import json
d=json.load(open('src/data/content.json','r',encoding='utf-8'))
for s in d['subjects']:
 if s['id']=='science':
  for c in s['chapters']:
   if c['id']=='digestive-system':
    c['exercises'].extend([
{'id':'d4','type':'mcq','difficulty':'easy','prompt':'What is the main function of the stomach?','prompt_zh':'胃的主要功能是什么？','choices':['To mix food with gastric juices and break it down','To absorb most nutrients','To absorb water','To store waste'],'choices_zh':['将食物与胃液混合并分解','吸收大部分营养','吸收水分','储存废物'],'answer':0,'explanation':'The stomach churns food and mixes it with gastric juices containing acid and enzymes to break it down further.','explanation_zh':'胃搅拌食物，将其与含有酸和酶的胃液混合，进一步分解食物。'},
{'id':'d5','type':'mcq','difficulty':'medium','prompt':'Where does most nutrient absorption occur?','prompt_zh':'大部分营养吸收发生在哪里？','choices':['Small intestine','Stomach','Large intestine','Mouth'],'choices_zh':['小肠','胃','大肠','口'],'answer':0,'explanation':'The small intestine is the main site of nutrient absorption.','explanation_zh':'小肠是营养吸收的主要场所。'},
{'id':'d6','type':'mcq','difficulty':'medium','prompt':'What is the main function of the large intestine?','prompt_zh':'大肠的主要功能是什么？','choices':['To absorb water and form feces','To digest proteins','To produce enzymes','To absorb nutrients'],'choices_zh':['吸收水分并形成粪便','消化蛋白质','产生酶','吸收营养'],'answer':0,'explanation':'The large intestine absorbs water from undigested food.','explanation_zh':'大肠从未消化的食物中吸收水分。'},
{'id':'d7','type':'multi','difficulty':'medium','prompt':'Which are parts of the digestive system? (Select all)','prompt_zh':'以下哪些是消化系统的一部分？','choices':['Mouth','Liver','Heart','Stomach','Lungs','Small intestine'],'choices_zh':['口','肝脏','心脏','胃','肺','小肠'],'answer':[0,1,3,5],'explanation':'Mouth, liver, stomach, and small intestine are parts of the digestive system.','explanation_zh':'口、肝脏、胃和小肠都是消化系统的一部分。'},
{'id':'d8','type':'mcq','difficulty':'hard','prompt':'What are the end products of protein digestion?','prompt_zh':'蛋白质消化的最终产物是什么？','choices':['Amino acids','Glucose','Fatty acids','Starch'],'choices_zh':['氨基酸','葡萄糖','脂肪酸','淀粉'],'answer':0,'explanation':'Proteins are broken down into amino acids.','explanation_zh':'蛋白质被分解成氨基酸。'},
{'id':'d9','type':'mcq','difficulty':'hard','prompt':'Which enzyme breaks down carbohydrates?','prompt_zh':'哪种酶分解碳水化合物？','choices':['Carbohydrase (e.g., amylase)','Protease','Lipase','Nuclease'],'choices_zh':['碳水化合物酶（例如淀粉酶）','蛋白酶','脂肪酶','核酸酶'],'answer':0,'explanation':'Carbohydrases like amylase break down carbohydrates.','explanation_zh':'碳水化合物酶将碳水化合物分解。'},
{'id':'d10','type':'mcq','difficulty':'easy','prompt':'What happens to undigested food?','prompt_zh':'未消化的食物会怎样？','choices':['It is removed as feces','It is stored in liver','It is converted to energy','It is absorbed by stomach'],'choices_zh':['作为粪便排出','储存在肝脏中','转化为能量','被胃吸收'],'answer':0,'explanation':'Undigested food is eliminated as feces.','explanation_zh':'未消化的食物作为粪便排出。'},
{'id':'d11','type':'short','difficulty':'medium','prompt':'How long is the small intestine in meters?','prompt_zh':'小肠有多长（米）？','answer':'6','acceptedAnswers':['6','6m','six','about 6'],'explanation':'The small intestine is about 6 meters long.','explanation_zh':'小肠约6米长。'},
{'id':'d12','type':'mcq','difficulty':'easy','prompt':'What connects the mouth to the stomach?','prompt_zh':'连接口腔和胃的是什么？','choices':['Esophagus','Trachea','Small intestine','Large intestine'],'choices_zh':['食道','气管','小肠','大肠'],'answer':0,'explanation':'The esophagus connects mouth to stomach.','explanation_zh':'食道连接口腔和胃。'},
{'id':'d13','type':'mcq','difficulty':'medium','prompt':'Easiest food after stomach upset?','prompt_zh':'胃部不适后最温和的食物？','choices':['Plain porridge','Spicy laksa','Fried chicken rice','Ice kacang'],'choices_zh':['白粥','辣叻沙','炸鸡饭','冰淇淋'],'answer':0,'explanation':'Plain porridge is gentle on stomach.','explanation_zh':'白粥对胃温和。'},
{'id':'d14','type':'mcq','difficulty':'hard','prompt':'Why do diabetics manage food intake?','prompt_zh':'糖尿病患者为何管理饮食？','choices':['Control blood sugar','Avoid hunger','Prevent tooth decay','Build muscle'],'choices_zh':['控制血糖','避免饥饿','预防蛀牙','增强肌肉'],'answer':0,'explanation':'To control blood glucose levels.','explanation_zh':'控制血糖水平。'},
{'id':'d15','type':'mcq','difficulty':'easy','prompt':'Final exit point for food waste?','prompt_zh':'食物废物的最终出口？','choices':['Anus','Mouth','Small intestine','Stomach'],'choices_zh':['肛门','口','小肠','胃'],'answer':0,'explanation':'Feces leaves through the anus.','explanation_zh':'粪便从肛门排出。'}
])
json.dump(d,open('src/data/content.json','w',encoding='utf-8'),ensure_ascii=False,indent=2)
print('Added 12 exercises')
