#!/usr/bin/env python3
"""JC2 Physics Batch 5: Quantum Physics + Nuclear Physics (25 exercises)"""
import json

with open('chapters/jc2_physics_chapters.json', 'r', encoding='utf-8') as f:
    chapters = json.load(f)

# Quantum Physics - 13 exercises (4 easy + 5 medium + 4 hard)
quantum_physics = [
    {"id": "quantum-jc2-ex1", "type": "mcq", "difficulty": "easy", "prompt": "Photoelectric effect: electrons emitted when light hits metal surface. Einstein explained using:", "prompt_zh": "光电效应：光照射金属表面时发射电子。爱因斯坦用什么解释：", "choices": ["Wave theory", "Particle theory (photons)", "Classical mechanics", "Electromagnetic theory"], "choices_zh": ["波动理论", "粒子理论（光子）", "经典力学", "电磁理论"], "answer": 1, "explanation": "**Problem:** Theory explaining photoelectric effect.\n\n**Key Concept:** Einstein's photon theory (light as particles).\n\n**Steps:** Classical wave theory failed. Einstein proposed light quanta (photons) with E = hf.\n\n**Answer:** Particle theory (photons).\n\n**Common Mistakes:** Thinking wave theory works.\n\n**Tip:** Singapore's solar panels use photoelectric effect—photons knock electrons free to create current!", "explanation_zh": "**问题：** 解释光电效应的理论。\n\n**关键概念：** 爱因斯坦的光子理论（光作为粒子）。\n\n**步骤：** 经典波动理论失败。爱因斯坦提出光量子（光子）E=hf。\n\n**答案：** 粒子理论（光子）。\n\n**常见错误：** 认为波动理论有效。\n\n**提示：** 新加坡太阳能板使用光电效应—光子击出电子产生电流！"},

    {"id": "quantum-jc2-ex2", "type": "short", "difficulty": "easy", "prompt": "Photon energy E = hf. h = 6.63×10⁻³⁴J·s, f = 5×10¹⁴Hz. E in 10⁻¹⁹J?", "prompt_zh": "光子能量E=hf。h=6.63×10⁻³⁴焦·秒，f=5×10¹⁴赫兹。E（10⁻¹⁹焦）？", "answer": "3.32", "validator": "numeric", "explanation": "**Problem:** Calculate photon energy.\n\n**Key Concept:** E = hf.\n\n**Steps:**\n1. E = 6.63×10⁻³⁴ × 5×10¹⁴\n2. E = 33.15×10⁻²⁰\n3. E = 3.315×10⁻¹⁹J ≈ 3.32×10⁻¹⁹J\n\n**Answer:** 3.32 (units: 10⁻¹⁹J).\n\n**Common Mistakes:** Calculation or power of 10 errors.\n\n**Tip:** LED lights in Singapore HDB corridors emit specific photon energies—color determined by E = hf!", "explanation_zh": "**问题：** 计算光子能量。\n\n**关键概念：** E=hf。\n\n**步骤：**\n1. E=6.63×10⁻³⁴×5×10¹⁴\n2. E=33.15×10⁻²⁰\n3. E=3.315×10⁻¹⁹焦≈3.32×10⁻¹⁹焦\n\n**答案：** 3.32（单位：10⁻¹⁹焦）。\n\n**常见错误：** 计算或10的幂错误。\n\n**提示：** 新加坡组屋走廊的LED灯发射特定光子能量—颜色由E=hf决定！"},

    {"id": "quantum-jc2-ex3", "type": "mcq", "difficulty": "easy", "prompt": "Work function Φ: minimum energy to remove electron from metal. If photon energy < Φ:", "prompt_zh": "逸出功Φ：从金属移除电子的最小能量。如果光子能量<Φ：", "choices": ["Electrons emitted with low KE", "Many electrons emitted", "No electrons emitted", "Electrons emitted after delay"], "choices_zh": ["发射低动能电子", "发射许多电子", "不发射电子", "延迟后发射电子"], "answer": 2, "explanation": "**Problem:** Photoelectric effect threshold.\n\n**Key Concept:** If E_photon < Φ, no emission (threshold frequency).\n\n**Steps:**\n1. Need E ≥ Φ to overcome binding\n2. If E < Φ, insufficient energy\n3. Zero emission regardless of intensity\n\n**Answer:** No electrons emitted.\n\n**Common Mistakes:** Thinking high intensity helps (it doesn't if E < Φ).\n\n**Tip:** UV security sensors in Singapore buildings won't trigger with visible light—need high enough photon energy!", "explanation_zh": "**问题：** 光电效应阈值。\n\n**关键概念：** 如果E光子<Φ，无发射（阈值频率）。\n\n**步骤：**\n1. 需要E≥Φ以克服结合\n2. 如果E<Φ，能量不足\n3. 无论强度如何零发射\n\n**答案：** 不发射电子。\n\n**常见错误：** 认为高强度有帮助（如果E<Φ则没有）。\n\n**提示：** 新加坡建筑的紫外线安全传感器不会被可见光触发—需要足够高的光子能量！"},

    {"id": "quantum-jc2-ex4", "type": "mcq", "difficulty": "easy", "prompt": "de Broglie wavelength λ = h/p. Applies to:", "prompt_zh": "德布罗意波长λ=h/p。适用于：", "choices": ["Only photons", "Only electrons", "All particles", "Only charged particles"], "choices_zh": ["仅光子", "仅电子", "所有粒子", "仅带电粒子"], "answer": 2, "explanation": "**Problem:** Applicability of de Broglie relation.\n\n**Key Concept:** Wave-particle duality applies to ALL matter.\n\n**Steps:** de Broglie proposed all particles have wave properties with λ = h/p.\n\n**Answer:** All particles (universal wave-particle duality).\n\n**Common Mistakes:** Thinking only electrons or photons.\n\n**Tip:** Electron microscopes in Singapore universities use electron waves—shorter λ than light for better resolution!", "explanation_zh": "**问题：** 德布罗意关系的适用性。\n\n**关键概念：** 波粒二象性适用于所有物质。\n\n**步骤：** 德布罗意提出所有粒子具有波动性质，λ=h/p。\n\n**答案：** 所有粒子（普遍波粒二象性）。\n\n**常见错误：** 认为仅电子或光子。\n\n**提示：** 新加坡大学的电子显微镜使用电子波—比光更短的λ获得更好分辨率！"},

    {"id": "quantum-jc2-ex5", "type": "short", "difficulty": "medium", "prompt": "Max KE of photoelectrons: KE_max = hf - Φ. hf = 5eV, Φ = 2eV. KE_max in eV?", "prompt_zh": "光电子最大动能：KE最大=hf-Φ。hf=5电子伏，Φ=2电子伏。KE最大（电子伏）？", "answer": "3", "validator": "numeric", "explanation": "**Problem:** Calculate maximum kinetic energy of photoelectrons.\n\n**Key Concept:** Einstein's photoelectric equation: KE_max = hf - Φ.\n\n**Steps:**\n1. KE_max = hf - Φ\n2. KE_max = 5 - 2 = 3eV\n\n**Answer:** 3eV.\n\n**Common Mistakes:** Adding instead of subtracting.\n\n**Tip:** Photocathodes in Singapore's night vision devices—excess energy becomes electron KE!", "explanation_zh": "**问题：** 计算光电子最大动能。\n\n**关键概念：** 爱因斯坦光电方程：KE最大=hf-Φ。\n\n**步骤：**\n1. KE最大=hf-Φ\n2. KE最大=5-2=3电子伏\n\n**答案：** 3电子伏。\n\n**常见错误：** 相加而不是相减。\n\n**提示：** 新加坡夜视设备中的光阴极—多余能量变成电子动能！"},

    {"id": "quantum-jc2-ex6", "type": "mcq", "difficulty": "medium", "prompt": "Stopping potential V_s: minimum voltage to stop photoelectrons. eV_s = KE_max means:", "prompt_zh": "遏止电位V_s：阻止光电子的最小电压。eV_s=KE最大意味着：", "choices": ["V_s independent of frequency", "V_s increases with intensity", "V_s increases with frequency", "V_s always constant"], "choices_zh": ["V_s与频率无关", "V_s随强度增加", "V_s随频率增加", "V_s总是恒定"], "answer": 2, "explanation": "**Problem:** Stopping potential dependence.\n\n**Key Concept:** eV_s = KE_max = hf - Φ → V_s ∝ f.\n\n**Steps:**\n1. KE_max = hf - Φ\n2. eV_s = hf - Φ\n3. Higher f → higher V_s\n\n**Answer:** V_s increases with frequency.\n\n**Common Mistakes:** Thinking V_s depends on intensity.\n\n**Tip:** Photomultiplier tubes in Singapore labs measure V_s to determine photon frequency!", "explanation_zh": "**问题：** 遏止电位的依赖性。\n\n**关键概念：** eV_s=KE最大=hf-Φ→V_s∝f。\n\n**步骤：**\n1. KE最大=hf-Φ\n2. eV_s=hf-Φ\n3. 更高f→更高V_s\n\n**答案：** V_s随频率增加。\n\n**常见错误：** 认为V_s取决于强度。\n\n**提示：** 新加坡实验室的光电倍增管测量V_s以确定光子频率！"},

    {"id": "quantum-jc2-ex7", "type": "short", "difficulty": "medium", "prompt": "Electron (m=9.1×10⁻³¹kg, v=10⁶m/s). de Broglie λ = h/mv. h=6.63×10⁻³⁴J·s. λ in nm (10⁻⁹m)?", "prompt_zh": "电子（m=9.1×10⁻³¹千克，v=10⁶米/秒）。德布罗意λ=h/mv。h=6.63×10⁻³⁴焦·秒。λ（纳米）？", "answer": "0.728", "validator": "numeric", "explanation": "**Problem:** Calculate de Broglie wavelength of electron.\n\n**Key Concept:** λ = h/(mv).\n\n**Steps:**\n1. λ = 6.63×10⁻³⁴/(9.1×10⁻³¹ × 10⁶)\n2. λ = 6.63×10⁻³⁴/(9.1×10⁻²⁵)\n3. λ ≈ 7.28×10⁻¹⁰m = 0.728nm\n\n**Answer:** 0.728nm.\n\n**Common Mistakes:** Calculation or unit conversion errors.\n\n**Tip:** Electron wavelength comparable to atomic spacing—enables electron diffraction in Singapore's material science labs!", "explanation_zh": "**问题：** 计算电子的德布罗意波长。\n\n**关键概念：** λ=h/(mv)。\n\n**步骤：**\n1. λ=6.63×10⁻³⁴/(9.1×10⁻³¹×10⁶)\n2. λ=6.63×10⁻³⁴/(9.1×10⁻²⁵)\n3. λ≈7.28×10⁻¹⁰米=0.728纳米\n\n**答案：** 0.728纳米。\n\n**常见错误：** 计算或单位转换错误。\n\n**提示：** 电子波长与原子间距相当—使新加坡材料科学实验室能够进行电子衍射！"},

    {"id": "quantum-jc2-ex8", "type": "mcq", "difficulty": "medium", "prompt": "Heisenberg Uncertainty Principle: ΔxΔp ≥ h/(4π). Cannot simultaneously know:", "prompt_zh": "海森堡不确定性原理：ΔxΔp≥h/(4π)。不能同时知道：", "choices": ["Position and velocity", "Position and momentum", "Energy and time", "Both B and C"], "choices_zh": ["位置和速度", "位置和动量", "能量和时间", "B和C都是"], "answer": 3, "explanation": "**Problem:** What uncertainty principle limits.\n\n**Key Concept:** Cannot precisely know conjugate pairs: (x, p) and (E, t).\n\n**Steps:**\n1. ΔxΔp ≥ h/(4π) - position-momentum\n2. ΔEΔt ≥ h/(4π) - energy-time\n3. Fundamental quantum limit\n\n**Answer:** Both position-momentum AND energy-time.\n\n**Common Mistakes:** Thinking it's measurement error (it's fundamental).\n\n**Tip:** Singapore's quantum computing research deals with these fundamental limits!", "explanation_zh": "**问题：** 不确定性原理限制什么。\n\n**关键概念：** 不能精确知道共轭对：（x，p）和（E，t）。\n\n**步骤：**\n1. ΔxΔp≥h/(4π)-位置-动量\n2. ΔEΔt≥h/(4π)-能量-时间\n3. 基本量子极限\n\n**答案：** 位置-动量和能量-时间都是。\n\n**常见错误：** 认为是测量误差（是基本的）。\n\n**提示：** 新加坡量子计算研究处理这些基本极限！"},

    {"id": "quantum-jc2-ex9", "type": "short", "difficulty": "hard", "prompt": "Hydrogen atom energy levels: E_n = -13.6/n² eV. Energy of photon emitted in transition n=3 to n=2?", "prompt_zh": "氢原子能级：E_n=-13.6/n²电子伏。从n=3到n=2跃迁发射的光子能量？", "answer": "1.89", "validator": "numeric", "explanation": "**Problem:** Calculate photon energy from atomic transition.\n\n**Key Concept:** E_photon = E_upper - E_lower = ΔE.\n\n**Steps:**\n1. E₃ = -13.6/9 = -1.51eV\n2. E₂ = -13.6/4 = -3.40eV\n3. ΔE = -1.51 - (-3.40) = 1.89eV\n\n**Answer:** 1.89eV (visible red light).\n\n**Common Mistakes:** Sign errors or wrong formula.\n\n**Tip:** Hydrogen discharge tubes in Singapore physics labs emit this red line (Balmer series)!", "explanation_zh": "**问题：** 从原子跃迁计算光子能量。\n\n**关键概念：** E光子=E上-E下=ΔE。\n\n**步骤：**\n1. E₃=-13.6/9=-1.51电子伏\n2. E₂=-13.6/4=-3.40电子伏\n3. ΔE=-1.51-(-3.40)=1.89电子伏\n\n**答案：** 1.89电子伏（可见红光）。\n\n**常见错误：** 符号错误或公式错误。\n\n**提示：** 新加坡物理实验室的氢放电管发射这条红线（巴尔默系列）！"},

    {"id": "quantum-jc2-ex10", "type": "mcq", "difficulty": "hard", "prompt": "Line spectra vs continuous spectra. Atoms emit line spectra because:", "prompt_zh": "线光谱与连续光谱。原子发射线光谱因为：", "choices": ["Electrons continuous energy", "Discrete energy levels", "Wave nature of light", "Classical radiation"], "choices_zh": ["电子连续能量", "离散能级", "光的波动性", "经典辐射"], "answer": 1, "explanation": "**Problem:** Why line spectra exist.\n\n**Key Concept:** Quantized energy levels → discrete photon energies → line spectra.\n\n**Steps:**\n1. Electrons occupy discrete energy levels\n2. Transitions emit specific ΔE photons\n3. Result: discrete wavelengths (lines)\n\n**Answer:** Discrete energy levels.\n\n**Common Mistakes:** Thinking continuous energy possible.\n\n**Tip:** Neon signs in Singapore's Chinatown emit characteristic red-orange lines from discrete Ne atom transitions!", "explanation_zh": "**问题：** 为什么存在线光谱。\n\n**关键概念：** 量子化能级→离散光子能量→线光谱。\n\n**步骤：**\n1. 电子占据离散能级\n2. 跃迁发射特定ΔE光子\n3. 结果：离散波长（线）\n\n**答案：** 离散能级。\n\n**常见错误：** 认为连续能量可能。\n\n**提示：** 新加坡牛车水的霓虹灯从离散Ne原子跃迁发射特征红橙线！"},

    {"id": "quantum-jc2-ex11", "type": "short", "difficulty": "hard", "prompt": "Wave-particle duality. Photon momentum p = E/c = h/λ. λ = 500nm. p in 10⁻²⁷kg·m/s?", "prompt_zh": "波粒二象性。光子动量p=E/c=h/λ。λ=500纳米。p（10⁻²⁷千克·米/秒）？", "answer": "1.33", "validator": "numeric", "explanation": "**Problem:** Calculate photon momentum from wavelength.\n\n**Key Concept:** p = h/λ (photon momentum).\n\n**Steps:**\n1. λ = 500nm = 5×10⁻⁷m\n2. p = 6.63×10⁻³⁴/(5×10⁻⁷)\n3. p ≈ 1.33×10⁻²⁷kg·m/s\n\n**Answer:** 1.33 (units: 10⁻²⁷kg·m/s).\n\n**Common Mistakes:** Unit conversion errors.\n\n**Tip:** Light pressure from photon momentum powers solar sails—future spacecraft technology!", "explanation_zh": "**问题：** 从波长计算光子动量。\n\n**关键概念：** p=h/λ（光子动量）。\n\n**步骤：**\n1. λ=500纳米=5×10⁻⁷米\n2. p=6.63×10⁻³⁴/(5×10⁻⁷)\n3. p≈1.33×10⁻²⁷千克·米/秒\n\n**答案：** 1.33（单位：10⁻²⁷千克·米/秒）。\n\n**常见错误：** 单位转换错误。\n\n**提示：** 光子动量的光压驱动太阳帆—未来航天器技术！"},

    {"id": "quantum-jc2-ex12", "type": "mcq", "difficulty": "hard", "prompt": "Compton scattering: photon collides with electron, wavelength:", "prompt_zh": "康普顿散射：光子与电子碰撞，波长：", "choices": ["Decreases", "Stays same", "Increases", "Becomes zero"], "choices_zh": ["减少", "保持不变", "增加", "变为零"], "answer": 2, "explanation": "**Problem:** Wavelength change in Compton scattering.\n\n**Key Concept:** Photon transfers energy to electron → lower photon energy → longer λ.\n\n**Steps:**\n1. Photon-electron collision\n2. Photon loses energy (E = hf decreases)\n3. Lower f → longer λ (c = fλ)\n\n**Answer:** Wavelength increases.\n\n**Common Mistakes:** Thinking wavelength decreases.\n\n**Tip:** X-ray scattering in Singapore hospitals demonstrates Compton effect—scattered X-rays have longer wavelength!", "explanation_zh": "**问题：** 康普顿散射中的波长变化。\n\n**关键概念：** 光子将能量转移给电子→光子能量降低→更长λ。\n\n**步骤：**\n1. 光子-电子碰撞\n2. 光子失去能量（E=hf减少）\n3. 更低f→更长λ（c=fλ）\n\n**答案：** 波长增加。\n\n**常见错误：** 认为波长减少。\n\n**提示：** 新加坡医院的X射线散射展示康普顿效应—散射X射线有更长波长！"},

    {"id": "quantum-jc2-ex13", "type": "short", "difficulty": "hard", "prompt": "Bohr model: angular momentum L = nℏ (n=1,2,3...). ℏ = h/(2π) = 1.05×10⁻³⁴J·s. Ground state (n=1) L?", "prompt_zh": "玻尔模型：角动量L=nℏ（n=1,2,3...）。ℏ=h/(2π)=1.05×10⁻³⁴焦·秒。基态（n=1）L？", "answer": "1.05e-34", "validator": "numeric", "explanation": "**Problem:** Angular momentum in Bohr's ground state.\n\n**Key Concept:** L = nℏ, ground state n = 1.\n\n**Steps:**\n1. n = 1 (ground state)\n2. L = 1 × ℏ\n3. L = 1.05×10⁻³⁴J·s\n\n**Answer:** 1.05×10⁻³⁴J·s (one unit of ℏ).\n\n**Common Mistakes:** Using n = 0 (not allowed).\n\n**Tip:** Quantized angular momentum explains why atoms don't collapse—minimum L prevents electron from falling into nucleus!", "explanation_zh": "**问题：** 玻尔基态中的角动量。\n\n**关键概念：** L=nℏ，基态n=1。\n\n**步骤：**\n1. n=1（基态）\n2. L=1×ℏ\n3. L=1.05×10⁻³⁴焦·秒\n\n**答案：** 1.05×10⁻³⁴焦·秒（一个ℏ单位）。\n\n**常见错误：** 使用n=0（不允许）。\n\n**提示：** 量子化角动量解释为什么原子不坍缩—最小L防止电子落入核！"}
]

# Nuclear Physics - 12 exercises (3 easy + 5 medium + 4 hard)
nuclear_physics = [
    {"id": "nuclear-jc2-ex1", "type": "mcq", "difficulty": "easy", "prompt": "Alpha particle is:", "prompt_zh": "阿尔法粒子是：", "choices": ["Helium nucleus (2 protons + 2 neutrons)", "Electron", "Photon", "Hydrogen nucleus"], "choices_zh": ["氦核（2质子+2中子）", "电子", "光子", "氢核"], "answer": 0, "explanation": "**Problem:** Identify alpha particle.\n\n**Key Concept:** α = He nucleus (₂⁴He).\n\n**Steps:** Alpha decay emits helium-4 nucleus: 2 protons + 2 neutrons.\n\n**Answer:** Helium nucleus (2p + 2n).\n\n**Common Mistakes:** Confusing with other radiation types.\n\n**Tip:** Smoke detectors in Singapore buildings use alpha emitter (Am-241)—ionizes air to detect smoke!", "explanation_zh": "**问题：** 识别阿尔法粒子。\n\n**关键概念：** α=氦核（₂⁴氦）。\n\n**步骤：** 阿尔法衰变发射氦-4核：2质子+2中子。\n\n**答案：** 氦核（2p+2n）。\n\n**常见错误：** 与其他辐射类型混淆。\n\n**提示：** 新加坡建筑的烟雾探测器使用阿尔法发射器（Am-241）—电离空气检测烟雾！"},

    {"id": "nuclear-jc2-ex2", "type": "short", "difficulty": "easy", "prompt": "Half-life t₁/₂: time for half of nuclei to decay. Initial 1000 nuclei, t₁/₂ = 10s. After 20s, how many remain?", "prompt_zh": "半衰期t₁/₂：一半核衰变的时间。初始1000核，t₁/₂=10秒。20秒后剩余多少？", "answer": "250", "validator": "numeric", "explanation": "**Problem:** Apply half-life concept.\n\n**Key Concept:** After n half-lives: N = N₀/2ⁿ.\n\n**Steps:**\n1. 20s = 2 half-lives (20/10)\n2. N = 1000/2² = 1000/4 = 250\n\n**Answer:** 250 nuclei.\n\n**Common Mistakes:** Using linear decay instead of exponential.\n\n**Tip:** Medical isotopes in Singapore hospitals (Tc-99m) have 6-hour half-life—carefully timed for imaging!", "explanation_zh": "**问题：** 应用半衰期概念。\n\n**关键概念：** n个半衰期后：N=N₀/2ⁿ。\n\n**步骤：**\n1. 20秒=2个半衰期（20/10）\n2. N=1000/2²=1000/4=250\n\n**答案：** 250个核。\n\n**常见错误：** 使用线性衰变而不是指数。\n\n**提示：** 新加坡医院的医用同位素（Tc-99m）半衰期6小时—仔细定时用于成像！"},

    {"id": "nuclear-jc2-ex3", "type": "mcq", "difficulty": "easy", "prompt": "Beta minus (β⁻) decay emits:", "prompt_zh": "贝塔负（β⁻）衰变发射：", "choices": ["Proton", "Neutron", "Electron", "Positron"], "choices_zh": ["质子", "中子", "电子", "正电子"], "answer": 2, "explanation": "**Problem:** What is emitted in β⁻ decay.\n\n**Key Concept:** β⁻ = electron (from neutron → proton + electron).\n\n**Steps:** Neutron converts to proton, emits electron and antineutrino.\n\n**Answer:** Electron (high-energy).\n\n**Common Mistakes:** Confusing with positron (β⁺).\n\n**Tip:** Beta radiation from medical tracers in Singapore—penetrates tissue but stopped by aluminum!", "explanation_zh": "**问题：** β⁻衰变中发射什么。\n\n**关键概念：** β⁻=电子（从中子→质子+电子）。\n\n**步骤：** 中子转换为质子，发射电子和反中微子。\n\n**答案：** 电子（高能）。\n\n**常见错误：** 与正电子（β⁺）混淆。\n\n**提示：** 新加坡医用示踪剂的贝塔辐射—穿透组织但被铝阻止！"},

    {"id": "nuclear-jc2-ex4", "type": "short", "difficulty": "medium", "prompt": "Activity A = λN (decay rate). λ = ln2/t₁/₂. t₁/₂ = 10s, N = 10⁶. A in decays/s?", "prompt_zh": "活度A=λN（衰变率）。λ=ln2/t₁/₂。t₁/₂=10秒，N=10⁶。A（衰变/秒）？", "answer": "69300", "validator": "numeric", "explanation": "**Problem:** Calculate radioactive activity.\n\n**Key Concept:** A = λN, where λ = ln2/t₁/₂.\n\n**Steps:**\n1. λ = 0.693/10 = 0.0693 s⁻¹\n2. A = 0.0693 × 10⁶\n3. A ≈ 69,300 decays/s (or Bq)\n\n**Answer:** 69,300 decays/s.\n\n**Common Mistakes:** Forgetting to calculate λ first.\n\n**Tip:** Radiation safety in Singapore labs—activity measured in becquerels (Bq = decays/s)!", "explanation_zh": "**问题：** 计算放射性活度。\n\n**关键概念：** A=λN，其中λ=ln2/t₁/₂。\n\n**步骤：**\n1. λ=0.693/10=0.0693秒⁻¹\n2. A=0.0693×10⁶\n3. A≈69,300衰变/秒（或贝克）\n\n**答案：** 69,300衰变/秒。\n\n**常见错误：** 忘记先计算λ。\n\n**提示：** 新加坡实验室的辐射安全—活度以贝克勒尔（Bq=衰变/秒）测量！"},

    {"id": "nuclear-jc2-ex5", "type": "mcq", "difficulty": "medium", "prompt": "Mass defect Δm in nucleus. Binding energy E = Δmc². Higher binding energy per nucleon means:", "prompt_zh": "核中的质量亏损Δm。结合能E=Δmc²。每核子更高结合能意味着：", "choices": ["Less stable", "More stable", "Easier to split", "Lower mass"], "choices_zh": ["较不稳定", "更稳定", "更容易分裂", "更低质量"], "answer": 1, "explanation": "**Problem:** Binding energy and nuclear stability.\n\n**Key Concept:** Higher BE/nucleon → more stable nucleus.\n\n**Steps:**\n1. Binding energy = energy to disassemble nucleus\n2. Higher BE/nucleon = more energy needed\n3. More stable\n\n**Answer:** More stable.\n\n**Common Mistakes:** Thinking higher BE means less stable.\n\n**Tip:** Iron-56 has highest BE/nucleon—most stable nucleus, explaining why stars produce Fe!", "explanation_zh": "**问题：** 结合能和核稳定性。\n\n**关键概念：** 更高BE/核子→更稳定核。\n\n**步骤：**\n1. 结合能=拆解核所需能量\n2. 更高BE/核子=需要更多能量\n3. 更稳定\n\n**答案：** 更稳定。\n\n**常见错误：** 认为更高BE意味着较不稳定。\n\n**提示：** 铁-56有最高BE/核子—最稳定核，解释为什么恒星产生Fe！"},

    {"id": "nuclear-jc2-ex6", "type": "short", "difficulty": "medium", "prompt": "Nuclear fission: U-235 + neutron → products + 200MeV. 1eV = 1.6×10⁻¹⁹J. Energy in joules?", "prompt_zh": "核裂变：U-235+中子→产物+200兆电子伏。1电子伏=1.6×10⁻¹⁹焦。能量（焦）？", "answer": "3.2e-11", "validator": "numeric", "explanation": "**Problem:** Convert fission energy to joules.\n\n**Key Concept:** Unit conversion MeV → J.\n\n**Steps:**\n1. E = 200MeV = 200×10⁶eV\n2. E = 200×10⁶ × 1.6×10⁻¹⁹J\n3. E = 3.2×10⁻¹¹J\n\n**Answer:** 3.2×10⁻¹¹J per fission.\n\n**Common Mistakes:** Power of 10 errors.\n\n**Tip:** Nuclear power research at NTU—one U-235 fission releases enormous energy from tiny mass!", "explanation_zh": "**问题：** 将裂变能量转换为焦耳。\n\n**关键概念：** 单位转换兆电子伏→焦。\n\n**步骤：**\n1. E=200兆电子伏=200×10⁶电子伏\n2. E=200×10⁶×1.6×10⁻¹⁹焦\n3. E=3.2×10⁻¹¹焦\n\n**答案：** 每次裂变3.2×10⁻¹¹焦。\n\n**常见错误：** 10的幂错误。\n\n**提示：** 南大的核能研究—一次U-235裂变从微小质量释放巨大能量！"},

    {"id": "nuclear-jc2-ex7", "type": "mcq", "difficulty": "medium", "prompt": "Nuclear fusion requires high temperature because:", "prompt_zh": "核聚变需要高温因为：", "choices": ["Nuclei move faster", "Overcome electrostatic repulsion", "Increase binding energy", "Produce neutrons"], "choices_zh": ["核运动更快", "克服静电排斥", "增加结合能", "产生中子"], "answer": 1, "explanation": "**Problem:** Why fusion needs high temperature.\n\n**Key Concept:** Need KE to overcome Coulomb barrier (proton-proton repulsion).\n\n**Steps:**\n1. Both nuclei positively charged\n2. Repel via electrostatic force\n3. High T → high KE → overcome barrier\n\n**Answer:** Overcome electrostatic repulsion.\n\n**Common Mistakes:** Thinking it's just for speed.\n\n**Tip:** Sun's core at 15 million K enables fusion—Singapore's fusion research aims to replicate this!", "explanation_zh": "**问题：** 为什么聚变需要高温。\n\n**关键概念：** 需要动能克服库仑势垒（质子-质子排斥）。\n\n**步骤：**\n1. 两个核都带正电\n2. 通过静电力排斥\n3. 高T→高动能→克服势垒\n\n**答案：** 克服静电排斥。\n\n**常见错误：** 认为只是为了速度。\n\n**提示：** 太阳核心1500万开尔文使聚变成为可能—新加坡聚变研究旨在复制这一点！"},

    {"id": "nuclear-jc2-ex8", "type": "short", "difficulty": "medium", "prompt": "E = mc². Mass defect Δm = 0.03u in fusion. 1u = 931.5MeV/c². Energy released in MeV?", "prompt_zh": "E=mc²。聚变中质量亏损Δm=0.03原子质量单位。1原子质量单位=931.5兆电子伏/c²。释放能量（兆电子伏）？", "answer": "27.9", "validator": "numeric", "explanation": "**Problem:** Calculate fusion energy from mass defect.\n\n**Key Concept:** E = Δm × 931.5MeV (when Δm in atomic mass units).\n\n**Steps:**\n1. E = Δm × c²\n2. E = 0.03 × 931.5MeV\n3. E ≈ 27.9MeV\n\n**Answer:** 27.9MeV.\n\n**Common Mistakes:** Forgetting conversion factor.\n\n**Tip:** Fusion in Sun converts 4 million tons mass to energy per second—powering life on Earth!", "explanation_zh": "**问题：** 从质量亏损计算聚变能量。\n\n**关键概念：** E=Δm×931.5兆电子伏（当Δm以原子质量单位时）。\n\n**步骤：**\n1. E=Δm×c²\n2. E=0.03×931.5兆电子伏\n3. E≈27.9兆电子伏\n\n**答案：** 27.9兆电子伏。\n\n**常见错误：** 忘记转换因子。\n\n**提示：** 太阳中的聚变每秒将400万吨质量转换为能量—为地球生命提供动力！"},

    {"id": "nuclear-jc2-ex9", "type": "short", "difficulty": "hard", "prompt": "Exponential decay: N = N₀e⁻ᵏᵗ. λ = 0.1s⁻¹, t = 5s. Fraction remaining N/N₀?", "prompt_zh": "指数衰变：N=N₀e⁻ᵏᵗ。λ=0.1秒⁻¹，t=5秒。剩余分数N/N₀？", "answer": "0.607", "validator": "numeric", "explanation": "**Problem:** Calculate fraction remaining using exponential decay.\n\n**Key Concept:** N/N₀ = e⁻ᵏᵗ.\n\n**Steps:**\n1. N/N₀ = e⁻⁰·¹ˣ⁵\n2. N/N₀ = e⁻⁰·⁵\n3. N/N₀ ≈ 0.607 (60.7%)\n\n**Answer:** 0.607.\n\n**Common Mistakes:** Calculation errors with exponential.\n\n**Tip:** Carbon-14 dating uses exponential decay—archaeologists in Singapore date artifacts using this!", "explanation_zh": "**问题：** 使用指数衰变计算剩余分数。\n\n**关键概念：** N/N₀=e⁻ᵏᵗ。\n\n**步骤：**\n1. N/N₀=e⁻⁰·¹ˣ⁵\n2. N/N₀=e⁻⁰·⁵\n3. N/N₀≈0.607（60.7%）\n\n**答案：** 0.607。\n\n**常见错误：** 指数计算错误。\n\n**提示：** 碳-14定年使用指数衰变—新加坡考古学家用此给文物定年！"},

    {"id": "nuclear-jc2-ex10", "type": "mcq", "difficulty": "hard", "prompt": "Chain reaction in nuclear fission requires:", "prompt_zh": "核裂变中的链式反应需要：", "choices": ["Fast neutrons only", "Critical mass and moderator", "High temperature", "Gamma rays"], "choices_zh": ["仅快中子", "临界质量和慢化剂", "高温", "伽马射线"], "answer": 1, "explanation": "**Problem:** Requirements for sustained chain reaction.\n\n**Key Concept:** Need critical mass + neutron moderator (slow neutrons).\n\n**Steps:**\n1. Each fission produces neutrons\n2. Need enough mass for neutrons to hit another nucleus\n3. Moderator slows neutrons (increases capture probability)\n\n**Answer:** Critical mass and moderator.\n\n**Common Mistakes:** Thinking only mass matters.\n\n**Tip:** Nuclear reactors use water as moderator—slows neutrons to thermal speeds for efficient fission!", "explanation_zh": "**问题：** 持续链式反应的要求。\n\n**关键概念：** 需要临界质量+中子慢化剂（慢中子）。\n\n**步骤：**\n1. 每次裂变产生中子\n2. 需要足够质量使中子击中另一个核\n3. 慢化剂减慢中子（增加捕获概率）\n\n**答案：** 临界质量和慢化剂。\n\n**常见错误：** 认为只有质量重要。\n\n**提示：** 核反应堆使用水作为慢化剂—将中子减慢到热速度以实现高效裂变！"},

    {"id": "nuclear-jc2-ex11", "type": "short", "difficulty": "hard", "prompt": "Absorbed dose (Gy): energy absorbed per kg. 1Gy = 1J/kg. 50mJ absorbed by 0.1kg tissue. Dose in Gy?", "prompt_zh": "吸收剂量（戈瑞）：每千克吸收的能量。1戈瑞=1焦/千克。50毫焦被0.1千克组织吸收。剂量（戈瑞）？", "answer": "0.5", "validator": "numeric", "explanation": "**Problem:** Calculate absorbed radiation dose.\n\n**Key Concept:** Dose (Gy) = Energy (J) / Mass (kg).\n\n**Steps:**\n1. E = 50mJ = 0.05J\n2. m = 0.1kg\n3. Dose = 0.05/0.1 = 0.5Gy\n\n**Answer:** 0.5Gy.\n\n**Common Mistakes:** Unit conversion errors (mJ to J).\n\n**Tip:** Singapore radiation safety limits: occupational exposure <20mSv/year—medical staff carefully monitored!", "explanation_zh": "**问题：** 计算吸收辐射剂量。\n\n**关键概念：** 剂量（戈瑞）=能量（焦）/质量（千克）。\n\n**步骤：**\n1. E=50毫焦=0.05焦\n2. m=0.1千克\n3. 剂量=0.05/0.1=0.5戈瑞\n\n**答案：** 0.5戈瑞。\n\n**常见错误：** 单位转换错误（毫焦到焦）。\n\n**提示：** 新加坡辐射安全限值：职业暴露<20毫希沃特/年—医疗人员仔细监测！"},

    {"id": "nuclear-jc2-ex12", "type": "mcq", "difficulty": "hard", "prompt": "PET scan uses positron emission. Positron-electron annihilation produces:", "prompt_zh": "PET扫描使用正电子发射。正电子-电子湮灭产生：", "choices": ["One gamma photon", "Two gamma photons (180° apart)", "Alpha particle", "Neutrino"], "choices_zh": ["一个伽马光子", "两个伽马光子（相距180°）", "阿尔法粒子", "中微子"], "answer": 1, "explanation": "**Problem:** Products of positron-electron annihilation.\n\n**Key Concept:** e⁺ + e⁻ → 2γ (back-to-back, conservation of momentum).\n\n**Steps:**\n1. Matter-antimatter annihilation\n2. Total mass → energy (E = mc²)\n3. Two 511keV photons at 180° (momentum conservation)\n\n**Answer:** Two gamma photons (180° apart).\n\n**Common Mistakes:** Thinking only one photon.\n\n**Tip:** PET scanners in Singapore hospitals detect these coincident photons to locate tumors precisely!", "explanation_zh": "**问题：** 正电子-电子湮灭的产物。\n\n**关键概念：** e⁺+e⁻→2γ（背靠背，动量守恒）。\n\n**步骤：**\n1. 物质-反物质湮灭\n2. 总质量→能量（E=mc²）\n3. 两个511千电子伏光子相距180°（动量守恒）\n\n**答案：** 两个伽马光子（相距180°）。\n\n**常见错误：** 认为只有一个光子。\n\n**提示：** 新加坡医院的PET扫描仪检测这些符合光子以精确定位肿瘤！"}
]

for ch in chapters:
    if ch['id'] == 'quantum-physics-jc2-physics':
        ch['exercises'] = quantum_physics
        print(f"✓ Added {len(quantum_physics)} exercises to Quantum Physics")
    elif ch['id'] == 'nuclear-physics-jc2-physics':
        ch['exercises'] = nuclear_physics
        print(f"✓ Added {len(nuclear_physics)} exercises to Nuclear Physics")

with open('chapters/jc2_physics_chapters.json', 'w', encoding='utf-8') as f:
    json.dump(chapters, f, ensure_ascii=False, indent=2)

print(f"\n✅ Batch 5 Complete: 25 exercises added (Quantum: 13 + Nuclear: 12)")
print(f"   Total so far: 65 + 25 = 90 exercises")
print(f"\n🎉 ALL JC2 PHYSICS EXERCISES COMPLETE!")
print(f"   Final totals: 8 chapters, 24 sections, 90 exercises")
print(f"   Matches JC1 Physics exercise count!")
