#!/usr/bin/env python3
"""
Create exercises for Sec 4 Biology chapters (4 chapters × 15 exercises = 60 exercises)
"""
import json

exercises_by_chapter = {
    "human-health-disease-sec4-bio": [
        # Easy (5)
        {"id": "hhd-ex1", "type": "mcq", "difficulty": "easy",
         "prompt": "What is the function of white blood cells in the immune system?",
         "prompt_zh": "白细胞在免疫系统中的功能是什么？",
         "choices": ["Fight pathogens and infections", "Carry oxygen", "Help blood clotting", "Transport nutrients"],
         "choices_zh": ["对抗病原体和感染", "携带氧气", "帮助血液凝固", "运输营养"],
         "answer": 0,
         "hint": "The body's defense cells",
         "hint_zh": "身体的防御细胞",
         "explanation": "**Problem:** Function of white blood cells\n\n**Answer:** Fight pathogens and infections\n\n**Types:**\n- **Phagocytes:** Engulf and digest pathogens\n- **Lymphocytes:** Produce antibodies, destroy infected cells\n\n**Red blood cells:** Carry oxygen\n**Platelets:** Help clotting"},
        {"id": "hhd-ex2", "type": "mcq", "difficulty": "easy",
         "prompt": "Which of these is a pathogen?",
         "prompt_zh": "以下哪个是病原体？",
         "choices": ["Bacteria that cause tuberculosis", "Red blood cells", "Antibodies", "Skin cells"],
         "choices_zh": ["引起结核病的细菌", "红细胞", "抗体", "皮肤细胞"],
         "answer": 0,
         "hint": "Disease-causing microorganism",
         "hint_zh": "致病微生物",
         "explanation": "**Problem:** Identify a pathogen\n\n**Answer:** Bacteria that cause tuberculosis\n\n**Pathogens:** Disease-causing organisms\n- Bacteria (TB, cholera)\n- Viruses (COVID-19, dengue)\n- Fungi (ringworm)\n- Protists (malaria)"},
        {"id": "hhd-ex3", "type": "short", "difficulty": "easy",
         "prompt": "Name the type of immunity you get after recovering from a disease.",
         "prompt_zh": "说出你从疾病康复后获得的免疫类型。",
         "answer": "active immunity",
         "hint": "Your body made the antibodies itself",
         "hint_zh": "你的身体自己制造了抗体",
         "explanation": "**Problem:** Type of immunity from recovery\n\n**Answer:** Active immunity (natural active)\n\n**Types of immunity:**\n- **Active natural:** From infection\n- **Active artificial:** From vaccination\n- **Passive natural:** From mother (breast milk, placenta)\n- **Passive artificial:** From injection of antibodies"},
        {"id": "hhd-ex4", "type": "mcq", "difficulty": "easy",
         "prompt": "What is the first line of defense against pathogens?",
         "prompt_zh": "抵御病原体的第一道防线是什么？",
         "choices": ["Skin and mucous membranes", "White blood cells", "Antibodies", "Vaccination"],
         "choices_zh": ["皮肤和黏膜", "白细胞", "抗体", "疫苗接种"],
         "answer": 0,
         "hint": "Physical and chemical barriers",
         "hint_zh": "物理和化学屏障",
         "explanation": "**Problem:** First line of defense\n\n**Answer:** Skin and mucous membranes\n\n**First line defenses:**\n- Skin (physical barrier)\n- Mucus in nose/throat (traps pathogens)\n- Stomach acid (kills pathogens)\n- Tears/saliva (contain lysozyme)"},
        {"id": "hhd-ex5", "type": "mcq", "difficulty": "easy",
         "prompt": "What is a non-communicable disease (NCD)?",
         "prompt_zh": "什么是非传染性疾病（NCD）？",
         "choices": ["A disease that cannot spread between people", "A disease caused by bacteria", "A disease spread by mosquitoes", "A disease cured by antibiotics"],
         "choices_zh": ["不能在人与人之间传播的疾病", "由细菌引起的疾病", "由蚊子传播的疾病", "可用抗生素治愈的疾病"],
         "answer": 0,
         "hint": "Heart disease, diabetes, cancer are examples",
         "hint_zh": "心脏病、糖尿病、癌症是例子",
         "explanation": "**Problem:** Definition of NCD\n\n**Answer:** A disease that cannot spread between people\n\n**Examples:**\n- Cardiovascular disease\n- Diabetes\n- Cancer\n- COPD\n\n**Causes:** Usually lifestyle, genetics, environment (not pathogens)"},
        # Medium (5)
        {"id": "hhd-ex6", "type": "mcq", "difficulty": "medium",
         "prompt": "How do antibodies help fight infection?",
         "prompt_zh": "抗体如何帮助对抗感染？",
         "choices": ["Bind to antigens on pathogens, marking them for destruction", "Directly kill all cells in the body", "Produce more pathogens", "Break down food molecules"],
         "choices_zh": ["与病原体上的抗原结合，标记它们以便销毁", "直接杀死体内所有细胞", "产生更多病原体", "分解食物分子"],
         "answer": 0,
         "hint": "Lock-and-key fit with antigens",
         "hint_zh": "与抗原的锁钥配合",
         "explanation": "**Problem:** How antibodies work\n\n**Answer:** Bind to antigens on pathogens, marking them for destruction\n\n**Antibody actions:**\n- **Agglutination:** Clump pathogens together\n- **Neutralization:** Block pathogen's active sites\n- **Mark for phagocytosis:** Help phagocytes identify targets\n\n**Specific:** Each antibody matches specific antigen"},
        {"id": "hhd-ex7", "type": "mcq", "difficulty": "medium",
         "prompt": "Why does antibiotic resistance develop?",
         "prompt_zh": "为什么会产生抗生素耐药性？",
         "choices": ["Bacteria evolve when exposed to antibiotics; resistant ones survive", "Antibiotics become weaker over time", "Human bodies reject antibiotics", "Viruses attack antibiotics"],
         "choices_zh": ["细菌在接触抗生素时进化；耐药的存活下来", "抗生素随时间变弱", "人体排斥抗生素", "病毒攻击抗生素"],
         "answer": 0,
         "hint": "Natural selection in bacteria",
         "hint_zh": "细菌的自然选择",
         "explanation": "**Problem:** Cause of antibiotic resistance\n\n**Answer:** Bacteria evolve when exposed to antibiotics; resistant ones survive\n\n**Process:**\n1. Some bacteria naturally have mutations for resistance\n2. Antibiotics kill susceptible bacteria\n3. Resistant bacteria survive and multiply\n4. Over time, resistant bacteria dominate\n\n**Prevention:** Complete antibiotic courses, don't misuse antibiotics"},
        {"id": "hhd-ex8", "type": "mcq", "difficulty": "medium",
         "prompt": "What is the vector for dengue fever in Singapore?",
         "prompt_zh": "在新加坡，登革热的传播媒介是什么？",
         "choices": ["Aedes mosquito", "Housefly", "Rat", "Contaminated water"],
         "choices_zh": ["伊蚊", "家蝇", "老鼠", "污染的水"],
         "answer": 0,
         "hint": "Day-biting mosquito, breeds in stagnant water",
         "hint_zh": "日间叮咬的蚊子，在死水中繁殖",
         "explanation": "**Problem:** Dengue vector\n\n**Answer:** Aedes mosquito (Aedes aegypti and Aedes albopictus)\n\n**Singapore control:**\n- Mozzie Wipeout (remove stagnant water)\n- NEA Gravitrap surveillance\n- Project Wolbachia (male mosquitoes reduce transmission)\n- Fines for breeding sites"},
        {"id": "hhd-ex9", "type": "short", "difficulty": "medium",
         "prompt": "What type of cells retain 'memory' of pathogens for long-term immunity?",
         "prompt_zh": "什么类型的细胞保留对病原体的'记忆'以实现长期免疫？",
         "answer": "memory cells",
         "hint": "Memory B-cells and Memory T-cells",
         "hint_zh": "记忆B细胞和记忆T细胞",
         "explanation": "**Problem:** Cells for long-term immunity\n\n**Answer:** Memory cells (Memory B-cells and Memory T-cells)\n\n**Function:**\n- Remain in body after infection\n- Quickly recognize same pathogen if it returns\n- Rapid response = immunity\n\n**Why vaccination works:** Creates memory cells without full infection"},
        {"id": "hhd-ex10", "type": "mcq", "difficulty": "medium",
         "prompt": "Which lifestyle factor is the biggest risk for lung cancer?",
         "prompt_zh": "哪个生活方式因素是肺癌的最大风险？",
         "choices": ["Smoking", "Drinking water", "Sleeping too much", "Eating vegetables"],
         "choices_zh": ["吸烟", "喝水", "睡太多", "吃蔬菜"],
         "answer": 0,
         "hint": "Responsible for 90% of lung cancer cases",
         "hint_zh": "导致90%的肺癌病例",
         "explanation": "**Problem:** Biggest risk factor for lung cancer\n\n**Answer:** Smoking\n\n**Statistics:** ~90% of lung cancer cases linked to smoking\n\n**Singapore:**\n- Smoke-free public places\n- High tobacco tax\n- Graphic health warnings\n- Plain packaging\n\n**Other lung cancer risks:** Air pollution, radon, asbestos"},
        # Hard (5)
        {"id": "hhd-ex11", "type": "mcq", "difficulty": "hard",
         "prompt": "How does a vaccine provide immunity without causing disease?",
         "prompt_zh": "疫苗如何在不引起疾病的情况下提供免疫力？",
         "choices": ["Contains weakened/dead pathogens or antigens that trigger antibody production", "Directly provides antibodies to fight disease", "Kills all bacteria in the body", "Strengthens the skin barrier"],
         "choices_zh": ["含有弱化/死亡的病原体或抗原，触发抗体产生", "直接提供抗体对抗疾病", "杀死体内所有细菌", "加强皮肤屏障"],
         "answer": 0,
         "hint": "Triggers immune response without full infection",
         "hint_zh": "触发免疫反应而不完全感染",
         "explanation": "**Problem:** How vaccines work\n\n**Answer:** Contains weakened/dead pathogens or antigens that trigger antibody production\n\n**Types of vaccines:**\n- **Live attenuated:** Weakened pathogen (MMR)\n- **Inactivated:** Killed pathogen (polio)\n- **Subunit:** Parts of pathogen (hepatitis B)\n- **mRNA:** Genetic instructions for antigen (COVID-19)\n\n**Result:** Memory cells formed without disease symptoms"},
        {"id": "hhd-ex12", "type": "mcq", "difficulty": "hard",
         "prompt": "Why can't antibiotics treat viral infections like COVID-19?",
         "prompt_zh": "为什么抗生素不能治疗像COVID-19这样的病毒感染？",
         "choices": ["Antibiotics target bacterial structures that viruses don't have", "Viruses are larger than bacteria", "Antibiotics are too strong for viruses", "Viruses live outside the body"],
         "choices_zh": ["抗生素针对病毒没有的细菌结构", "病毒比细菌大", "抗生素对病毒来说太强", "病毒生活在体外"],
         "answer": 0,
         "hint": "Antibiotics target cell walls, ribosomes - viruses have neither",
         "hint_zh": "抗生素针对细胞壁、核糖体 - 病毒两者都没有",
         "explanation": "**Problem:** Why antibiotics don't work on viruses\n\n**Answer:** Antibiotics target bacterial structures that viruses don't have\n\n**Antibiotics target:**\n- Cell wall synthesis\n- Protein synthesis (bacterial ribosomes)\n- DNA replication\n\n**Viruses:**\n- No cell wall\n- Use host's ribosomes\n- Very different structure\n\n**Treatment:** Antivirals (different mechanism)"},
        {"id": "hhd-ex13", "type": "short", "difficulty": "hard",
         "prompt": "Name the process where phagocytes engulf and destroy pathogens.",
         "prompt_zh": "说出吞噬细胞吞噬和消灭病原体的过程名称。",
         "answer": "phagocytosis",
         "hint": "Phago- means 'eating'",
         "hint_zh": "Phago-意为'吃'",
         "explanation": "**Problem:** Process of engulfing pathogens\n\n**Answer:** Phagocytosis\n\n**Steps:**\n1. Phagocyte detects pathogen\n2. Extends pseudopodia around pathogen\n3. Engulfs pathogen into vesicle\n4. Lysosomes fuse with vesicle\n5. Enzymes digest pathogen\n6. Debris expelled"},
        {"id": "hhd-ex14", "type": "mcq", "difficulty": "hard",
         "prompt": "What is herd immunity?",
         "prompt_zh": "什么是群体免疫？",
         "choices": ["When enough people are immune to stop disease spread", "Immunity shared between animals and humans", "Immunity from eating meat", "Immunity that weakens over time"],
         "choices_zh": ["当足够多的人免疫以阻止疾病传播时", "动物和人类之间共享的免疫", "吃肉获得的免疫", "随时间减弱的免疫"],
         "answer": 0,
         "hint": "Protects those who can't be vaccinated",
         "hint_zh": "保护那些不能接种疫苗的人",
         "explanation": "**Problem:** Definition of herd immunity\n\n**Answer:** When enough people are immune to stop disease spread\n\n**Threshold:** Usually 80-95% depending on disease\n\n**Importance:**\n- Protects babies (too young for vaccines)\n- Protects immunocompromised (can't be vaccinated)\n- Breaks chain of transmission\n\n**Singapore:** High COVID-19 vaccination rate achieved herd immunity"},
        {"id": "hhd-ex15", "type": "mcq", "difficulty": "hard",
         "prompt": "Diabetes Type 2 is primarily caused by:",
         "prompt_zh": "2型糖尿病主要由什么引起？",
         "choices": ["Insulin resistance and lifestyle factors", "Viral infection", "Genetic defect present from birth", "Bacterial infection"],
         "choices_zh": ["胰岛素抵抗和生活方式因素", "病毒感染", "出生时就存在的基因缺陷", "细菌感染"],
         "answer": 0,
         "hint": "Related to obesity, diet, lack of exercise",
         "hint_zh": "与肥胖、饮食、缺乏运动有关",
         "explanation": "**Problem:** Main cause of Type 2 diabetes\n\n**Answer:** Insulin resistance and lifestyle factors\n\n**Risk factors:**\n- Obesity (especially abdominal)\n- Physical inactivity\n- Poor diet (high sugar, refined carbs)\n- Family history\n\n**Singapore:** 1 in 9 adults has diabetes - \"War on Diabetes\" campaign\n\n**Type 1:** Autoimmune (different cause)"}
    ],
    
    "dna-genetics-advanced-sec4-bio": [
        # Easy (5)
        {"id": "dga-ex1", "type": "mcq", "difficulty": "easy",
         "prompt": "What does DNA stand for?",
         "prompt_zh": "DNA代表什么？",
         "choices": ["Deoxyribonucleic acid", "Dinitrogen acid", "Dual nucleic acid", "Dynamic nitrogen acid"],
         "choices_zh": ["脱氧核糖核酸", "二氮酸", "双核酸", "动态氮酸"],
         "answer": 0,
         "hint": "Contains deoxyribose sugar",
         "hint_zh": "含有脱氧核糖",
         "explanation": "**Problem:** Full name of DNA\n\n**Answer:** Deoxyribonucleic acid\n\n**Components:**\n- Deoxyribo- : deoxyribose sugar\n- Nucleic: in nucleus\n- Acid: acidic molecule\n\n**Structure:** Double helix, discovered by Watson and Crick (1953)"},
        {"id": "dga-ex2", "type": "mcq", "difficulty": "easy",
         "prompt": "Which base pairs with adenine (A) in DNA?",
         "prompt_zh": "DNA中哪个碱基与腺嘌呤（A）配对？",
         "choices": ["Thymine (T)", "Guanine (G)", "Cytosine (C)", "Uracil (U)"],
         "choices_zh": ["胸腺嘧啶 (T)", "鸟嘌呤 (G)", "胞嘧啶 (C)", "尿嘧啶 (U)"],
         "answer": 0,
         "hint": "A-T and G-C pairing",
         "hint_zh": "A-T 和 G-C 配对",
         "explanation": "**Problem:** Base pairing rule for adenine\n\n**Answer:** Thymine (T)\n\n**Base pairing rules:**\n- A pairs with T (2 hydrogen bonds)\n- G pairs with C (3 hydrogen bonds)\n\n**Memory:** AT (like 'at') and GC (like 'good connection')"},
        {"id": "dga-ex3", "type": "short", "difficulty": "easy",
         "prompt": "What is a gene?",
         "prompt_zh": "什么是基因？",
         "answer": "section of DNA that codes for a protein",
         "hint": "Determines a specific characteristic",
         "hint_zh": "决定特定特征",
         "explanation": "**Problem:** Definition of gene\n\n**Answer:** A section of DNA that codes for a protein (or specific characteristic)\n\n**Key points:**\n- Contains instructions for making one protein\n- Located on chromosomes\n- Inherited from parents\n\n**Human genome:** ~20,000-25,000 genes"},
        {"id": "dga-ex4", "type": "mcq", "difficulty": "easy",
         "prompt": "What is the shape of a DNA molecule?",
         "prompt_zh": "DNA分子的形状是什么？",
         "choices": ["Double helix", "Single strand", "Circular ring", "Square lattice"],
         "choices_zh": ["双螺旋", "单链", "圆环", "方格"],
         "answer": 0,
         "hint": "Like a twisted ladder",
         "hint_zh": "像扭曲的梯子",
         "explanation": "**Problem:** Shape of DNA\n\n**Answer:** Double helix\n\n**Structure:**\n- Two strands twisted around each other\n- Sugar-phosphate backbone (sides)\n- Base pairs (rungs)\n- Discovered by Watson and Crick (1953)"},
        {"id": "dga-ex5", "type": "mcq", "difficulty": "easy",
         "prompt": "Where is DNA found in a eukaryotic cell?",
         "prompt_zh": "DNA在真核细胞的哪里？",
         "choices": ["Nucleus", "Cytoplasm", "Cell membrane", "Ribosomes"],
         "choices_zh": ["细胞核", "细胞质", "细胞膜", "核糖体"],
         "answer": 0,
         "hint": "The control center of the cell",
         "hint_zh": "细胞的控制中心",
         "explanation": "**Problem:** Location of DNA\n\n**Answer:** Nucleus\n\n**Also found in:**\n- Mitochondria (mtDNA)\n- Chloroplasts (in plants)\n\n**Prokaryotes:** DNA in cytoplasm (no nucleus)"},
        # Medium (5)
        {"id": "dga-ex6", "type": "mcq", "difficulty": "medium",
         "prompt": "What is the first step of protein synthesis?",
         "prompt_zh": "蛋白质合成的第一步是什么？",
         "choices": ["Transcription (DNA → mRNA)", "Translation (mRNA → protein)", "DNA replication", "Cell division"],
         "choices_zh": ["转录 (DNA → mRNA)", "翻译 (mRNA → 蛋白质)", "DNA复制", "细胞分裂"],
         "answer": 0,
         "hint": "Making a messenger copy of the gene",
         "hint_zh": "制作基因的信使拷贝",
         "explanation": "**Problem:** First step of protein synthesis\n\n**Answer:** Transcription (DNA → mRNA)\n\n**Steps:**\n1. **Transcription** (in nucleus): DNA → mRNA\n2. mRNA leaves nucleus\n3. **Translation** (at ribosome): mRNA → protein\n\n**Why two steps?** DNA is too large/valuable to leave nucleus"},
        {"id": "dga-ex7", "type": "short", "difficulty": "medium",
         "prompt": "If a DNA strand is ATGCCG, what is the complementary strand?",
         "prompt_zh": "如果DNA链是ATGCCG，互补链是什么？",
         "answer": "TACGGC",
         "hint": "A pairs with T, G pairs with C",
         "hint_zh": "A与T配对，G与C配对",
         "explanation": "**Problem:** Find complementary DNA strand\n\n**Rules:** A↔T, G↔C\n\n**Given:** A-T-G-C-C-G\n**Complement:** T-A-C-G-G-C\n\n**Answer:** TACGGC"},
        {"id": "dga-ex8", "type": "mcq", "difficulty": "medium",
         "prompt": "What is a codon?",
         "prompt_zh": "什么是密码子？",
         "choices": ["A sequence of 3 bases that codes for one amino acid", "A type of protein", "The entire DNA molecule", "A single nucleotide"],
         "choices_zh": ["编码一个氨基酸的3个碱基序列", "一种蛋白质", "整个DNA分子", "单个核苷酸"],
         "answer": 0,
         "hint": "Triplet code",
         "hint_zh": "三联体密码",
         "explanation": "**Problem:** Definition of codon\n\n**Answer:** A sequence of 3 bases that codes for one amino acid\n\n**Example:** AUG codes for methionine (start codon)\n\n**Genetic code:**\n- 64 possible codons (4³)\n- 61 code for amino acids\n- 3 are stop codons (UAA, UAG, UGA)"},
        {"id": "dga-ex9", "type": "mcq", "difficulty": "medium",
         "prompt": "What is a mutation?",
         "prompt_zh": "什么是突变？",
         "choices": ["A change in the DNA sequence", "Normal cell division", "The process of making proteins", "Transfer of genes between species"],
         "choices_zh": ["DNA序列的改变", "正常细胞分裂", "制造蛋白质的过程", "物种间基因转移"],
         "answer": 0,
         "hint": "Can be caused by radiation, chemicals, or random errors",
         "hint_zh": "可由辐射、化学物质或随机错误引起",
         "explanation": "**Problem:** Definition of mutation\n\n**Answer:** A change in the DNA sequence\n\n**Types:**\n- Substitution (one base replaced)\n- Insertion (extra base added)\n- Deletion (base removed)\n\n**Effects:** Can be harmful, neutral, or beneficial"},
        {"id": "dga-ex10", "type": "mcq", "difficulty": "medium",
         "prompt": "What is the role of mRNA in protein synthesis?",
         "prompt_zh": "mRNA在蛋白质合成中的作用是什么？",
         "choices": ["Carries genetic code from nucleus to ribosome", "Makes copies of DNA", "Brings amino acids to ribosome", "Forms the structure of ribosomes"],
         "choices_zh": ["将遗传密码从细胞核带到核糖体", "复制DNA", "将氨基酸带到核糖体", "形成核糖体结构"],
         "answer": 0,
         "hint": "m = messenger",
         "hint_zh": "m = 信使",
         "explanation": "**Problem:** Role of mRNA\n\n**Answer:** Carries genetic code from nucleus to ribosome\n\n**Types of RNA:**\n- **mRNA (messenger):** Carries code\n- **tRNA (transfer):** Brings amino acids\n- **rRNA (ribosomal):** Part of ribosome structure"},
        # Hard (5)
        {"id": "dga-ex11", "type": "mcq", "difficulty": "hard",
         "prompt": "What is CRISPR-Cas9 used for?",
         "prompt_zh": "CRISPR-Cas9用于什么？",
         "choices": ["Gene editing - cutting and modifying DNA precisely", "Taking photographs of DNA", "Counting chromosomes", "Making vaccines"],
         "choices_zh": ["基因编辑 - 精确切割和修改DNA", "给DNA拍照", "计数染色体", "制造疫苗"],
         "answer": 0,
         "hint": "Revolutionary gene editing technology (2020 Nobel Prize)",
         "hint_zh": "革命性的基因编辑技术（2020年诺贝尔奖）",
         "explanation": "**Problem:** Use of CRISPR-Cas9\n\n**Answer:** Gene editing - cutting and modifying DNA precisely\n\n**How it works:**\n- Guide RNA directs Cas9 enzyme to specific DNA sequence\n- Cas9 cuts DNA at that location\n- Cell repairs cut, can add/remove/edit genes\n\n**Applications:** Treating genetic diseases, creating GM crops, research"},
        {"id": "dga-ex12", "type": "short", "difficulty": "hard",
         "prompt": "If the mRNA codon is AUG, what is the tRNA anticodon?",
         "prompt_zh": "如果mRNA密码子是AUG，tRNA反密码子是什么？",
         "answer": "UAC",
         "hint": "Anticodon is complementary to codon (A-U, G-C)",
         "hint_zh": "反密码子与密码子互补（A-U，G-C）",
         "explanation": "**Problem:** Find tRNA anticodon\n\n**Rules:** A↔U, G↔C (in RNA)\n\n**mRNA codon:** A-U-G\n**tRNA anticodon:** U-A-C\n\n**Answer:** UAC\n\n**Note:** AUG is the start codon (codes for methionine)"},
        {"id": "dga-ex13", "type": "mcq", "difficulty": "hard",
         "prompt": "What is the advantage of producing human insulin using genetically modified bacteria?",
         "prompt_zh": "使用转基因细菌生产人类胰岛素有什么优势？",
         "choices": ["Identical to human insulin, cheaper, unlimited supply", "Bacteria naturally produce insulin", "It's faster to extract from pigs", "Insulin from bacteria is stronger"],
         "choices_zh": ["与人类胰岛素相同、更便宜、供应无限", "细菌自然产生胰岛素", "从猪中提取更快", "来自细菌的胰岛素更强"],
         "answer": 0,
         "hint": "Previously insulin came from pigs/cows (limited, possible allergies)",
         "hint_zh": "以前胰岛素来自猪/牛（有限，可能过敏）",
         "explanation": "**Problem:** Advantages of GM bacterial insulin\n\n**Answer:** Identical to human insulin, cheaper, unlimited supply\n\n**Process:**\n- Human insulin gene inserted into bacterial plasmid\n- Bacteria multiply rapidly, producing insulin\n- Purified for medical use\n\n**Advantages over animal insulin:**\n- No allergic reactions\n- Cheaper to produce\n- Unlimited supply\n- Ethically better"},
        {"id": "dga-ex14", "type": "mcq", "difficulty": "hard",
         "prompt": "What causes sickle cell anemia?",
         "prompt_zh": "什么导致镰刀型细胞贫血症？",
         "choices": ["A single base substitution mutation in hemoglobin gene", "A virus infection", "Lack of iron in diet", "Too many red blood cells"],
         "choices_zh": ["血红蛋白基因中的单碱基替换突变", "病毒感染", "饮食中缺铁", "红细胞太多"],
         "answer": 0,
         "hint": "One amino acid changed → abnormal hemoglobin",
         "hint_zh": "一个氨基酸改变 → 异常血红蛋白",
         "explanation": "**Problem:** Cause of sickle cell anemia\n\n**Answer:** A single base substitution mutation in hemoglobin gene\n\n**Mutation:**\n- DNA: CTC → CAC (one base change)\n- mRNA: GAG → GUG\n- Amino acid: Glutamic acid → Valine\n\n**Result:** Abnormal hemoglobin → sickle-shaped RBCs → blocked vessels, anemia"},
        {"id": "dga-ex15", "type": "mcq", "difficulty": "hard",
         "prompt": "What ethical concern exists about designer babies?",
         "prompt_zh": "关于设计婴儿存在什么伦理担忧？",
         "choices": ["Could lead to genetic discrimination and inequality", "Babies would be too healthy", "It's too expensive for hospitals", "Doctors don't know how to do it"],
         "choices_zh": ["可能导致基因歧视和不平等", "婴儿会太健康", "对医院来说太贵", "医生不知道怎么做"],
         "answer": 0,
         "hint": "Rich families selecting for intelligence, appearance...",
         "hint_zh": "富裕家庭选择智力、外貌...",
         "explanation": "**Problem:** Ethical concerns about designer babies\n\n**Answer:** Could lead to genetic discrimination and inequality\n\n**Concerns:**\n- Only wealthy could afford → genetic inequality\n- Selection for traits (intelligence, appearance) → eugenics\n- Playing God / interfering with nature\n- Unknown long-term effects\n- Consent issues (baby can't consent)\n\n**Singapore:** Human cloning prohibited by law"}
    ],
    
    "ecosystems-conservation-sec4-bio": [
        # Easy (5)
        {"id": "ec-ex1", "type": "mcq", "difficulty": "easy",
         "prompt": "What is a producer in a food chain?",
         "prompt_zh": "食物链中的生产者是什么？",
         "choices": ["An organism that makes its own food (plants)", "An animal that eats plants", "An animal that eats other animals", "A decomposer"],
         "choices_zh": ["自己制造食物的生物（植物）", "吃植物的动物", "吃其他动物的动物", "分解者"],
         "answer": 0,
         "hint": "Uses photosynthesis",
         "hint_zh": "使用光合作用",
         "explanation": "**Problem:** Definition of producer\n\n**Answer:** An organism that makes its own food (plants)\n\n**Examples:** Trees, grass, algae, phytoplankton\n\n**Producers use photosynthesis:**\n6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂\n\n**They are the base of all food chains.**"},
        {"id": "ec-ex2", "type": "mcq", "difficulty": "easy",
         "prompt": "What percentage of energy is typically passed to the next trophic level?",
         "prompt_zh": "通常有多少百分比的能量传递到下一个营养级？",
         "choices": ["10%", "50%", "90%", "100%"],
         "choices_zh": ["10%", "50%", "90%", "100%"],
         "answer": 0,
         "hint": "Most energy is lost as heat",
         "hint_zh": "大部分能量以热量形式损失",
         "explanation": "**Problem:** Energy transfer between trophic levels\n\n**Answer:** 10% (the '10% rule')\n\n**Where does 90% go?**\n- Heat from respiration/movement\n- Undigested material (feces)\n- Parts not eaten (bones, roots)\n\n**This is why food chains are short (4-5 levels max)**"},
        {"id": "ec-ex3", "type": "short", "difficulty": "easy",
         "prompt": "Name the process that recycles nutrients from dead organisms back into the soil.",
         "prompt_zh": "说出将死亡生物的养分回收到土壤中的过程名称。",
         "answer": "decomposition",
         "hint": "Done by bacteria and fungi",
         "hint_zh": "由细菌和真菌完成",
         "explanation": "**Problem:** Process recycling nutrients from dead matter\n\n**Answer:** Decomposition\n\n**Decomposers:** Bacteria, fungi\n\n**Process:**\n1. Break down dead organisms\n2. Release nutrients into soil\n3. Plants absorb nutrients\n4. Cycle continues\n\n**Important for:** Carbon cycle, nitrogen cycle"},
        {"id": "ec-ex4", "type": "mcq", "difficulty": "easy",
         "prompt": "What is biodiversity?",
         "prompt_zh": "什么是生物多样性？",
         "choices": ["The variety of life in an area", "The number of plants only", "The amount of water in an ecosystem", "The temperature range"],
         "choices_zh": ["一个地区生命的多样性", "仅植物的数量", "生态系统中的水量", "温度范围"],
         "answer": 0,
         "hint": "Bio = life, diversity = variety",
         "hint_zh": "Bio = 生命，diversity = 多样性",
         "explanation": "**Problem:** Definition of biodiversity\n\n**Answer:** The variety of life in an area\n\n**Three levels:**\n1. Genetic diversity (within species)\n2. Species diversity (number of species)\n3. Ecosystem diversity (variety of habitats)\n\n**Singapore:** ~400 bird species, 2000+ plant species despite small size"},
        {"id": "ec-ex5", "type": "mcq", "difficulty": "easy",
         "prompt": "What is a food web?",
         "prompt_zh": "什么是食物网？",
         "choices": ["Interconnected food chains showing feeding relationships", "A single straight line of who eats who", "A spider's web", "A fishing net"],
         "choices_zh": ["显示取食关系的相互连接的食物链", "谁吃谁的单一直线", "蜘蛛网", "渔网"],
         "answer": 0,
         "hint": "More complex than a food chain",
         "hint_zh": "比食物链更复杂",
         "explanation": "**Problem:** Definition of food web\n\n**Answer:** Interconnected food chains showing feeding relationships\n\n**Food chain:** Linear (grass → grasshopper → frog → snake)\n\n**Food web:** Complex network (many chains linked together)\n\n**More realistic** - most organisms eat multiple things"},
        # Medium (5)
        {"id": "ec-ex6", "type": "mcq", "difficulty": "medium",
         "prompt": "What is the main carbon reservoir on Earth?",
         "prompt_zh": "地球上主要的碳储库是什么？",
         "choices": ["Oceans and fossil fuels", "The atmosphere", "Living organisms", "Soil only"],
         "choices_zh": ["海洋和化石燃料", "大气", "生物体", "仅土壤"],
         "answer": 0,
         "hint": "Atmosphere has relatively small amount",
         "hint_zh": "大气中含量相对较少",
         "explanation": "**Problem:** Main carbon reservoir\n\n**Answer:** Oceans and fossil fuels\n\n**Carbon distribution:**\n- Oceans: ~38,000 Gt (dissolved CO₂, carbonates)\n- Fossil fuels: ~4,000 Gt (coal, oil, gas)\n- Atmosphere: ~750 Gt (0.04% CO₂)\n- Living organisms: ~550 Gt\n\n**Concern:** Burning fossil fuels releases stored carbon"},
        {"id": "ec-ex7", "type": "mcq", "difficulty": "medium",
         "prompt": "What is eutrophication?",
         "prompt_zh": "什么是富营养化？",
         "choices": ["Excess nutrients cause algal bloom, depleting oxygen", "Too much sunlight killing plants", "Water becoming too cold", "Fish population increasing"],
         "choices_zh": ["过多营养导致藻类大量繁殖，消耗氧气", "阳光过多杀死植物", "水变得太冷", "鱼类数量增加"],
         "answer": 0,
         "hint": "Caused by fertilizer runoff",
         "hint_zh": "由肥料径流引起",
         "explanation": "**Problem:** Definition of eutrophication\n\n**Answer:** Excess nutrients cause algal bloom, depleting oxygen\n\n**Process:**\n1. Fertilizer runoff enters water\n2. Algae grow rapidly (bloom)\n3. Algae die, bacteria decompose them\n4. Bacteria use up oxygen\n5. Fish and aquatic life suffocate\n\n**Singapore:** Strict regulations on fertilizer use"},
        {"id": "ec-ex8", "type": "short", "difficulty": "medium",
         "prompt": "Name a Singapore nature reserve that protects primary rainforest.",
         "prompt_zh": "说出一个保护原始雨林的新加坡自然保护区。",
         "answer": "Bukit Timah",
         "hint": "163 hectares of old-growth forest",
         "hint_zh": "163公顷的原始森林",
         "explanation": "**Problem:** Singapore nature reserve with primary rainforest\n\n**Answer:** Bukit Timah Nature Reserve\n\n**Facts:**\n- One of only 2 remaining primary rainforests in Singapore\n- 163 hectares\n- Home to diverse species (monitor lizards, long-tailed macaques)\n- Protected since 1883\n\n**Also accept:** Central Catchment Nature Reserve"},
        {"id": "ec-ex9", "type": "mcq", "difficulty": "medium",
         "prompt": "What is an invasive species?",
         "prompt_zh": "什么是入侵物种？",
         "choices": ["Non-native species that outcompetes native species", "A species that helps the ecosystem", "A species that has always lived in an area", "An endangered species"],
         "choices_zh": ["与本地物种竞争的非本地物种", "帮助生态系统的物种", "一直生活在某地区的物种", "濒危物种"],
         "answer": 0,
         "hint": "Introduced from elsewhere, causes harm",
         "hint_zh": "从其他地方引入，造成危害",
         "explanation": "**Problem:** Definition of invasive species\n\n**Answer:** Non-native species that outcompetes native species\n\n**Singapore examples:**\n- Red-eared slider turtle (pet trade)\n- Javan myna (displaces native birds)\n- Golden apple snail (aquarium trade)\n\n**Why problematic:**\n- No natural predators\n- Outcompete natives for resources"},
        {"id": "ec-ex10", "type": "mcq", "difficulty": "medium",
         "prompt": "What is the role of nitrogen-fixing bacteria?",
         "prompt_zh": "固氮细菌的作用是什么？",
         "choices": ["Convert atmospheric N₂ into ammonia for plants", "Release N₂ into atmosphere", "Break down proteins in dead matter", "Produce oxygen"],
         "choices_zh": ["将大气中的N₂转化为植物可用的氨", "将N₂释放到大气中", "分解死亡物质中的蛋白质", "产生氧气"],
         "answer": 0,
         "hint": "Found in root nodules of legumes",
         "hint_zh": "存在于豆科植物的根瘤中",
         "explanation": "**Problem:** Role of nitrogen-fixing bacteria\n\n**Answer:** Convert atmospheric N₂ into ammonia for plants\n\n**Process:**\n- N₂ (unreactive gas) → NH₃ (usable)\n- Found in root nodules of legumes (peas, beans)\n- Also: Rhizobium, Azotobacter\n\n**Why important:** Plants can't use N₂ directly, but need nitrogen for proteins"},
        # Hard (5)
        {"id": "ec-ex11", "type": "mcq", "difficulty": "hard",
         "prompt": "Why is the pyramid of energy always upright?",
         "prompt_zh": "为什么能量金字塔总是正立的？",
         "choices": ["Energy is lost at each trophic level (Second Law of Thermodynamics)", "There are always more producers than consumers", "Energy increases at each level", "All organisms have the same energy"],
         "choices_zh": ["每个营养级都会损失能量（热力学第二定律）", "生产者总是比消费者多", "能量在每个层级增加", "所有生物体有相同的能量"],
         "answer": 0,
         "hint": "Energy can't be recycled, only transferred with losses",
         "hint_zh": "能量不能被回收，只能带着损失传递",
         "explanation": "**Problem:** Why pyramid of energy is always upright\n\n**Answer:** Energy is lost at each trophic level (Second Law of Thermodynamics)\n\n**Unlike:**\n- Pyramid of numbers: Can be inverted (1 tree, many insects)\n- Pyramid of biomass: Usually upright, some exceptions\n\n**Energy pyramid: ALWAYS upright** because energy is lost as heat at each transfer"},
        {"id": "ec-ex12", "type": "short", "difficulty": "hard",
         "prompt": "Name the process in the nitrogen cycle that converts nitrates back to atmospheric nitrogen.",
         "prompt_zh": "说出氮循环中将硝酸盐转化回大气氮的过程名称。",
         "answer": "denitrification",
         "hint": "Done by denitrifying bacteria in anaerobic conditions",
         "hint_zh": "在厌氧条件下由反硝化细菌完成",
         "explanation": "**Problem:** Process converting nitrates to N₂\n\n**Answer:** Denitrification\n\n**Nitrogen cycle processes:**\n1. **Nitrogen fixation:** N₂ → NH₃\n2. **Nitrification:** NH₃ → NO₂⁻ → NO₃⁻\n3. **Assimilation:** Plants absorb NO₃⁻\n4. **Decomposition:** Dead matter → NH₃\n5. **Denitrification:** NO₃⁻ → N₂ (back to atmosphere)"},
        {"id": "ec-ex13", "type": "mcq", "difficulty": "hard",
         "prompt": "What is bioaccumulation?",
         "prompt_zh": "什么是生物积累？",
         "choices": ["Toxins concentrate as they move up food chain", "Plants accumulating carbon", "Bacteria multiplying in water", "Animals growing larger"],
         "choices_zh": ["毒素在食物链上层浓缩", "植物积累碳", "细菌在水中繁殖", "动物变大"],
         "answer": 0,
         "hint": "DDT example: plankton → fish → birds (highest concentration)",
         "hint_zh": "DDT例子：浮游生物 → 鱼 → 鸟（最高浓度）",
         "explanation": "**Problem:** Definition of bioaccumulation\n\n**Answer:** Toxins concentrate as they move up food chain\n\n**Example: DDT (pesticide)**\n- Plankton: 0.04 ppm\n- Small fish: 0.5 ppm\n- Large fish: 2 ppm\n- Birds: 25 ppm (causes thin eggshells)\n\n**Also called biomagnification**"},
        {"id": "ec-ex14", "type": "mcq", "difficulty": "hard",
         "prompt": "What is a carbon sink?",
         "prompt_zh": "什么是碳汇？",
         "choices": ["A reservoir that absorbs more carbon than it releases", "A place where carbon is burned", "A source of carbon dioxide", "A type of coal mine"],
         "choices_zh": ["吸收的碳比释放的多的储库", "燃烧碳的地方", "二氧化碳的来源", "一种煤矿"],
         "answer": 0,
         "hint": "Forests and oceans are examples",
         "hint_zh": "森林和海洋是例子",
         "explanation": "**Problem:** Definition of carbon sink\n\n**Answer:** A reservoir that absorbs more carbon than it releases\n\n**Examples:**\n- Forests (photosynthesis)\n- Oceans (CO₂ dissolves)\n- Peat bogs\n\n**Carbon source:** Releases more than absorbs (fossil fuel burning)\n\n**Singapore:** Tree planting creates carbon sinks"},
        {"id": "ec-ex15", "type": "mcq", "difficulty": "hard",
         "prompt": "Singapore's Sisters' Islands Marine Park was established to:",
         "prompt_zh": "新加坡姐妹岛海洋公园的设立目的是：",
         "choices": ["Protect coral reefs and marine biodiversity", "Increase fishing activities", "Build underwater hotels", "Extract oil from the seabed"],
         "choices_zh": ["保护珊瑚礁和海洋生物多样性", "增加捕鱼活动", "建造海底酒店", "从海底提取石油"],
         "answer": 0,
         "hint": "Singapore's first Marine Protected Area",
         "hint_zh": "新加坡第一个海洋保护区",
         "explanation": "**Problem:** Purpose of Sisters' Islands Marine Park\n\n**Answer:** Protect coral reefs and marine biodiversity\n\n**Established:** 2014 (Singapore's first MPA)\n\n**Features:**\n- No fishing allowed\n- Coral restoration projects\n- Research and monitoring\n- Educational programs\n\n**Biodiversity:** ~250 species of hard corals, 120+ fish species"}
    ],
    
    "human-impact-environment-sec4-bio": [
        # Easy (5)
        {"id": "hie-ex1", "type": "mcq", "difficulty": "easy",
         "prompt": "What is the main cause of global warming?",
         "prompt_zh": "全球变暖的主要原因是什么？",
         "choices": ["Increased greenhouse gases (mainly CO₂)", "Ozone layer thinning", "Volcanic eruptions", "Earthquakes"],
         "choices_zh": ["温室气体增加（主要是CO₂）", "臭氧层变薄", "火山爆发", "地震"],
         "answer": 0,
         "hint": "From burning fossil fuels",
         "hint_zh": "来自燃烧化石燃料",
         "explanation": "**Problem:** Main cause of global warming\n\n**Answer:** Increased greenhouse gases (mainly CO₂)\n\n**Sources:**\n- Burning fossil fuels (power, transport)\n- Deforestation (less CO₂ absorption)\n- Agriculture (methane from cattle)\n\n**Effect:** More heat trapped → rising temperatures"},
        {"id": "hie-ex2", "type": "mcq", "difficulty": "easy",
         "prompt": "What does 'Reduce, Reuse, Recycle' aim to do?",
         "prompt_zh": "'减少、重复使用、回收'旨在做什么？",
         "choices": ["Minimize waste and resource consumption", "Increase factory production", "Create more landfills", "Burn more fossil fuels"],
         "choices_zh": ["最小化废物和资源消耗", "增加工厂生产", "建造更多垃圾填埋场", "燃烧更多化石燃料"],
         "answer": 0,
         "hint": "The 3Rs of sustainability",
         "hint_zh": "可持续发展的3R原则",
         "explanation": "**Problem:** Goal of Reduce, Reuse, Recycle\n\n**Answer:** Minimize waste and resource consumption\n\n**Priority order:**\n1. **Reduce:** Use less in first place\n2. **Reuse:** Use items again\n3. **Recycle:** Convert waste into new materials\n\n**Singapore:** Blue bins for recyclables, e-waste collection points"},
        {"id": "hie-ex3", "type": "short", "difficulty": "easy",
         "prompt": "Name Singapore's only landfill.",
         "prompt_zh": "说出新加坡唯一的垃圾填埋场名称。",
         "answer": "Semakau",
         "hint": "An offshore landfill that's also a nature area",
         "hint_zh": "一个同时是自然区域的离岸垃圾填埋场",
         "explanation": "**Problem:** Singapore's only landfill\n\n**Answer:** Semakau Landfill\n\n**Facts:**\n- Offshore landfill (between 2 islands)\n- Receives incineration ash\n- Expected to last until ~2035\n- Unique: Also supports biodiversity (mangroves, coral)\n\n**Challenge:** Running out of space → need to reduce waste!"},
        {"id": "hie-ex4", "type": "mcq", "difficulty": "easy",
         "prompt": "What is deforestation?",
         "prompt_zh": "什么是森林砍伐？",
         "choices": ["Cutting down or clearing forests", "Planting more trees", "Protecting forests", "Growing food crops"],
         "choices_zh": ["砍伐或清除森林", "种植更多树木", "保护森林", "种植粮食作物"],
         "answer": 0,
         "hint": "Major environmental concern, especially in tropics",
         "hint_zh": "主要环境问题，尤其在热带地区",
         "explanation": "**Problem:** Definition of deforestation\n\n**Answer:** Cutting down or clearing forests\n\n**Causes:**\n- Agriculture (palm oil, cattle)\n- Logging (timber)\n- Urban expansion\n\n**Effects:**\n- Habitat loss\n- Less CO₂ absorption\n- Soil erosion\n- Climate change\n\n**Singapore:** Lost 95% of original forest, now protecting remainder"},
        {"id": "hie-ex5", "type": "mcq", "difficulty": "easy",
         "prompt": "What is sustainable development?",
         "prompt_zh": "什么是可持续发展？",
         "choices": ["Meeting present needs without compromising future generations", "Using resources as fast as possible", "Stopping all development", "Building more factories"],
         "choices_zh": ["满足当前需求而不损害后代", "尽快使用资源", "停止所有发展", "建造更多工厂"],
         "answer": 0,
         "hint": "Balance between environment, economy, and society",
         "hint_zh": "环境、经济和社会之间的平衡",
         "explanation": "**Problem:** Definition of sustainable development\n\n**Answer:** Meeting present needs without compromising future generations\n\n**Three pillars:**\n1. Environmental sustainability\n2. Economic sustainability\n3. Social sustainability\n\n**Singapore:** Green Plan 2030 targets sustainability goals"},
        # Medium (5)
        {"id": "hie-ex6", "type": "mcq", "difficulty": "medium",
         "prompt": "What is Singapore's main source of water for the Four National Taps?",
         "prompt_zh": "新加坡四大国家水喉的主要水源是什么？",
         "choices": ["Local catchment, imported water, NEWater, desalination", "Only imported water from Malaysia", "Only rainwater", "Only seawater"],
         "choices_zh": ["本地集水、进口水、新生水、海水淡化", "仅从马来西亚进口水", "仅雨水", "仅海水"],
         "answer": 0,
         "hint": "Singapore has 4 water sources for resilience",
         "hint_zh": "新加坡有4个水源保障供应",
         "explanation": "**Problem:** Singapore's Four National Taps\n\n**Answer:** Local catchment, imported water, NEWater, desalination\n\n**Details:**\n1. **Local catchment:** 17 reservoirs, 2/3 of land\n2. **Imported water:** From Malaysia (Johor)\n3. **NEWater:** Recycled wastewater (40% of demand)\n4. **Desalination:** Seawater → freshwater (30%)\n\n**Goal:** Self-sufficient by 2061 when Malaysia agreement expires"},
        {"id": "hie-ex7", "type": "mcq", "difficulty": "medium",
         "prompt": "Why is Singapore's domestic recycling rate low (~13%)?",
         "prompt_zh": "为什么新加坡的家庭回收率低（约13%）？",
         "choices": ["Contamination and lack of awareness", "No recycling facilities exist", "Recycling is illegal", "All waste is already recycled"],
         "choices_zh": ["污染和缺乏意识", "没有回收设施", "回收是非法的", "所有废物已被回收"],
         "answer": 0,
         "hint": "Food residue on recyclables is a major issue",
         "hint_zh": "可回收物上的食物残渣是主要问题",
         "explanation": "**Problem:** Why low domestic recycling rate\n\n**Answer:** Contamination and lack of awareness\n\n**Issues:**\n- Food residue contaminates recyclables\n- Don't know what's recyclable\n- Convenience (easier to use trash chute)\n\n**Solutions:**\n- Education campaigns\n- Clean recyclables before binning\n- Better labeling"},
        {"id": "hie-ex8", "type": "short", "difficulty": "medium",
         "prompt": "What is NEWater?",
         "prompt_zh": "什么是新生水？",
         "answer": "recycled wastewater",
         "hint": "Ultra-clean water from treated sewage",
         "hint_zh": "来自处理过的污水的超净水",
         "explanation": "**Problem:** Definition of NEWater\n\n**Answer:** Recycled wastewater (treated to ultra-clean standards)\n\n**Process:**\n1. Used water collected\n2. Primary and secondary treatment\n3. Microfiltration\n4. Reverse osmosis\n5. UV disinfection\n\n**Use:** Mainly industrial, some indirect potable use (added to reservoirs)"},
        {"id": "hie-ex9", "type": "mcq", "difficulty": "medium",
         "prompt": "What is Singapore's waste management strategy?",
         "prompt_zh": "新加坡的废物管理策略是什么？",
         "choices": ["Incineration to reduce volume, then landfill ash", "Dump all waste in the ocean", "Export all waste overseas", "Bury all waste underground"],
         "choices_zh": ["焚烧减少体积，然后填埋灰烬", "把所有废物倒入海洋", "把所有废物出口到海外", "把所有废物埋在地下"],
         "answer": 0,
         "hint": "Waste-to-Energy plants reduce volume by 90%",
         "hint_zh": "垃圾焚烧厂减少90%的体积",
         "explanation": "**Problem:** Singapore's waste management\n\n**Answer:** Incineration to reduce volume, then landfill ash\n\n**Process:**\n1. Waste collected\n2. Incinerated at 850-1000°C\n3. Volume reduced by 90%\n4. Generates electricity (~3% of demand)\n5. Ash sent to Semakau Landfill\n\n**Why:** Singapore has limited land for landfills"},
        {"id": "hie-ex10", "type": "mcq", "difficulty": "medium",
         "prompt": "What is the effect of rising sea levels on Singapore?",
         "prompt_zh": "海平面上升对新加坡有什么影响？",
         "choices": ["Flooding of low-lying areas and coastal erosion", "More rainfall in central areas", "Colder temperatures", "Increased volcanic activity"],
         "choices_zh": ["低洼地区洪水和海岸侵蚀", "中部地区降雨增加", "温度下降", "火山活动增加"],
         "answer": 0,
         "hint": "Singapore is a low-lying island nation",
         "hint_zh": "新加坡是一个低洼岛国",
         "explanation": "**Problem:** Effect of sea level rise on Singapore\n\n**Answer:** Flooding of low-lying areas and coastal erosion\n\n**Singapore response:**\n- Building sea walls\n- Raising new buildings (minimum platform level)\n- Protecting coastlines\n- Long-term planning (100-year projections)\n\n**At risk:** East Coast, Changi, Marina Bay area"},
        # Hard (5)
        {"id": "hie-ex11", "type": "mcq", "difficulty": "hard",
         "prompt": "What is Singapore's carbon tax rate and purpose?",
         "prompt_zh": "新加坡的碳税税率和目的是什么？",
         "choices": ["$25/tonne CO₂, to incentivize emission reduction", "$100/kg waste, to reduce waste", "$5/litre water, to save water", "No carbon tax exists"],
         "choices_zh": ["$25/吨CO₂，激励减排", "$100/公斤废物，减少废物", "$5/升水，节约用水", "没有碳税"],
         "answer": 0,
         "hint": "Introduced in 2019, rising to $50-80 by 2030",
         "hint_zh": "2019年引入，到2030年升至$50-80",
         "explanation": "**Problem:** Singapore's carbon tax\n\n**Answer:** $25/tonne CO₂, to incentivize emission reduction\n\n**Details:**\n- Introduced: 2019 at $5/tonne\n- Current: $25/tonne (2024)\n- Target: $50-80/tonne by 2030\n- Applies to large emitters (>25,000 tonnes CO₂/year)\n\n**Purpose:** Encourage businesses to reduce emissions, invest in clean technology"},
        {"id": "hie-ex12", "type": "short", "difficulty": "hard",
         "prompt": "What is Singapore's target for green buildings by 2030?",
         "prompt_zh": "新加坡到2030年绿色建筑的目标是多少？",
         "answer": "80%",
         "hint": "Green Mark certified buildings",
         "hint_zh": "绿色建筑标志认证建筑",
         "explanation": "**Problem:** Singapore's green building target\n\n**Answer:** 80% of buildings to be Green Mark certified by 2030\n\n**Green Mark:**\n- BCA's green building rating system\n- Energy efficiency\n- Water efficiency\n- Environmental protection\n\n**Benefits:** Lower energy bills, reduced emissions, healthier indoor environment"},
        {"id": "hie-ex13", "type": "mcq", "difficulty": "hard",
         "prompt": "What is the circular economy concept?",
         "prompt_zh": "什么是循环经济概念？",
         "choices": ["Design out waste; keep materials in use as long as possible", "Produce, use, and throw away", "Import all resources", "Only use natural materials"],
         "choices_zh": ["设计消除废物；尽可能长时间保持材料使用", "生产、使用、丢弃", "进口所有资源", "只使用天然材料"],
         "answer": 0,
         "hint": "Opposite of linear 'take-make-waste' economy",
         "hint_zh": "与线性'获取-制造-废弃'经济相反",
         "explanation": "**Problem:** Circular economy concept\n\n**Answer:** Design out waste; keep materials in use as long as possible\n\n**Principles:**\n1. Eliminate waste and pollution\n2. Circulate products and materials\n3. Regenerate nature\n\n**Singapore examples:**\n- NEWater (water recycling)\n- E-waste recycling (metals recovery)\n- Food waste → compost"},
        {"id": "hie-ex14", "type": "mcq", "difficulty": "hard",
         "prompt": "What is Singapore's Zero Waste Masterplan target?",
         "prompt_zh": "新加坡零废物总体规划的目标是什么？",
         "choices": ["70% recycling rate, extend Semakau lifespan beyond 2035", "Zero waste by 2025", "Close all recycling plants", "Double waste production"],
         "choices_zh": ["70%回收率，将Semakau寿命延长至2035年以后", "2025年零废物", "关闭所有回收厂", "废物产量翻倍"],
         "answer": 0,
         "hint": "Announced in 2019 as part of Year Towards Zero Waste",
         "hint_zh": "2019年作为迈向零废物年的一部分宣布",
         "explanation": "**Problem:** Zero Waste Masterplan target\n\n**Answer:** 70% recycling rate, extend Semakau lifespan beyond 2035\n\n**Current vs Target:**\n- Current recycling: ~59% overall\n- Target: 70% by 2030\n- Semakau filling up → need to reduce, reuse, recycle more\n\n**Focus areas:** E-waste, packaging, food waste"},
        {"id": "hie-ex15", "type": "mcq", "difficulty": "hard",
         "prompt": "Why is Singapore investing in floating solar panels on reservoirs?",
         "prompt_zh": "为什么新加坡在水库上投资浮动太阳能板？",
         "choices": ["Limited land, cooler panels = better efficiency, no agriculture competition", "Solar panels work better underwater", "To create fish habitats", "To make the reservoirs look nicer"],
         "choices_zh": ["土地有限、较凉的板更高效、不与农业竞争", "太阳能板在水下工作更好", "为鱼类创造栖息地", "使水库看起来更好"],
         "answer": 0,
         "hint": "Singapore is land-scarce but has 17 reservoirs",
         "hint_zh": "新加坡土地稀缺但有17个水库",
         "explanation": "**Problem:** Why floating solar on reservoirs\n\n**Answer:** Limited land, cooler panels = better efficiency, no agriculture competition\n\n**Benefits:**\n- Doesn't take land from housing/industry/nature\n- Water cools panels → higher efficiency\n- Reduces evaporation from reservoirs\n- Large surface area available\n\n**Tengeh Reservoir:** One of world's largest floating solar farms (60 MWp)\n\n**Singapore solar target:** 2 GWp by 2030"}
    ]
}

# Load content.json
with open('src/data/content.json', 'r', encoding='utf-8') as f:
    content = json.load(f)

# Find Science subject and add exercises
science = next(s for s in content['subjects'] if s['id'] == 'science')
chapters_updated = 0

for chapter in science['chapters']:
    if chapter['id'] in exercises_by_chapter:
        chapter['exercises'] = exercises_by_chapter[chapter['id']]
        chapters_updated += 1
        print(f"✅ Added {len(chapter['exercises'])} exercises to: {chapter['title']}")

# Save
with open('src/data/content.json', 'w', encoding='utf-8') as f:
    json.dump(content, f, ensure_ascii=False, indent=2)

print(f"\n📊 Updated {chapters_updated} Biology chapters with 60 exercises total!")
print("\n🎉 SEC 4 SCIENCE COMPLETE!")
print("   - Physics: 4 chapters, 60 exercises")
print("   - Chemistry: 4 chapters, 60 exercises")
print("   - Biology: 4 chapters, 60 exercises")
print("   - TOTAL: 12 chapters, 180 exercises")














