import json

# Load the chapters
with open('chapters/sec2-english-chapters.json', 'r', encoding='utf-8') as f:
    chapters = json.load(f)

# Exercise data for all 6 chapters
exercise_data = {
    "complex-sentences-sec2": [
        # Easy (1-5)
        ("Which of the following is a dependent clause?",
         ["The students studied hard", "Although it was raining", "The teacher arrived", "We finished our homework"],
         1, "mcq", "easy"),
        ("Identify the subordinating conjunction: 'I will go to the library unless it closes early.'",
         ["will", "unless", "to", "early"],
         1, "mcq", "easy"),
        ("Which sentence correctly combines these: 'The bus was late. We missed the movie.'",
         ["The bus was late, we missed the movie.", "Because the bus was late, we missed the movie.", "The bus was late we missed the movie.", "The bus was late and we missed the movie."],
         1, "mcq", "easy"),
        ("Select the sentence with correct complex structure:",
         ["While waiting for the MRT I read a book.", "While waiting for the MRT, I read a book.", "While waiting for the MRT; I read a book.", "While waiting for the MRT. I read a book."],
         1, "mcq", "easy"),
        ("Which subordinating conjunction shows cause/effect relationship?",
         ["although", "while", "because", "unless"],
         2, "mcq", "easy"),
        # Medium (6-10)
        ("Fix this fragment: 'When the NEA issued the haze warning.'",
         ["When the NEA issued the haze warning, schools closed early.", "When the NEA issued the haze warning schools closed early.", "The NEA issued the haze warning.", "When the NEA issued."],
         0, "mcq", "medium"),
        ("Combine these sentences using a subordinating conjunction to show contrast: 'The exam was difficult. Most students passed.'",
         ["The exam was difficult, and most students passed.", "Although the exam was difficult, most students passed.", "The exam was difficult because most students passed.", "Most students passed, the exam was difficult."],
         1, "mcq", "medium"),
        ("Which sentence has INCORRECT comma usage with clauses?",
         ["After the rain stopped, we continued playing.", "We continued playing after the rain stopped.", "We continued playing, after the rain stopped.", "If it rains tomorrow, the match will be postponed."],
         2, "mcq", "medium"),
        ("Select the sentence with two dependent clauses:",
         ["When I arrived at school, I realized that I had forgotten my textbook.", "I studied hard, so I did well on the test.", "The teacher explained the lesson carefully.", "Students who work hard usually succeed."],
         0, "mcq", "medium"),
        ("Rewrite to start with a dependent clause: 'I will buy lunch at the hawker center if I have enough money.'",
         ["If I have enough money, I will buy lunch at the hawker center.", "I will buy lunch if I have enough money at the hawker center.", "Lunch at the hawker center if I have enough money.", "Having enough money, I will buy lunch."],
         0, "mcq", "medium"),
        # Hard (11-15)
        ("Identify the error: 'Because Singapore is a multicultural society. We celebrate many festivals.'",
         ["Incorrect subordinating conjunction", "Fragment in first sentence - should be combined", "Missing comma after 'society'", "Wrong verb tense"],
         1, "mcq", "hard"),
        ("Which revision creates the MOST effective complex sentence? Original: 'The government implemented stricter measures. COVID-19 cases were rising.'",
         ["The government implemented stricter measures, and COVID-19 cases were rising.", "Because COVID-19 cases were rising, the government implemented stricter measures.", "COVID-19 cases were rising the government implemented measures.", "The government implemented measures rising COVID-19 cases."],
         1, "mcq", "hard"),
        ("Combine THREE ideas into one complex sentence: 'The HDB upgrading works started. Residents were informed in advance. There were minimal complaints.'",
         ["When the HDB upgrading works started, residents were informed in advance, so there were minimal complaints.", "The HDB upgrading works started; residents were informed; minimal complaints.", "Residents were informed when works started and complained minimally.", "The works started and residents informed with minimal complaints."],
         0, "mcq", "hard"),
        ("Which sentence uses subordination MOST effectively to show logical relationship?",
         ["The student failed the exam, and he did not study.", "Although the student studied diligently, he struggled with the exam format.", "The student failed because he studied.", "When studying, the student failed the exam."],
         1, "mcq", "hard"),
        ("Identify the sentence with correct punctuation of multiple clauses: Topic - Singapore's water management",
         ["Although Singapore is a small country we have achieved water sustainability because we invested in technology.", "Although Singapore is a small country, we have achieved water sustainability because we invested in technology.", "Although, Singapore is a small country we have achieved water sustainability, because we invested in technology.", "Although Singapore is a small country we have achieved, water sustainability because we invested in technology."],
         1, "mcq", "hard"),
    ],
    "active-passive-voice-sec2": [
        # Easy (1-5)
        ("Identify the sentence in passive voice:",
         ["The chef prepared the laksa.", "The laksa was prepared by the chef.", "The chef is preparing laksa.", "The chef prepares laksa daily."],
         1, "mcq", "easy"),
        ("Which is the active voice version? 'The homework was completed by the students.'",
         ["The homework completed the students.", "The students were completing homework.", "The students completed the homework.", "Completing the homework by students."],
         2, "mcq", "easy"),
        ("In passive voice, the subject _____ the action.",
         ["performs", "receives", "creates", "ignores"],
         1, "mcq", "easy"),
        ("Change to passive: 'The teacher explained the lesson.'",
         ["The lesson was explained by the teacher.", "The lesson explained by the teacher.", "The teacher was explained the lesson.", "The lesson is explaining by the teacher."],
         0, "mcq", "easy"),
        ("Which word is essential in passive voice construction?",
         ["have", "be (is/was/were)", "do", "will"],
         1, "mcq", "easy"),
        # Medium (6-10)
        ("Which sentence is MOST appropriate in passive voice?",
         ["I ate chicken rice for lunch.", "The Singapore Botanic Gardens was designated a UNESCO World Heritage Site in 2015.", "My mother cooks dinner every night.", "Students complete their assignments on time."],
         1, "mcq", "medium"),
        ("Change to active voice: 'The national anthem is sung by students every morning.'",
         ["Students sing the national anthem every morning.", "The national anthem sings students every morning.", "Students are singing the anthem.", "Every morning students sung the anthem."],
         0, "mcq", "medium"),
        ("Which passive sentence CANNOT be easily converted to active because the agent is unknown?",
         ["The window was broken by the ball.", "My phone was stolen yesterday.", "The report was written by John.", "The cake was baked by my sister."],
         1, "mcq", "medium"),
        ("In scientific writing, why is passive voice often preferred?",
         ["It sounds more casual", "It emphasizes the action/result rather than the researcher", "It is shorter", "It is easier to write"],
         1, "mcq", "medium"),
        ("Convert to passive and remove the agent: 'Someone left the laboratory door unlocked.'",
         ["Someone left the door unlocked.", "The laboratory door was left unlocked.", "The door unlocked was left.", "Leaving the laboratory door unlocked."],
         1, "mcq", "medium"),
        # Hard (11-15)
        ("Which sentence demonstrates INAPPROPRIATE use of passive voice (should be active)?",
         ["The experiment was conducted at room temperature.", "The form should be submitted by Friday.", "My wallet was taken by me to school.", "The decision was made after careful consideration."],
         2, "mcq", "hard"),
        ("Rewrite in passive voice with correct structure: 'LTA will implement the new bus routes next month.'",
         ["The new bus routes will be implemented by LTA next month.", "The new bus routes will implement by LTA next month.", "LTA will be implementing the new routes.", "Next month will be implemented new bus routes."],
         0, "mcq", "hard"),
        ("Which revision improves this passive sentence? 'Mistakes were made in the calculation, and the wrong amount was charged to customers.'",
         ["We made mistakes in the calculation and charged customers the wrong amount.", "Mistakes in calculation were made charging wrong amounts.", "The calculation had mistakes and customers were charged wrong.", "Making mistakes in calculation charged customers wrong amounts."],
         0, "mcq", "hard"),
        ("Identify the error in this passive construction: 'The new MRT line was opened by commuters last week.'",
         ["Wrong tense", "Illogical agent - commuters did not open the line", "Missing be verb", "Wrong past participle"],
         1, "mcq", "hard"),
        ("In formal report writing, which sentence is MOST appropriate?",
         ["We surveyed 200 students about their study habits.", "200 students were surveyed about their study habits.", "Surveying 200 students about study habits.", "The survey was done by us on 200 students."],
         1, "mcq", "hard"),
    ],
    "persuasive-writing-sec2": [
        # Easy (1-5)
        ("Which is the BEST thesis statement for a persuasive essay?",
         ["This essay is about school uniforms.", "School uniforms are expensive.", "Schools should abolish uniform requirements because they restrict self-expression and create financial burden.", "I think uniforms are bad."],
         2, "mcq", "easy"),
        ("Ethos appeals to:",
         ["Emotions", "Logic and facts", "Credibility and trust", "Humor"],
         2, "mcq", "easy"),
        ("Which sentence uses a statistic as evidence?",
         ["Many students support longer recess.", "According to MOE data, 78% of students participate in at least one CCA.", "Students really need more break time.", "Everyone agrees that recess should be longer."],
         1, "mcq", "easy"),
        ("What is the purpose of addressing counterarguments?",
         ["To confuse readers", "To show you considered opposing views and strengthen your argument", "To make the essay longer", "To disagree with everyone"],
         1, "mcq", "easy"),
        ("Which transition word introduces a counterargument?",
         ["Furthermore", "Therefore", "However", "Additionally"],
         2, "mcq", "easy"),
        # Medium (6-10)
        ("Which piece of evidence is STRONGEST for arguing 'Singapore should increase investment in renewable energy'?",
         ["I believe renewable energy is good.", "My neighbor has solar panels.", "A study by NTU shows solar energy could reduce Singapore's carbon emissions by 25% by 2030.", "Renewable energy is popular."],
         2, "mcq", "medium"),
        ("Identify the persuasive technique: 'Imagine a Singapore where every student has equal access to quality education, regardless of family income.'",
         ["Ethos", "Pathos", "Logos", "None"],
         1, "mcq", "medium"),
        ("Which sentence effectively refutes a counterargument about reducing plastic bag usage?",
         ["Some people say reusable bags are inconvenient, but this is not true.", "While critics argue that reusable bags are inconvenient, studies show that 82% of users adapt within two weeks and prefer them.", "People who disagree are wrong about reusable bags.", "Reusable bags are better despite what others think."],
         1, "mcq", "medium"),
        ("What is WRONG with this evidence? 'Everyone knows that teenagers need more sleep, so school should start later.'",
         ["Uses 'everyone knows' without specific evidence", "Wrong topic", "Too short", "Wrong tense"],
         0, "mcq", "medium"),
        ("Which conclusion is MOST effective for a persuasive essay?",
         ["In conclusion, I talked about homework.", "As this essay has shown, reducing homework would benefit students.", "By implementing a homework cap, schools can improve student wellbeing, reduce stress, and foster genuine love of learning. The time to act is now.", "That is why homework is bad."],
         2, "mcq", "medium"),
        # Hard (11-15)
        ("Evaluate this argument structure: 'Singapore should ban single-use plastics. Plastics harm the environment. Therefore, we should ban them.' What is the weakness?",
         ["Wrong conclusion", "Lacks specific evidence and fails to address counterarguments like economic impact", "Too short", "Uses wrong transition word"],
         1, "mcq", "hard"),
        ("Which paragraph BEST combines ethos, pathos, and logos?",
         ["As a student who commutes daily (ethos), I have witnessed overcrowded buses causing students to arrive late and stressed (pathos). LTA data shows that increasing bus frequency by 15% would reduce wait times by an average of 8 minutes (logos).", "Buses are too crowded and students are late.", "I think buses should come more often because waiting is annoying.", "LTA should increase buses because everyone agrees."],
         0, "mcq", "hard"),
        ("A student argues: 'Schools should eliminate exams because exams cause stress.' What is the BEST counterargument consideration?",
         ["Exams are necessary.", "While exams can cause stress, they also provide structured assessment, prepare students for university entrance requirements, and help identify knowledge gaps for targeted support.", "Some students like exams.", "Stress is bad."],
         1, "mcq", "hard"),
        ("Which revision STRENGTHENS this weak claim? 'Social media is bad for teenagers.'",
         ["Social media is really bad for teenagers.", "Excessive social media use correlates with increased anxiety and decreased face-to-face social skills among teenagers aged 13-17.", "I believe social media harms teenagers.", "Everyone knows social media is harmful."],
         1, "mcq", "hard"),
        ("Analyze this persuasive technique: 'Join thousands of Singapore students who have already benefited from our tutoring program!' This primarily uses:",
         ["Bandwagon appeal (suggesting everyone is doing it)", "Statistical evidence", "Expert testimony", "Logical reasoning"],
         0, "mcq", "hard"),
    ],
    "descriptive-expository-writing-sec2": [
        # Easy (1-5)
        ("Which sentence uses sensory details BEST?",
         ["The food was good.", "The satay was delicious.", "The satay's smoky aroma wafted through the air, and the sweet peanut sauce dripped onto my fingers.", "I ate satay."],
         2, "mcq", "easy"),
        ("Identify the simile:",
         ["The rain fell heavily.", "The rain fell like silver needles.", "The rain was cold.", "Rain poured from the sky."],
         1, "mcq", "easy"),
        ("Which is an example of personification?",
         ["The sun was bright.", "The sun smiled down on the playground.", "The sun rose at 7am.", "We saw the sun."],
         1, "mcq", "easy"),
        ("What type of expository essay explains steps? Topic: 'How to Apply for a Student EZ-Link Card'",
         ["Cause-Effect", "Compare-Contrast", "Process", "Problem-Solution"],
         2, "mcq", "easy"),
        ("Which transition word shows contrast in expository writing?",
         ["Additionally", "Furthermore", "However", "Consequently"],
         2, "mcq", "easy"),
        # Medium (6-10)
        ("Revise this telling sentence to showing: 'The hawker center was busy.'",
         ["The hawker center had many people.", "The hawker center was very busy with customers.", "Diners jostled for seats while hawkers' shouts competed with sizzling woks and clattering plates.", "It was a busy time at the hawker center."],
         2, "mcq", "medium"),
        ("Which sentence uses a metaphor effectively?",
         ["Marina Bay Sands is a tall building.", "Marina Bay Sands is like three towers.", "Marina Bay Sands' rooftop infinity pool is a shimmering sapphire crown above the city.", "Marina Bay Sands was built in 2010."],
         2, "mcq", "medium"),
        ("For a compare-contrast essay about 'HDB flats vs. Condominiums,' which structure is MOST effective?",
         ["Describe all HDB features, then all condo features separately", "Alternate point-by-point: cost (HDB vs condo), amenities (HDB vs condo), space (HDB vs condo)", "Only describe HDB flats", "Write random facts about both"],
         1, "mcq", "medium"),
        ("Identify the weakness in this descriptive sentence: 'The durian smelled bad and tasted bad but some people like it.'",
         ["Wrong tense", "Lacks specific sensory details and uses vague words like 'bad'", "Too long", "Wrong punctuation"],
         1, "mcq", "medium"),
        ("Which topic sentence is BEST for an expository paragraph about cause-effect?",
         ["Singapore has haze.", "This paragraph is about haze.", "Transboundary haze affects Singapore primarily due to forest fires in neighboring Indonesia.", "Haze is bad for health."],
         2, "mcq", "medium"),
        # Hard (11-15)
        ("Which description uses sensory details from MULTIPLE senses most effectively?",
         ["The night market was crowded.", "The market was noisy and bright.", "Under the glaring fluorescent lights, vendors' calls mingled with the crackle of frying oil, while the sweet-sour tang of pineapple tarts competed with the earthy scent of roasted chestnuts; I weaved through the jostling crowd, my hands sticky from pearl milk tea.", "The night market had food, lights, and people."],
         2, "mcq", "hard"),
        ("Evaluate this figurative language: 'The MRT train was a silver snake slithering through underground tunnels.' What makes this effective?",
         ["It uses color words", "The metaphor captures both the train's appearance and motion while evoking the dark, winding nature of tunnels", "It mentions the MRT", "It is a long sentence"],
         1, "mcq", "hard"),
        ("For a problem-solution expository essay on 'Food Waste in School Canteens,' which structure is MOST logical?",
         ["Solution, then problem, then more solutions", "Problem description with causes, then proposed solutions with supporting evidence, then conclusion with call to action", "Only describe the problem", "Random facts about food waste"],
         1, "mcq", "hard"),
        ("Which revision improves this weak description? 'The sunset was beautiful with nice colors.'",
         ["The sunset was very beautiful with pretty colors.", "The sunset had beautiful colors in the sky.", "Amber and crimson streaks blazed across the horizon, reflecting off the glass towers and turning Marina Bay into a mirror of molten gold.", "The beautiful sunset had nice orange and red colors."],
         2, "mcq", "hard"),
        ("Analyze this expository excerpt: 'Singapore's bilingual policy has several effects. First, it promotes multiculturalism. Second, it provides economic advantages. Third, it preserves heritage languages.' What expository technique is used?",
         ["Chronological order", "Enumeration of multiple effects with clear transitions", "Comparison", "Personal narrative"],
         1, "mcq", "hard"),
    ],
    "literary-devices-sec2": [
        # Easy (1-5)
        ("In a story, a character finds an old key. The key most likely symbolizes:",
         ["A door", "Freedom or a new opportunity", "Metal", "Lock"],
         1, "mcq", "easy"),
        ("Identify the type of irony: A character says 'Great weather for a picnic!' during a thunderstorm.",
         ["Dramatic irony", "Situational irony", "Verbal irony", "No irony"],
         2, "mcq", "easy"),
        ("Which is an example of foreshadowing?",
         ["The sun rose at 7am.", "Dark storm clouds gathered as they set out on their journey.", "She ate breakfast.", "The school bell rang."],
         1, "mcq", "easy"),
        ("A theme is:",
         ["The topic of the story", "A central message or lesson expressed as a complete idea", "The setting", "The character's name"],
         1, "mcq", "easy"),
        ("In a story, a broken mirror appears repeatedly. This is an example of:",
         ["Metaphor", "Symbolism through repeated imagery", "Simile", "Alliteration"],
         1, "mcq", "easy"),
        # Medium (6-10)
        ("In a story, readers know a character's drink is poisoned, but the character doesn't. This is:",
         ["Verbal irony", "Situational irony", "Dramatic irony", "Foreshadowing"],
         2, "mcq", "medium"),
        ("Analyze: In a story about Singapore's history, the national flag appears in the opening scene when a character emigrates, and again at the end when her grandchild achieves success. The flag symbolizes:",
         ["National identity, belonging, and generational connection to Singapore", "Colors red and white", "Government", "Cloth"],
         0, "mcq", "medium"),
        ("Which statement is a theme (not just a topic)?",
         ["The story is about friendship.", "Friendship", "True friends support each other through difficult times.", "Two friends"],
         2, "mcq", "medium"),
        ("Identify the situational irony: A fire station _____.",
         ["Has firefighters", "Burns down", "Has red trucks", "Is located downtown"],
         1, "mcq", "medium"),
        ("A story opens: 'As Li Wei pocketed the exam answer key, he smiled. This was going to be easy.' This foreshadows:",
         ["Li Wei will succeed easily", "Li Wei will likely face consequences for cheating", "Li Wei is a good student", "The exam is tomorrow"],
         1, "mcq", "medium"),
        # Hard (11-15)
        ("In a Singaporean short story, rain appears during every major conflict and sunshine appears during resolutions. How does this symbolism function?",
         ["Weather symbolizes the characters' emotional states and reinforces the story's movement between conflict and resolution", "Rain means it is monsoon season", "The author likes weather", "It creates setting"],
         0, "mcq", "hard"),
        ("Analyze this excerpt: 'Ah Ma carefully folded the traditional kebaya her grandmother had given her. Tomorrow, she would donate it to the museum. Her granddaughter preferred jeans.' What theme does this symbolism suggest?",
         ["Clothing changes", "Generational change and the tension between preserving tradition and embracing modernity", "Museums collect clothes", "Jeans are comfortable"],
         1, "mcq", "hard"),
        ("A student writes: 'The theme of the story is friendship.' What is the problem with this theme statement?",
         ["It identifies a topic, not a theme; theme should be a complete statement about friendship like 'True friendship requires honesty even when it is difficult'", "Wrong spelling", "Too short", "Wrong punctuation"],
         0, "mcq", "hard"),
        ("In a story, a character who constantly preaches honesty is revealed to have been lying throughout. This is BEST described as:",
         ["Dramatic irony", "Situational irony that reveals hypocrisy", "Foreshadowing", "Symbolism"],
         1, "mcq", "hard"),
        ("A story about workers building Singapore's early infrastructure repeatedly mentions 'laying foundations.' Beyond literal meaning, this most likely symbolizes:",
         ["Construction work", "Singapore's nation-building and the foundation for future prosperity", "Concrete", "Buildings"],
         1, "mcq", "hard"),
    ],
    "critical-reading-sec2": [
        # Easy (1-5)
        ("Which statement is a FACT?",
         ["Singapore's Changi Airport is the best in the world.", "Singapore consists of 63 islands.", "Chili crab is delicious.", "Everyone should visit Singapore."],
         1, "mcq", "easy"),
        ("Text: 'Jamie slammed his textbook shut and stared out the window, ignoring his friend's question.' What can you infer?",
         ["Jamie is happy", "Jamie is frustrated or upset", "Jamie likes windows", "Jamie is hungry"],
         1, "mcq", "easy"),
        ("Which word indicates an opinion?",
         ["Singapore has four official languages.", "The temperature reached 32 degrees.", "Marina Bay Sands is beautiful.", "The MRT opened in 1987."],
         2, "mcq", "easy"),
        ("An author writing a textbook chapter about Singapore's water management has what purpose?",
         ["To persuade", "To entertain", "To inform", "To confuse"],
         2, "mcq", "easy"),
        ("Which sentence contains bias?",
         ["The government implemented new policies.", "The foolish opposition rejected the obviously superior plan.", "Two parties debated the policy.", "Citizens voted in the election."],
         1, "mcq", "easy"),
        # Medium (6-10)
        ("Text: 'The canteen auntie smiled warmly as she served extra vegetables onto my plate, though I hadn't requested them.' What is the BEST inference about the auntie's motivation?",
         ["She made a mistake", "She dislikes the student", "She cares about students eating healthily", "She has too many vegetables"],
         2, "mcq", "medium"),
        ("Analyze this statement: 'Studies show that 65% of Singaporean students participate in CCAs. Clearly, schools should make CCA mandatory for all students.' What is the logical flaw?",
         ["The conclusion doesn't necessarily follow; 65% participation might indicate sufficient voluntary engagement", "Wrong percentage", "Wrong topic", "No flaw"],
         0, "mcq", "medium"),
        ("An editorial about building a new MRT line uses phrases like 'wasteful spending' and 'questionable necessity.' The author's tone is:",
         ["Neutral", "Critical and disapproving", "Enthusiastic", "Confused"],
         1, "mcq", "medium"),
        ("Which evidence would BEST support distinguishing fact from opinion in this claim: 'Henderson Waves is Singapore's most beautiful bridge.'",
         ["The word 'beautiful' indicates subjective opinion; facts would be 'Henderson Waves is Singapore's highest pedestrian bridge at 36 meters'", "It mentions Henderson Waves", "Bridges are structures", "The sentence has adjectives"],
         0, "mcq", "medium"),
        ("Text: 'After three weeks of drought, the reservoir levels dropped to 40%. Experts warned of potential water rationing.' What can you validly infer?",
         ["It will definitely rain tomorrow", "Singapore may face water supply challenges if drought continues", "Reservoirs are useless", "Experts are always wrong"],
         1, "mcq", "medium"),
        # Hard (11-15)
        ("Analyze this excerpt from an article: 'While proponents claim the new grading system promotes holistic learning, critics rightly point out that it creates confusion and unfairly disadvantages high-achieving students.' Identify the bias.",
         ["The author uses 'rightly' to signal agreement with critics, revealing bias against the new system", "The word 'grading'", "Mention of students", "No bias present"],
         0, "mcq", "hard"),
        ("A travel blog states: 'Singapore offers world-class attractions (Fact). Every tourist will absolutely love Gardens by the Bay (Opinion). The Gardens opened in 2012 (Fact). It's obviously the most impressive garden in Asia (Opinion).' How many opinion statements?",
         ["1", "2", "3", "4"],
         1, "mcq", "hard"),
        ("Complex inference: 'The Principal announced that the school carnival raised $15,000. This exceeded the goal by $3,000. She thanked the Parent Support Group especially.' What can you infer about PSG's role?",
         ["PSG attended the carnival", "PSG likely played a significant role in organizing or contributing to the carnival's success", "PSG set the goal", "PSG received the money"],
         1, "mcq", "hard"),
        ("Evaluate author's purpose: An article presents data on youth unemployment, interviews affected youth, discusses policy options, and concludes with 'Parliament must act now.' The primary purpose is:",
         ["Pure information", "Entertainment", "To inform readers AND persuade policymakers to take action", "To confuse readers"],
         2, "mcq", "hard"),
        ("Critical analysis: 'A recent survey found that 70% of students prefer online learning. This clearly proves that schools should eliminate in-person classes.' What critical reading skill identifies the flaw?",
         ["Recognizing that preference does not equal effectiveness; the author conflates student preference with educational quality and ignores other factors", "Checking the math", "Counting words", "Grammar checking"],
         0, "mcq", "hard"),
    ]
}

# Add exercises to chapters
for chapter in chapters:
    chapter_id = chapter['id']
    if chapter_id in exercise_data:
        exercises = []
        for i, (prompt, choices, answer, ex_type, difficulty) in enumerate(exercise_data[chapter_id], 1):
            exercise = {
                "id": f"{chapter_id}-ex{i}",
                "type": ex_type,
                "difficulty": difficulty,
                "prompt": prompt,
                "prompt_zh": prompt,  # For English subject, keeping English for both
                "choices": choices,
                "choices_zh": choices,
                "answer": answer,
                "explanation": f"This tests understanding of {chapter['title']} concepts.",
                "explanation_zh": f"这测试对{chapter['title_zh']}概念的理解。"
            }
            exercises.append(exercise)
        chapter['exercises'] = exercises

# Save updated chapters
with open('chapters/sec2-english-chapters.json', 'w', encoding='utf-8') as f:
    json.dump(chapters, f, ensure_ascii=False, indent=2)

print(f"Added exercises to {len(chapters)} chapters")
total_exercises = sum(len(ch['exercises']) for ch in chapters)
print(f"Total exercises created: {total_exercises}")
print("Exercise breakdown:")
for ch in chapters:
    print(f"  {ch['title']}: {len(ch['exercises'])} exercises")
