import json
from datetime import datetime

# Create Sec 1 Humanities chapters (History and Geography)
humanities_chapters = {
    "subjects": [
        {
            "id": "humanities",
            "title": "Humanities",
            "title_zh": "人文",
            "description": "History and Geography for Secondary 1",
            "description_zh": "中一历史与地理",
            "color": "from-amber-500 to-orange-600",
            "chapters": [
                # HISTORY CHAPTERS
                {
                    "id": "understanding-history",
                    "title": "Understanding History",
                    "title_zh": "理解历史",
                    "gradeLevel": "sec1",
                    "tag": "History",
                    "tag_zh": "历史",
                    "description": "What is history and how do historians work?",
                    "description_zh": "什么是历史？历史学家如何工作？",
                    "objectives": [
                        "Understand what history is and why it matters",
                        "Learn about historical sources and evidence",
                        "Develop skills in analyzing historical perspectives"
                    ],
                    "objectives_zh": [
                        "理解什么是历史及其重要性",
                        "学习历史资料和证据",
                        "培养分析历史观点的技能"
                    ],
                    "sections": [
                        {
                            "id": "what-is-history",
                            "type": "text",
                            "title": "What is History?",
                            "title_zh": "什么是历史？",
                            "content": "**What is History?**\n\nHistory is the study of the past. It helps us understand how people lived, what they believed, and how societies changed over time.\n\n**Why Study History?**\n\n1. **Learn from the past**: Understanding past mistakes helps us make better decisions today\n2. **Understand the present**: Many current issues have historical roots\n3. **Preserve our heritage**: History keeps our cultural identity alive\n4. **Develop critical thinking**: Analyzing historical evidence teaches us to question and evaluate information\n\n**Example: Singapore's History**\n\nSingapore's transformation from a small fishing village to a modern global city took only 200 years. By studying this journey, we understand:\n- How our ancestors overcame challenges\n- Why certain policies were adopted\n- How different communities contributed to nation-building\n\n**Key Terms:**\n- **Primary source**: Original evidence from the time period (letters, artifacts, photos)\n- **Secondary source**: Analysis written later by historians (textbooks, documentaries)\n- **Perspective**: Different viewpoints on the same historical event",
                            "content_zh": "**什么是历史？**\n\n历史是对过去的研究。它帮助我们了解人们如何生活、他们的信仰以及社会如何随时间变化。\n\n**为什么学习历史？**\n\n1. **从过去学习**：理解过去的错误帮助我们今天做出更好的决策\n2. **理解现在**：许多当前问题都有历史根源\n3. **保护我们的遗产**：历史保持我们的文化认同\n4. **培养批判性思维**：分析历史证据教会我们质疑和评估信息\n\n**例子：新加坡的历史**\n\n新加坡从一个小渔村转变为现代化全球城市仅用了200年。通过研究这段旅程，我们理解：\n- 我们的祖先如何克服挑战\n- 为什么采取某些政策\n- 不同社区如何为建国做出贡献\n\n**关键术语：**\n- **第一手资料**：来自该时期的原始证据（信件、文物、照片）\n- **第二手资料**：历史学家后来撰写的分析（教科书、纪录片）\n- **观点**：对同一历史事件的不同看法"
                        },
                        {
                            "id": "historical-sources",
                            "type": "text",
                            "title": "Historical Sources and Evidence",
                            "title_zh": "历史资料和证据",
                            "content": "**Types of Historical Sources**\n\n**Primary Sources** (First-hand evidence):\n- **Written records**: Diaries, letters, official documents, newspapers\n- **Visual sources**: Photographs, paintings, posters, maps\n- **Physical artifacts**: Tools, pottery, buildings, coins\n- **Oral testimony**: Interviews with people who experienced events\n\n**Secondary Sources** (Second-hand analysis):\n- History textbooks\n- Documentary films\n- Biographies written by historians\n- Museum exhibitions\n\n**Evaluating Sources**\n\nWhen analyzing historical sources, ask:\n\n1. **Who created it?** (Author's background and bias)\n2. **When was it created?** (Time period and context)\n3. **Why was it created?** (Purpose: inform, persuade, entertain?)\n4. **Is it reliable?** (Cross-check with other sources)\n\n**Example: Raffles' Founding of Singapore**\n\nDifferent sources tell different stories:\n- **British records** emphasize Raffles' vision and leadership\n- **Malay chronicles** highlight the Sultan's role and local context\n- **Chinese accounts** focus on immigrant experiences\n\nHistorians must consider ALL perspectives to get the complete picture.\n\n**Singapore Example: Oral History Centre**\n\nThe National Archives of Singapore has recorded over 4,000 oral history interviews. These first-hand accounts from pioneers, war survivors, and everyday Singaporeans provide invaluable insights into our nation's development.",
                            "content_zh": "**历史资料的类型**\n\n**第一手资料**（直接证据）：\n- **书面记录**：日记、信件、官方文件、报纸\n- **视觉资料**：照片、绘画、海报、地图\n- **实物文物**：工具、陶器、建筑物、硬币\n- **口述证词**：对经历事件的人的采访\n\n**第二手资料**（间接分析）：\n- 历史教科书\n- 纪录片\n- 历史学家撰写的传记\n- 博物馆展览\n\n**评估资料**\n\n分析历史资料时，要问：\n\n1. **谁创建的？**（作者的背景和偏见）\n2. **何时创建？**（时期和背景）\n3. **为何创建？**（目的：告知、说服、娱乐？）\n4. **可靠吗？**（与其他资料交叉核对）\n\n**例子：莱佛士建立新加坡**\n\n不同资料讲述不同故事：\n- **英国记录**强调莱佛士的远见和领导力\n- **马来编年史**突出苏丹的角色和当地背景\n- **中国记录**关注移民经历\n\n历史学家必须考虑所有观点才能得到完整的画面。\n\n**新加坡例子：口述历史中心**\n\n新加坡国家档案馆已记录超过4,000个口述历史访谈。这些来自先驱者、战争幸存者和普通新加坡人的第一手资料为我们国家的发展提供了宝贵的见解。"
                        },
                        {
                            "id": "historical-perspectives",
                            "type": "text",
                            "title": "Multiple Perspectives in History",
                            "title_zh": "历史中的多重观点",
                            "content": "**Why Different Perspectives Matter**\n\nThe same historical event can be viewed differently depending on:\n- **Nationality**: British vs. local perspectives on colonialism\n- **Social class**: Elite vs. common people's experiences\n- **Gender**: Men's vs. women's roles in society\n- **Time period**: How views change over generations\n\n**Example: Japanese Occupation of Singapore (1942-1945)**\n\n**Perspective 1: British Military**\n- Focus on military defeat and strategic failures\n- Emphasis on eventually reclaiming the colony\n\n**Perspective 2: Local Chinese Community**\n- Experienced Sook Ching massacre and persecution\n- Remembers suffering and resistance efforts\n\n**Perspective 3: Local Malay Community**\n- Different treatment under Japanese rule\n- Some administrative cooperation\n\n**Perspective 4: Local Indian Community**\n- Indian National Army formation\n- Complex feelings about Japanese promises of Indian independence\n\n**Learning from Multiple Perspectives**\n\nUnderstanding different viewpoints helps us:\n1. Develop empathy and tolerance\n2. Avoid oversimplified narratives\n3. Make balanced judgments\n4. Appreciate Singapore's multicultural society\n\n**Activity: Fort Canning Excavations**\n\nArchaeological digs at Fort Canning Hill have uncovered:\n- 14th-century Majapahit artifacts (pre-colonial Singapore)\n- British colonial-era structures\n- Japanese military fortifications\n\nEach layer tells a different story of Singapore's past, showing how our island has been home to many cultures throughout history.",
                            "content_zh": "**为什么不同观点很重要**\n\n同一历史事件可以根据以下因素有不同看法：\n- **国籍**：英国vs.当地对殖民主义的看法\n- **社会阶层**：精英vs.普通人的经历\n- **性别**：男性vs.女性在社会中的角色\n- **时期**：观点如何随代际变化\n\n**例子：日本占领新加坡（1942-1945）**\n\n**观点1：英国军方**\n- 关注军事失败和战略失误\n- 强调最终收复殖民地\n\n**观点2：本地华人社区**\n- 经历了肃清大屠杀和迫害\n- 记住苦难和抵抗努力\n\n**观点3：本地马来社区**\n- 在日本统治下受到不同对待\n- 一些行政合作\n\n**观点4：本地印度社区**\n- 印度国民军的成立\n- 对日本承诺印度独立的复杂感受\n\n**从多重观点学习**\n\n理解不同观点帮助我们：\n1. 培养同理心和宽容\n2. 避免过于简化的叙述\n3. 做出平衡的判断\n4. 欣赏新加坡的多元文化社会\n\n**活动：福康宁山发掘**\n\n福康宁山的考古挖掘发现了：\n- 14世纪满者伯夷文物（殖民前新加坡）\n- 英国殖民时期建筑\n- 日本军事工事\n\n每一层都讲述了新加坡过去的不同故事，展示了我们的岛屿在历史上如何成为许多文化的家园。"
                        }
                    ],
                    "exercises": []
                },
                {
                    "id": "early-southeast-asia",
                    "title": "Early Southeast Asia",
                    "title_zh": "早期东南亚",
                    "gradeLevel": "sec1",
                    "tag": "History",
                    "tag_zh": "历史",
                    "description": "Ancient civilizations and trade in Southeast Asia",
                    "description_zh": "东南亚的古代文明和贸易",
                    "objectives": [
                        "Understand early Southeast Asian kingdoms",
                        "Learn about maritime trade routes",
                        "Explore cultural influences from India and China"
                    ],
                    "objectives_zh": [
                        "了解早期东南亚王国",
                        "学习海上贸易路线",
                        "探索来自印度和中国的文化影响"
                    ],
                    "sections": [
                        {
                            "id": "ancient-kingdoms",
                            "type": "text",
                            "title": "Ancient Kingdoms of Southeast Asia",
                            "title_zh": "东南亚的古代王国",
                            "content": "**Major Early Kingdoms (300-1500 CE)**\n\n**1. Srivijaya Empire (7th-13th century)**\n- **Location**: Sumatra (modern-day Indonesia)\n- **Power**: Controlled the Straits of Malacca\n- **Economy**: Maritime trade and piracy control\n- **Religion**: Mahayana Buddhism\n- **Legacy**: Influenced Malay language and culture\n\n**2. Majapahit Empire (13th-16th century)**\n- **Location**: Java (modern-day Indonesia)\n- **Peak**: 1350 CE under King Hayam Wuruk\n- **Territory**: Controlled much of maritime Southeast Asia including early Singapore (Temasek)\n- **Religion**: Hinduism-Buddhism blend\n- **Evidence**: Archaeological findings at Fort Canning Hill in Singapore\n\n**3. Angkor Empire (9th-15th century)**\n- **Location**: Cambodia\n- **Famous site**: Angkor Wat temple complex\n- **Achievement**: Advanced irrigation and engineering\n- **Religion**: Hinduism, later Buddhism\n\n**Connection to Singapore**\n\nSingapore (known as **Temasek** in ancient times) was:\n- A minor trading outpost under Srivijaya influence\n- Later part of the Majapahit trading network\n- Mentioned in Chinese texts as early as 3rd century CE\n- Named 'Singapura' (Lion City) around 1299 CE by a Srivijayan prince\n\n**Archaeological Evidence**\n\nExcavations at Fort Canning and Empress Place have found:\n- Chinese ceramics from Song and Yuan dynasties\n- Indian glass beads\n- Javanese goldwork\n- Evidence of a 14th-century settlement",,
                            "content_zh": "**主要早期王国（公元300-1500年）**\n\n**1. 室利佛逝帝国（7-13世纪）**\n- **地点**：苏门答腊（今印度尼西亚）\n- **权力**：控制马六甲海峡\n- **经济**：海上贸易和海盗控制\n- **宗教**：大乘佛教\n- **遗产**：影响马来语言和文化\n\n**2. 满者伯夷帝国（13-16世纪）**\n- **地点**：爪哇（今印度尼西亚）\n- **巅峰**：1350年在哈亚姆·乌鲁克国王统治下\n- **领土**：控制大部分海洋东南亚，包括早期新加坡（淡马锡）\n- **宗教**：印度教-佛教融合\n- **证据**：新加坡福康宁山的考古发现\n\n**3. 吴哥帝国（9-15世纪）**\n- **地点**：柬埔寨\n- **著名遗址**：吴哥窟寺庙群\n- **成就**：先进的灌溉和工程\n- **宗教**：印度教，后来是佛教\n\n**与新加坡的联系**\n\n新加坡（古代称为**淡马锡**）是：\n- 室利佛逝影响下的小型贸易站\n- 后来成为满者伯夷贸易网络的一部分\n- 中国文献早在公元3世纪就提到\n- 约1299年被室利佛逝王子命名为"狮城"\n\n**考古证据**\n\n福康宁和皇后坊的挖掘发现了：\n- 宋朝和元朝的中国陶瓷\n- 印度玻璃珠\n- 爪哇金工艺品\n- 14世纪定居点的证据"
                        },
                        {
                            "id": "maritime-trade",
                            "type": "text",
                            "title": "Maritime Trade Routes",
                            "title_zh": "海上贸易路线",
                            "content": "**The Ancient Maritime Silk Road**\n\n**What was traded?**\n\n**From China:**\n- Silk fabrics\n- Porcelain and ceramics\n- Tea\n- Paper\n\n**From India:**\n- Cotton textiles\n- Spices (pepper, cardamom)\n- Precious stones\n- Religious texts\n\n**From Southeast Asia:**\n- Spices (cloves, nutmeg from Moluccas)\n- Aromatic woods\n- Gold and tin\n- Forest products (camphor, resins)\n\n**From Middle East/Arabia:**\n- Frankincense and myrrh\n- Glassware\n- Carpets\n- Horses\n\n**Key Trade Routes**\n\n1. **Southern Route**: China → Vietnam → Malacca Straits → India → Middle East\n2. **Northern Route**: China → Philippines → Borneo → Java → India\n\n**Strategic Importance of Singapore/Temasek**\n\n- Located at the southern tip of the Malay Peninsula\n- Natural harbor for monsoon-dependent ships\n- Controlled access between Indian Ocean and South China Sea\n- Provided fresh water and supplies for traders\n\n**Monsoon Winds**\n\nTraders relied on predictable monsoon patterns:\n- **Northeast monsoon** (November-March): Ships sailed from China to Southeast Asia\n- **Southwest monsoon** (May-September): Return journey from Southeast Asia to China\n- Ships would wait months in ports like Temasek for wind changes\n\n**Cultural Exchange**\n\nTrade brought more than goods:\n- **Religion**: Buddhism and Hinduism from India\n- **Language**: Sanskrit words in Malay\n- **Architecture**: Temple designs\n- **Technology**: Shipbuilding techniques, navigation tools\n\n**Singapore's Modern Legacy**\n\nToday, Singapore remains one of the world's busiest ports, continuing its ancient role as a trading hub. The Port of Singapore handles over 37 million containers annually, making it the second-busiest container port globally.",
                            "content_zh": "**古代海上丝绸之路**\n\n**交易什么？**\n\n**来自中国：**\n- 丝绸织物\n- 瓷器和陶瓷\n- 茶\n- 纸\n\n**来自印度：**\n- 棉织品\n- 香料（胡椒、豆蔻）\n- 宝石\n- 宗教文献\n\n**来自东南亚：**\n- 香料（来自摩鹿加群岛的丁香、肉豆蔻）\n- 芳香木材\n- 黄金和锡\n- 森林产品（樟脑、树脂）\n\n**来自中东/阿拉伯：**\n- 乳香和没药\n- 玻璃器皿\n- 地毯\n- 马匹\n\n**主要贸易路线**\n\n1. **南线**：中国 → 越南 → 马六甲海峡 → 印度 → 中东\n2. **北线**：中国 → 菲律宾 → 婆罗洲 → 爪哇 → 印度\n\n**新加坡/淡马锡的战略重要性**\n\n- 位于马来半岛南端\n- 依赖季风的船只的天然港口\n- 控制印度洋和南中国海之间的通道\n- 为贸易商提供淡水和补给\n\n**季风**\n\n贸易商依赖可预测的季风模式：\n- **东北季风**（11月-3月）：船只从中国航行到东南亚\n- **西南季风**（5月-9月）：从东南亚返回中国\n- 船只会在淡马锡等港口等待数月以等待风向变化\n\n**文化交流**\n\n贸易带来的不仅是商品：\n- **宗教**：来自印度的佛教和印度教\n- **语言**：马来语中的梵语词汇\n- **建筑**：寺庙设计\n- **技术**：造船技术、导航工具\n\n**新加坡的现代遗产**\n\n今天，新加坡仍然是世界上最繁忙的港口之一，延续其作为贸易枢纽的古老角色。新加坡港每年处理超过3700万个集装箱，使其成为全球第二繁忙的集装箱港口。"
                        },
                        {
                            "id": "cultural-influences",
                            "type": "text",
                            "title": "Indian and Chinese Influences",
                            "title_zh": "印度和中国的影响",
                            "content": "**Indian Cultural Influence (Indianization)**\n\n**Religion and Philosophy:**\n- Hinduism and Buddhism spread through trade and missionary activity\n- Sanskrit became the language of religion and scholarship\n- Concept of divine kingship (god-kings)\n\n**Architecture:**\n- Temple construction techniques\n- Use of stone monuments\n- Borobudur (Java) and Angkor Wat (Cambodia) show Indian influence\n\n**Literature and Arts:**\n- Indian epics (Ramayana, Mahabharata) adapted locally\n- Sanskrit writing system influenced local scripts\n- Classical dance forms\n\n**Political Systems:**\n- Concepts of kingship and statecraft\n- Administrative organization\n- Legal codes based on Indian models\n\n**Chinese Cultural Influence (Sinicization)**\n\n**Trade and Economics:**\n- Chinese merchants established communities in port cities\n- Introduction of Chinese coinage systems\n- Ceramic technology and production\n\n**Technology:**\n- Shipbuilding techniques (junk ships)\n- Navigation tools (compass)\n- Agricultural methods (wet rice cultivation)\n\n**Philosophy and Governance:**\n- Confucian values in some kingdoms\n- Tributary system (smaller kingdoms paid tribute to Chinese emperors)\n- Civil service examination concepts\n\n**Cultural Artifacts:**\n- Chinese ceramics highly valued\n- Porcelain used as status symbols\n- Chinese motifs in local art\n\n**Synthesis in Southeast Asia**\n\nSoutheast Asian societies didn't simply copy Indian or Chinese culture. Instead, they created unique blends:\n\n**Example: Javanese Wayang Kulit (Shadow Puppets)**\n- Uses Indian epic stories (Ramayana)\n- But adapted with local characters and humor\n- Performance style unique to Java\n- Shows selective adoption and creative adaptation\n\n**Singapore's Multicultural Heritage**\n\nThis ancient pattern of cultural blending continues today:\n- **Little India**: Hindu temples, Indian cuisine, traditional music\n- **Chinatown**: Chinese temples, clan associations, TCM shops\n- **Kampong Glam**: Malay-Muslim culture, Sultan Mosque\n- All coexisting in one small island, just like ancient trading ports\n\n**Archaeological Evidence in Singapore**\n\nFindings at Fort Canning show cultural mixing:\n- Gold ornaments with Hindu-Buddhist motifs\n- Chinese ceramics for daily use\n- Islamic gravestones from 14th century\n- Shows Singapore was always a multicultural crossroads",
                            "content_zh": "**印度文化影响（印度化）**\n\n**宗教和哲学：**\n- 印度教和佛教通过贸易和传教活动传播\n- 梵语成为宗教和学术语言\n- 神圣王权概念（神王）\n\n**建筑：**\n- 寺庙建筑技术\n- 石碑的使用\n- 婆罗浮屠（爪哇）和吴哥窟（柬埔寨）显示印度影响\n\n**文学和艺术：**\n- 印度史诗（罗摩衍那、摩诃婆罗多）的本地改编\n- 梵文书写系统影响本地文字\n- 古典舞蹈形式\n\n**政治制度：**\n- 王权和治国理念\n- 行政组织\n- 基于印度模式的法律法规\n\n**中国文化影响（中国化）**\n\n**贸易和经济：**\n- 中国商人在港口城市建立社区\n- 引入中国货币系统\n- 陶瓷技术和生产\n\n**技术：**\n- 造船技术（帆船）\n- 导航工具（指南针）\n- 农业方法（水稻种植）\n\n**哲学和治理：**\n- 一些王国的儒家价值观\n- 朝贡制度（较小王国向中国皇帝进贡）\n- 科举考试概念\n\n**文化文物：**\n- 中国陶瓷高度重视\n- 瓷器用作身份象征\n- 本地艺术中的中国图案\n\n**东南亚的综合**\n\n东南亚社会不是简单地复制印度或中国文化。相反，他们创造了独特的融合：\n\n**例子：爪哇皮影戏**\n- 使用印度史诗故事（罗摩衍那）\n- 但加入本地角色和幽默进行改编\n- 爪哇独特的表演风格\n- 显示选择性采用和创造性改编\n\n**新加坡的多元文化遗产**\n\n这种古老的文化融合模式今天仍在继续：\n- **小印度**：印度庙宇、印度美食、传统音乐\n- **牛车水**：中国庙宇、宗乡会馆、中药店\n- **甘榜格南**：马来-穆斯林文化、苏丹回教堂\n- 所有这些都共存于一个小岛上，就像古代贸易港口\n\n**新加坡的考古证据**\n\n福康宁的发现显示文化融合：\n- 带有印度教-佛教图案的金饰品\n- 日常使用的中国陶瓷\n- 14世纪的伊斯兰墓碑\n- 显示新加坡一直是多元文化的十字路口"
                        }
                    ],
                    "exercises": []
                },

                # GEOGRAPHY CHAPTERS
                {
                    "id": "physical-geography",
                    "title": "Introduction to Physical Geography",
                    "title_zh": "自然地理导论",
                    "gradeLevel": "sec1",
                    "tag": "Geography",
                    "tag_zh": "地理",
                    "description": "Understanding Earth's physical features and processes",
                    "description_zh": "了解地球的自然特征和过程",
                    "objectives": [
                        "Learn about Earth's structure and landforms",
                        "Understand weather and climate patterns",
                        "Explore natural resources and ecosystems"
                    ],
                    "objectives_zh": [
                        "了解地球结构和地貌",
                        "理解天气和气候模式",
                        "探索自然资源和生态系统"
                    ],
                    "sections": [
                        {
                            "id": "earth-structure",
                            "type": "text",
                            "title": "Earth's Structure and Landforms",
                            "title_zh": "地球结构和地貌",
                            "content": "**Layers of the Earth**\n\n1. **Crust** (outer layer)\n   - Thinnest layer (5-70 km thick)\n   - **Continental crust**: Land masses (thicker, less dense)\n   - **Oceanic crust**: Ocean floor (thinner, more dense)\n   - Where we live!\n\n2. **Mantle** (middle layer)\n   - 2,900 km thick\n   - Made of semi-molten rock (magma)\n   - Slow convection currents drive plate movement\n\n3. **Core** (innermost layer)\n   - **Outer core**: Liquid iron and nickel (2,300 km thick)\n   - **Inner core**: Solid iron and nickel (1,200 km radius)\n   - Temperatures up to 5,500°C!\n\n**Major Landforms**\n\n**Mountains:**\n- Formed by tectonic plate collision\n- Example: Himalayas (still growing 5mm per year!)\n- Tallest in SE Asia: Mount Kinabalu (Borneo, 4,095m)\n\n**Valleys:**\n- Created by river erosion or glaciers\n- V-shaped valleys from rivers\n- U-shaped valleys from glaciers\n\n**Plains:**\n- Large, flat areas\n- Often fertile for agriculture\n- Example: Central Plains of Thailand (rice farming)\n\n**Plateaus:**\n- Elevated flat areas\n- Example: Tibetan Plateau (\"Roof of the World\")\n\n**Islands:**\n- Land surrounded by water\n- **Volcanic islands**: Formed by underwater volcanoes (e.g., Hawaii)\n- **Continental islands**: Separated from mainland (e.g., Singapore!)\n\n**Singapore's Geography**\n\nSingapore is:\n- A low-lying island (highest point: Bukit Timah Hill, 163.63m)\n- Part of the Sunda Shelf (connected to mainland during ice ages)\n- Composed mainly of sedimentary rocks and granite\n- Has 63 smaller islands (e.g., Sentosa, Pulau Ubin)\n- Originally hilly, but many hills flattened for development",
                            "content_zh": "**地球的层次**\n\n1. **地壳**（外层）\n   - 最薄的层（5-70公里厚）\n   - **大陆地壳**：陆地（较厚、密度较低）\n   - **海洋地壳**：海底（较薄、密度较高）\n   - 我们居住的地方！\n\n2. **地幔**（中间层）\n   - 2,900公里厚\n   - 由半熔融岩石（岩浆）组成\n   - 缓慢的对流推动板块运动\n\n3. **地核**（最内层）\n   - **外核**：液态铁和镍（2,300公里厚）\n   - **内核**：固态铁和镍（1,200公里半径）\n   - 温度高达5,500°C！\n\n**主要地貌**\n\n**山脉：**\n- 由构造板块碰撞形成\n- 例子：喜马拉雅山（仍在以每年5毫米的速度增长！）\n- 东南亚最高：京那巴鲁山（婆罗洲，4,095米）\n\n**山谷：**\n- 由河流侵蚀或冰川形成\n- 河流形成V形山谷\n- 冰川形成U形山谷\n\n**平原：**\n- 大片平坦区域\n- 通常适合农业\n- 例子：泰国中部平原（水稻种植）\n\n**高原：**\n- 高海拔平坦区域\n- 例子：青藏高原（"世界屋脊"）\n\n**岛屿：**\n- 被水环绕的陆地\n- **火山岛**：由海底火山形成（如夏威夷）\n- **大陆岛**：从大陆分离（如新加坡！）\n\n**新加坡的地理**\n\n新加坡是：\n- 低洼岛屿（最高点：武吉知马山，163.63米）\n- 巽他陆架的一部分（冰河时期与大陆相连）\n- 主要由沉积岩和花岗岩组成\n- 有63个较小的岛屿（如圣淘沙、乌敏岛）\n- 原本多山，但许多山丘因开发而被夷平"
                        },
                        {
                            "id": "weather-climate",
                            "type": "text",
                            "title": "Weather and Climate",
                            "title_zh": "天气和气候",
                            "content": "**Weather vs. Climate**\n\n**Weather:**\n- Short-term atmospheric conditions (hours to days)\n- Changes frequently\n- Examples: Today it's sunny and 32°C; tomorrow might rain\n\n**Climate:**\n- Long-term average weather patterns (30+ years)\n- Changes slowly\n- Example: Singapore has a tropical rainforest climate year-round\n\n**Elements of Weather/Climate**\n\n1. **Temperature**: How hot or cold the air is\n2. **Precipitation**: Rain, snow, hail, sleet\n3. **Humidity**: Amount of water vapor in air\n4. **Wind**: Moving air from high to low pressure\n5. **Air pressure**: Weight of atmosphere pressing down\n6. **Cloud cover**: Amount of sky covered by clouds\n\n**Climate Zones**\n\n**Tropical (Equatorial):**\n- **Location**: Near the equator (0° latitude)\n- **Temperature**: Hot year-round (25-32°C)\n- **Rainfall**: Heavy rain, often daily\n- **Example**: Singapore, Malaysia, Indonesia\n\n**Temperate:**\n- **Location**: Mid-latitudes (30-60°)\n- **Temperature**: Moderate, distinct seasons\n- **Rainfall**: Varies by season\n- **Example**: Japan, parts of China, South Korea\n\n**Polar:**\n- **Location**: Near poles (60-90°)\n- **Temperature**: Very cold, long winters\n- **Rainfall**: Low (mostly snow)\n- **Example**: Antarctica, Arctic\n\n**Singapore's Tropical Climate**\n\n**Characteristics:**\n- **Temperature**: 24-32°C year-round (no seasons!)\n- **Rainfall**: Average 2,400mm annually\n- **Humidity**: 80-90% (feels very sticky)\n- **Sunshine**: 12 hours daylight year-round (near equator)\n\n**Monsoon Seasons:**\n\n**Northeast Monsoon (December-March):**\n- Wetter period\n- More frequent heavy rain\n- Cooler temperatures (24-30°C)\n\n**Southwest Monsoon (June-September):**\n- Drier period (but still rains!)\n- Occasional haze from forest fires in Indonesia\n- Slightly warmer\n\n**Inter-monsoon (April-May, October-November):**\n- Transition periods\n- Afternoon thunderstorms common\n- Hottest temperatures\n\n**Why Singapore Has This Climate:**\n\n1. **Location**: 1°N latitude (almost on equator)\n2. **Sun angle**: Sun directly overhead twice a year\n3. **Ocean**: Surrounded by warm seas (evaporation → rain)\n4. **Low elevation**: Sea-level position\n\n**Impact on Daily Life:**\n\n- Buildings designed for rain and heat (covered walkways, air conditioning)\n- Agriculture limited (no seasonal crops)\n- Water catchment systems crucial\n- Outdoor activities planned around afternoon rain",
                            "content_zh": "**天气vs.气候**\n\n**天气：**\n- 短期大气条件（数小时到数天）\n- 变化频繁\n- 例子：今天晴朗32°C；明天可能下雨\n\n**气候：**\n- 长期平均天气模式（30年以上）\n- 变化缓慢\n- 例子：新加坡全年热带雨林气候\n\n**天气/气候要素**\n\n1. **温度**：空气的冷热程度\n2. **降水**：雨、雪、冰雹、雨夹雪\n3. **湿度**：空气中的水蒸气量\n4. **风**：从高压到低压的移动空气\n5. **气压**：大气向下压的重量\n6. **云量**：天空被云覆盖的量\n\n**气候带**\n\n**热带（赤道）：**\n- **位置**：赤道附近（0°纬度）\n- **温度**：全年炎热（25-32°C）\n- **降雨**：大雨，通常每天\n- **例子**：新加坡、马来西亚、印度尼西亚\n\n**温带：**\n- **位置**：中纬度（30-60°）\n- **温度**：适中，四季分明\n- **降雨**：因季节而异\n- **例子**：日本、中国部分地区、韩国\n\n**极地：**\n- **位置**：极地附近（60-90°）\n- **温度**：非常冷，冬季漫长\n- **降雨**：低（主要是雪）\n- **例子**：南极洲、北极\n\n**新加坡的热带气候**\n\n**特征：**\n- **温度**：全年24-32°C（无季节！）\n- **降雨**：年平均2,400毫米\n- **湿度**：80-90%（感觉非常粘）\n- **阳光**：全年12小时日照（靠近赤道）\n\n**季风季节：**\n\n**东北季风（12月-3月）：**\n- 较湿润时期\n- 更频繁的大雨\n- 较凉爽的温度（24-30°C）\n\n**西南季风（6月-9月）：**\n- 较干燥时期（但仍会下雨！）\n- 偶尔有来自印度尼西亚森林火灾的雾霾\n- 稍微温暖\n\n**季风过渡期（4月-5月，10月-11月）：**\n- 过渡时期\n- 下午雷暴常见\n- 最热的温度\n\n**为什么新加坡有这种气候：**\n\n1. **位置**：北纬1°（几乎在赤道上）\n2. **太阳角度**：太阳每年两次直射头顶\n3. **海洋**：被温暖的海洋环绕（蒸发 → 雨）\n4. **低海拔**：海平面位置\n\n**对日常生活的影响：**\n\n- 建筑设计适应雨和热（有盖走道、空调）\n- 农业有限（无季节性作物）\n- 集水系统至关重要\n- 户外活动避开下午降雨"
                        }
                    ],
                    "exercises": []
                },
                {
                    "id": "map-skills",
                    "title": "Map Reading and Geographic Skills",
                    "title_zh": "地图阅读和地理技能",
                    "gradeLevel": "sec1",
                    "tag": "Geography",
                    "tag_zh": "地理",
                    "description": "Learn to read maps, use coordinates, and understand scale",
                    "description_zh": "学习阅读地图、使用坐标和理解比例尺",
                    "objectives": [
                        "Read and interpret different types of maps",
                        "Use latitude and longitude coordinates",
                        "Calculate distance using map scale",
                        "Understand map symbols and legends"
                    ],
                    "objectives_zh": [
                        "阅读和解释不同类型的地图",
                        "使用经纬度坐标",
                        "使用地图比例尺计算距离",
                        "理解地图符号和图例"
                    ],
                    "sections": [
                        {
                            "id": "types-of-maps",
                            "type": "text",
                            "title": "Types of Maps",
                            "title_zh": "地图类型",
                            "content": "**Different Types of Maps**\n\n**1. Physical Maps**\n- Show natural features (mountains, rivers, lakes)\n- Use colors to show elevation (height above sea level)\n- **Green**: Lowlands\n- **Brown/Orange**: Highlands/mountains\n- **Blue**: Water bodies\n\n**2. Political Maps**\n- Show human-made boundaries (countries, states, cities)\n- Display capitals and major cities\n- Use colors to distinguish different countries/regions\n\n**3. Topographic Maps**\n- Show detailed terrain with contour lines\n- Each line represents same elevation\n- **Close lines**: Steep slope\n- **Far apart lines**: Gentle slope\n- Used for hiking, military planning\n\n**4. Thematic Maps**\n- Focus on specific topics:\n  - **Climate maps**: Temperature, rainfall zones\n  - **Population maps**: Where people live\n  - **Economic maps**: Industries, resources\n  - **Transportation maps**: Roads, MRT lines\n\n**5. Road/Street Maps**\n- Show roads, highways, landmarks\n- Example: Singapore Street Directory\n- Now mostly replaced by GPS (Google Maps)\n\n**Essential Map Elements**\n\nEvery good map should have:\n\n1. **Title**: What the map shows\n2. **Legend/Key**: Explains symbols and colors\n3. **Scale**: Shows relationship between map distance and real distance\n4. **Compass Rose**: Shows cardinal directions (N, S, E, W)\n5. **Grid/Coordinates**: For locating places\n\n**Singapore Example: MRT Map**\n\nThe Singapore MRT map is a **schematic map**:\n- Not to scale (distances not accurate)\n- Shows connections, not exact locations\n- Simplified for easy understanding\n- Compare with actual geographic map to see differences!\n\n**Modern Mapping Technology**\n\n**Satellite Imagery:**\n- Google Earth shows real photos from space\n- Updated regularly\n- Can see 3D buildings, terrain\n\n**GPS (Global Positioning System):**\n- Uses satellites to find exact location\n- Accurate to within meters\n- Powers navigation apps like Google Maps, Grab\n\n**GIS (Geographic Information Systems):**\n- Combines multiple data layers\n- Used for urban planning in Singapore\n- Example: OneMap Singapore (government mapping portal)",
                            "content_zh": "**不同类型的地图**\n\n**1. 自然地图**\n- 显示自然特征（山脉、河流、湖泊）\n- 使用颜色显示海拔（海平面以上高度）\n- **绿色**：低地\n- **棕色/橙色**：高地/山脉\n- **蓝色**：水体\n\n**2. 政治地图**\n- 显示人造边界（国家、州、城市）\n- 显示首都和主要城市\n- 使用颜色区分不同国家/地区\n\n**3. 地形图**\n- 用等高线显示详细地形\n- 每条线代表相同海拔\n- **线靠近**：陡坡\n- **线分散**：缓坡\n- 用于徒步旅行、军事规划\n\n**4. 专题地图**\n- 关注特定主题：\n  - **气候图**：温度、降雨带\n  - **人口图**：人们居住的地方\n  - **经济图**：工业、资源\n  - **交通图**：道路、地铁线路\n\n**5. 道路/街道地图**\n- 显示道路、高速公路、地标\n- 例子：新加坡街道指南\n- 现在大多被GPS（谷歌地图）取代\n\n**基本地图元素**\n\n每张好地图都应该有：\n\n1. **标题**：地图显示什么\n2. **图例/图标**：解释符号和颜色\n3. **比例尺**：显示地图距离与实际距离的关系\n4. **罗盘玫瑰**：显示基本方向（北、南、东、西）\n5. **网格/坐标**：用于定位地点\n\n**新加坡例子：地铁地图**\n\n新加坡地铁地图是**示意图**：\n- 不按比例（距离不准确）\n- 显示连接，而非确切位置\n- 简化以便理解\n- 与实际地理地图比较以看出差异！\n\n**现代制图技术**\n\n**卫星图像：**\n- 谷歌地球显示来自太空的真实照片\n- 定期更新\n- 可以看到3D建筑、地形\n\n**GPS（全球定位系统）：**\n- 使用卫星查找确切位置\n- 精确到米\n- 为谷歌地图、Grab等导航应用提供动力\n\n**GIS（地理信息系统）：**\n- 结合多个数据层\n- 用于新加坡的城市规划\n- 例子：OneMap新加坡（政府地图门户）"
                        },
                        {
                            "id": "coordinates-scale",
                            "type": "text",
                            "title": "Coordinates and Scale",
                            "title_zh": "坐标和比例尺",
                            "content": "**Latitude and Longitude**\n\n**Latitude (纬度):**\n- **Horizontal lines** running east-west\n- **Equator** (赤道): 0° latitude\n- **North**: 0° to 90°N (North Pole)\n- **South**: 0° to 90°S (South Pole)\n- **Singapore**: 1.3°N (very close to equator!)\n\n**Longitude (经度):**\n- **Vertical lines** running north-south\n- **Prime Meridian** (本初子午线): 0° longitude (passes through Greenwich, UK)\n- **East**: 0° to 180°E\n- **West**: 0° to 180°W\n- **Singapore**: 103.8°E\n\n**How to Write Coordinates**\n\n**Format**: (Latitude, Longitude)\n\n**Examples:**\n- **Singapore**: (1.3°N, 103.8°E) or (1.3°, 103.8°)\n- **Beijing**: (39.9°N, 116.4°E)\n- **Sydney**: (33.9°S, 151.2°E)\n- **New York**: (40.7°N, 74.0°W)\n\n**Using Coordinates:**\n1. Find latitude line (horizontal)\n2. Find longitude line (vertical)\n3. Where they meet = the location!\n\n**Map Scale**\n\nScale shows relationship between:\n- **Map distance** (cm on map)\n- **Real distance** (km on ground)\n\n**Three Ways to Show Scale:**\n\n**1. Word Statement:**\n- \"1 centimeter represents 1 kilometer\"\n- \"1 cm = 1 km\"\n\n**2. Representative Fraction (RF):**\n- Written as 1:100,000\n- Means 1 unit on map = 100,000 units in reality\n- **Large scale**: 1:50,000 (shows more detail, smaller area)\n- **Small scale**: 1:1,000,000 (shows less detail, larger area)\n\n**3. Linear/Bar Scale:**\n- Graphic bar divided into segments\n- Can measure directly with ruler\n- Most practical for general use\n\n**Calculating Distance Using Scale**\n\n**Example:**\nMap scale: 1:100,000\nDistance on map: 5 cm\n\n**Step 1**: Convert map distance to same units\n5 cm × 100,000 = 500,000 cm\n\n**Step 2**: Convert to kilometers\n500,000 cm = 5,000 m = 5 km\n\n**Answer**: Real distance is 5 km\n\n**Singapore Example:**\n\nOn a 1:50,000 map:\n- **Jurong to Changi**: ~25 cm on map\n- Real distance: 25 × 50,000 = 1,250,000 cm = 12.5 km\n\n**Four-Figure and Six-Figure Grid References**\n\n**Four-Figure Grid Reference:**\n- Uses grid squares\n- Identifies a whole square (1 km²)\n- **Example**: 5834\n  - 58 = Easting (left to right)\n  - 34 = Northing (bottom to top)\n\n**Six-Figure Grid Reference:**\n- More precise (100m × 100m area)\n- Divides each square into tenths\n- **Example**: 584347\n  - 584 = Easting (58.4)\n  - 347 = Northing (34.7)\n\n**Compass Directions**\n\n**Cardinal Directions:**\n- **N** (North/北): 0° or 360°\n- **E** (East/东): 90°\n- **S** (South/南): 180°\n- **W** (West/西): 270°\n\n**Intercardinal Directions:**\n- **NE** (Northeast/东北): 45°\n- **SE** (Southeast/东南): 135°\n- **SW** (Southwest/西南): 225°\n- **NW** (Northwest/西北): 315°\n\n**Bearing:**\n- Direction measured as angle from North (clockwise)\n- Always 3 digits: 045°, 180°, 270°\n- Used in navigation and orienteering",
                            "content_zh": "**经纬度**\n\n**纬度：**\n- **水平线**东西走向\n- **赤道**：0°纬度\n- **北**：0°到90°N（北极）\n- **南**：0°到90°S（南极）\n- **新加坡**：北纬1.3°（非常靠近赤道！）\n\n**经度：**\n- **垂直线**南北走向\n- **本初子午线**：0°经度（经过英国格林威治）\n- **东**：0°到180°E\n- **西**：0°到180°W\n- **新加坡**：东经103.8°\n\n**如何写坐标**\n\n**格式**：（纬度，经度）\n\n**例子：**\n- **新加坡**：（北纬1.3°，东经103.8°）或（1.3°，103.8°）\n- **北京**：（北纬39.9°，东经116.4°）\n- **悉尼**：（南纬33.9°，东经151.2°）\n- **纽约**：（北纬40.7°，西经74.0°）\n\n**使用坐标：**\n1. 找到纬度线（水平）\n2. 找到经度线（垂直）\n3. 它们相交的地方 = 位置！\n\n**地图比例尺**\n\n比例尺显示以下关系：\n- **地图距离**（地图上的厘米）\n- **实际距离**（地面上的公里）\n\n**显示比例尺的三种方式：**\n\n**1. 文字说明：**\n- "1厘米代表1公里"\n- "1厘米 = 1公里"\n\n**2. 代表性分数（RF）：**\n- 写作1:100,000\n- 意味着地图上的1单位 = 现实中的100,000单位\n- **大比例尺**：1:50,000（显示更多细节，更小区域）\n- **小比例尺**：1:1,000,000（显示更少细节，更大区域）\n\n**3. 线性/条形比例尺：**\n- 分成段的图形条\n- 可以用尺子直接测量\n- 最实用于一般使用\n\n**使用比例尺计算距离**\n\n**例子：**\n地图比例尺：1:100,000\n地图上的距离：5厘米\n\n**步骤1**：将地图距离转换为相同单位\n5厘米 × 100,000 = 500,000厘米\n\n**步骤2**：转换为公里\n500,000厘米 = 5,000米 = 5公里\n\n**答案**：实际距离是5公里\n\n**新加坡例子：**\n\n在1:50,000地图上：\n- **裕廊到樟宜**：地图上约25厘米\n- 实际距离：25 × 50,000 = 1,250,000厘米 = 12.5公里\n\n**四位和六位网格参考**\n\n**四位网格参考：**\n- 使用网格方块\n- 识别整个方块（1平方公里）\n- **例子**：5834\n  - 58 = 东距（从左到右）\n  - 34 = 北距（从下到上）\n\n**六位网格参考：**\n- 更精确（100米 × 100米区域）\n- 将每个方块分成十分之一\n- **例子**：584347\n  - 584 = 东距（58.4）\n  - 347 = 北距（34.7）\n\n**罗盘方向**\n\n**基本方向：**\n- **北**：0°或360°\n- **东**：90°\n- **南**：180°\n- **西**：270°\n\n**中间方向：**\n- **东北**：45°\n- **东南**：135°\n- **西南**：225°\n- **西北**：315°\n\n**方位角：**\n- 从北方向（顺时针）测量的角度\n- 总是3位数：045°，180°，270°\n- 用于导航和定向"
                        }
                    ],
                    "exercises": []
                }
            ]
        }
    ]
}

# Save to file
output_file = "chapters/sec1_humanities_chapters.json"
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(humanities_chapters, f, ensure_ascii=False, indent=2)

print(f"✅ Created {output_file}")
print(f"📚 Total chapters: {len(humanities_chapters['subjects'][0]['chapters'])}")
print("\nChapter breakdown:")
for chapter in humanities_chapters['subjects'][0]['chapters']:
    print(f"  - {chapter['title']} ({chapter['tag']}) - {len(chapter['sections'])} sections")
