#!/usr/bin/env python3
"""
FINAL: Add all 45 remaining Geography exercises (15 per chapter for chapters 2-4)
"""

import json

# Compact exercise template - all exercises follow AO1 (5), AO2 (5), AO3 (5) pattern

def create_geography_exercises():
    """Generate all remaining exercises for chapters 2, 3, 4"""

    exercises = {
        # CHAPTER 2: WATER RESOURCES (15 exercises)
        "chapter2": [
            # AO1: Knowledge (5 MCQ/short answer)
            {"id":"ex1-evaporation","type":"mcq","difficulty":"easy","prompt":"Which process changes water from liquid to gas?","prompt_zh":"哪个过程将水从液态变为气态？","choices":["Evaporation","Condensation","Precipitation","Infiltration"],"choices_zh":["蒸发","凝结","降水","渗透"],"answer":0,"explanation":"Evaporation is liquid→gas. Condensation is gas→liquid. Precipitation is falling water. Infiltration is water soaking into ground.","explanation_zh":"蒸发是液态→气态。凝结是气态→液态。降水是降落的水。渗透是水渗入地下。","hint":"Think about water on a hot day.","hint_zh":"想想炎热天气的水。"},
            {"id":"ex2-four-taps","type":"mcq","difficulty":"easy","prompt":"Which is NOT one of Singapore's Four National Taps?","prompt_zh":"哪一项不是新加坡的四大国家水喉之一？","choices":["Home rainwater harvesting","Local catchment","Imported water","NEWater"],"choices_zh":["家庭雨水收集","本地集水区","进口水","新生水"],"answer":0,"explanation":"Four Taps: 1)Local catchment 2)Imported 3)NEWater 4)Desalination. Home harvesting encouraged but not official tap.","explanation_zh":"四大水喉：1)本地集水区 2)进口 3)新生水 4)淡化。家庭收集受鼓励但非官方水喉。","hint":"Official PUB sources.","hint_zh":"公用事业局官方来源。"},
            {"id":"ex3-industrial-use","type":"mcq","difficulty":"easy","prompt":"Semiconductor manufacturing uses water for what purpose?","prompt_zh":"半导体制造使用水的目的是什么？","choices":["Industrial use","Domestic use","Agricultural use","Recreational use"],"choices_zh":["工业用途","家庭用途","农业用途","娱乐用途"],"answer":0,"explanation":"Manufacturing=industrial. Semiconductors need ultra-pure water for production processes.","explanation_zh":"制造=工业。半导体需要超纯水用于生产过程。","hint":"Factories=?","hint_zh":"工厂=？"},
            {"id":"ex4-pollution-type","type":"mcq","difficulty":"medium","prompt":"Farm fertilizers washing into rivers is which pollution type?","prompt_zh":"农场肥料流入河流是哪种污染类型？","choices":["Agricultural runoff","Industrial waste","Sewage","Oil spill"],"choices_zh":["农业径流","工业废物","污水","石油泄漏"],"answer":0,"explanation":"From farms=agricultural. Runoff=washes off land into water. Fertilizers/pesticides from farms pollute waterways.","explanation_zh":"来自农场=农业。径流=从土地冲入水中。来自农场的肥料/农药污染水道。","hint":"From farm land.","hint_zh":"来自农田。"},
            {"id":"ex5-newater-source","type":"short","difficulty":"medium","prompt":"What is NEWater made from?","prompt_zh":"新生水是由什么制成的？","answer":"Treated wastewater","answer_zh":"处理过的废水","explanation":"NEWater=NEW water from WASTE water. Uses advanced membrane+UV treatment to recycle wastewater into ultra-clean water.","explanation_zh":"新生水=来自废水的新水。使用先进膜+紫外线处理将废水回收为超清洁水。","hint":"Recycled from...","hint_zh":"从...回收"},

            # AO2: Understanding/Explanation (5)
            {"id":"ex6-water-scarcity","type":"short","difficulty":"medium","prompt":"Explain why Singapore faces water scarcity despite 2400mm annual rainfall.","prompt_zh":"解释为什么新加坡尽管年降雨量2400毫米仍面临水资源短缺。","answer":"Small land area limits catchment despite high rainfall","answer_zh":"小土地面积限制集水区尽管降雨量高","explanation":"Water availability=rainfall×catchment area. Singapore: high rain BUT small land=limited catchment. Also high evaporation in tropical climate.","explanation_zh":"水可用性=降雨量×集水区。新加坡：高降雨但小土地=有限集水区。热带气候蒸发率也高。","hint":"Think about land size.","hint_zh":"想想土地大小。"},
            {"id":"ex7-pollution-effect","type":"short","difficulty":"medium","prompt":"Explain ONE environmental effect of water pollution.","prompt_zh":"解释水污染的一种环境影响。","answer":"Death of aquatic life due to toxins or oxygen depletion","answer_zh":"由于毒素或缺氧导致水生生物死亡","explanation":"Polluted water kills fish/plants through: 1)Toxic chemicals 2)Oxygen depletion from algal blooms 3)Disrupted food chains.","explanation_zh":"受污染的水通过以下方式杀死鱼/植物：1)有毒化学品 2)藻华导致缺氧 3)食物链破坏。","hint":"What happens to fish?","hint_zh":"鱼会怎样？"},
            {"id":"ex8-marina-barrage","type":"short","difficulty":"medium","prompt":"How does Marina Barrage help Singapore's water supply?","prompt_zh":"滨海堤坝如何帮助新加坡的水供应？","answer":"Keeps seawater out creating freshwater reservoir","answer_zh":"阻止海水形成淡水水库","explanation":"Marina Barrage=dam at Marina Bay mouth. Closes to keep seawater out. Collects city rainwater creating 15th reservoir covering 1/6 of Singapore.","explanation_zh":"滨海堤坝=滨海湾口的大坝。关闭以阻止海水。收集城市雨水形成第15个水库，覆盖新加坡1/6。","hint":"What does a barrage do?","hint_zh":"堤坝做什么？"},
            {"id":"ex9-conservation","type":"short","difficulty":"hard","prompt":"Suggest TWO household water conservation methods.","prompt_zh":"建议两种家庭节水方法。","answer":"Install water-efficient fittings and take shorter showers","answer_zh":"安装节水配件并缩短淋浴时间","explanation":"Valid methods: 1)WELS-rated taps/toilets 2)Shorter showers (5min not 10) 3)Turn off tap while brushing 4)Fix leaks 5)Full loads only in washing machine.","explanation_zh":"有效方法：1)WELS评级水龙头/马桶 2)缩短淋浴（5分钟非10分钟）3)刷牙时关水龙头 4)修复漏水 5)洗衣机仅满载。","hint":"Daily home activities.","hint_zh":"日常家庭活动。"},
            {"id":"ex10-desalination","type":"short","difficulty":"hard","prompt":"Give ONE advantage and ONE disadvantage of desalination.","prompt_zh":"给出海水淡化的一个优点和一个缺点。","answer":"Advantage: weather-independent; Disadvantage: high energy cost","answer_zh":"优点：不受天气影响；缺点：能源成本高","explanation":"Advantages: unlimited seawater source, drought-proof, reduces import dependence. Disadvantages: expensive energy use, brine discharge harms marine life, high infrastructure cost.","explanation_zh":"优点：无限的海水来源、抗旱、减少进口依赖。缺点：昂贵的能源使用、盐水排放损害海洋生物、高基础设施成本。","hint":"Reliability vs cost.","hint_zh":"可靠性与成本。"},

            # AO3: Data Interpretation (5)
            {"id":"ex11-rainfall-pattern","type":"mcq","difficulty":"medium","prompt":"Graph shows Singapore's highest rainfall in December (300mm), lowest in February (120mm). What pattern?","prompt_zh":"图表显示新加坡12月降雨最高（300mm），2月最低（120mm）。什么模式？","choices":["Seasonal variation with monsoons","Random pattern","Yearly increase","Climate change decrease"],"choices_zh":["季风的季节性变化","随机模式","年度增加","气候变化减少"],"answer":0,"explanation":"December=NE monsoon (wet). February=drier period. Shows seasonal pattern from monsoon influence.","explanation_zh":"12月=东北季风（湿）。2月=较干旱时期。显示季风影响的季节模式。","hint":"Monsoon seasons.","hint_zh":"季风季节。"},
            {"id":"ex12-consumption-trend","type":"short","difficulty":"medium","prompt":"Household water use decreased from 165L/person/day (2003) to 141L (2022). Suggest ONE reason.","prompt_zh":"家庭用水从165升/人/天（2003）降至141升（2022）。建议一个原因。","answer":"WELS water-efficient fixtures installed","answer_zh":"安装了WELS节水装置","explanation":"Decrease due to: 1)Mandatory WELS since 2009 2)Education campaigns 3)Pricing incentives 4)Better technology (dual-flush toilets) 5)Greater awareness.","explanation_zh":"减少原因：1)2009年起强制WELS 2)教育活动 3)价格激励 4)更好技术（双冲马桶）5)更大意识。","hint":"Government policies.","hint_zh":"政府政策。"},
            {"id":"ex13-water-budget","type":"short","difficulty":"hard","prompt":"Basin gets 200mm rain. 50mm evaporates, 30mm transpires, 100mm runs off. Remaining water (mm)?","prompt_zh":"流域收到200mm降水。50mm蒸发，30mm蒸腾，100mm径流。剩余水（mm）？","answer":"20","answer_zh":"20","validator":"numeric","explanation":"Water budget=Input-Outputs. Input:200mm. Outputs:50+30+100=180mm. Remaining:200-180=20mm.","explanation_zh":"水量平衡=输入-输出。输入：200mm。输出：50+30+100=180mm。剩余：200-180=20mm。","hint":"Subtract all losses.","hint_zh":"减去所有损失。"},
            {"id":"ex14-newater-process","type":"mcq","difficulty":"hard","prompt":"NEWater: Wastewater→Microfiltration→Reverse Osmosis→UV→NEWater. Which removes dissolved salts?","prompt_zh":"新生水：废水→微滤→反渗透→紫外线→新生水。哪个去除溶解盐？","choices":["Reverse Osmosis","Microfiltration","UV Disinfection","All steps"],"choices_zh":["反渗透","微滤","紫外线消毒","所有步骤"],"answer":0,"explanation":"Microfiltration=removes particles/bacteria. Reverse Osmosis=removes dissolved salts/minerals through membrane. UV=kills microorganisms.","explanation_zh":"微滤=去除颗粒/细菌。反渗透=通过膜去除溶解盐/矿物质。紫外线=杀死微生物。","hint":"Membrane removes...","hint_zh":"膜去除..."},
            {"id":"ex15-abc-waters","type":"short","difficulty":"hard","prompt":"ABC Waters Programme stands for Active, Beautiful, Clean. How does it help water management?","prompt_zh":"ABC水务计划代表活跃、美丽、清洁。它如何帮助水管理？","answer":"Integrates drains/reservoirs with parks managing stormwater while creating recreation","answer_zh":"将排水渠/水库与公园整合管理雨水同时创建休闲","explanation":"ABC Waters transforms drains/reservoirs into recreational parks. Benefits: 1)Natural filtration improves water quality 2)Increases catchment 3)Flood management 4)Community awareness. Examples: Bishan Park, Kallang River.","explanation_zh":"ABC水务将排水渠/水库转变为休闲公园。好处：1)自然过滤改善水质 2)增加集水区 3)洪水管理 4)社区意识。示例：碧山公园、加冷河。","hint":"Dual purpose.","hint_zh":"双重目的。"}
        ],

        # CHAPTER 3: TROPICAL RAINFORESTS (15 exercises)
        "chapter3": [
            # AO1 (5)
            {"id":"ex1-climate","type":"mcq","difficulty":"easy","prompt":"Tropical rainforest climate characteristic?","prompt_zh":"热带雨林气候特征？","choices":["High temp & rain year-round","Hot summers cold winters","Low rainfall dry season","Cold all year"],"choices_zh":["全年高温高降雨","炎热夏季寒冷冬季","低降雨旱季","全年寒冷"],"answer":0,"explanation":"Equatorial climate: 25-28°C constant, >2000mm rain, 75-95% humidity, NO seasons.","explanation_zh":"赤道气候：25-28°C恒定，>2000mm降雨，75-95%湿度，无季节。","hint":"Near equator.","hint_zh":"赤道附近。"},
            {"id":"ex2-layers","type":"mcq","difficulty":"easy","prompt":"Which rainforest layer gets MOST sunlight?","prompt_zh":"哪个雨林层获得最多阳光？","choices":["Emergent","Canopy","Understory","Forest floor"],"choices_zh":["突出层","林冠层","林下层","林地层"],"answer":0,"explanation":"Layers top→bottom: Emergent (45-55m, most sun)→Canopy (30-45m)→Understory (10-30m)→Floor (0-10m, dark).","explanation_zh":"层次顶→底：突出层（45-55米，最多阳光）→林冠层（30-45米）→林下层（10-30米）→林地层（0-10米，黑暗）。","hint":"Highest layer?","hint_zh":"最高层？"},
            {"id":"ex3-drip-tips","type":"short","difficulty":"easy","prompt":"Purpose of drip tips on leaves?","prompt_zh":"叶子滴水尖的用途？","answer":"Channel rainwater off quickly","answer_zh":"快速引导雨水离开","explanation":"Constant heavy rain. Pointed tips channel water off→prevents mold, allows photosynthesis to continue.","explanation_zh":"持续大雨。尖端引导水离开→防止霉菌，允许光合作用继续。","hint":"Heavy rain problem.","hint_zh":"大雨问题。"},
            {"id":"ex4-deforestation","type":"mcq","difficulty":"medium","prompt":"Major deforestation cause in Indonesia/Malaysia?","prompt_zh":"印尼/马来西亚森林砍伐的主要原因？","choices":["Palm oil plantations","Urban expansion","Gold mining","Tourism"],"choices_zh":["棕榈油种植园","城市扩张","金矿","旅游"],"answer":0,"explanation":"Indonesia+Malaysia=top palm oil producers. Large-scale forest clearing for oil palm. Used in food/cosmetics/biofuels.","explanation_zh":"印尼+马来西亚=顶级棕榈油生产国。大规模森林清除用于油棕。用于食品/化妆品/生物燃料。","hint":"Export crop.","hint_zh":"出口作物。"},
            {"id":"ex5-sg-forest","type":"short","difficulty":"medium","prompt":"% of Singapore's original rainforest remains?","prompt_zh":"新加坡原始雨林剩余%？","answer":"0.25","answer_zh":"0.25","validator":"numeric","explanation":"Was 100% forest. Now only 0.25% in Bukit Timah, Central Catchment reserves. 95%+ lost to development. Current 47% green cover includes parks/planted trees.","explanation_zh":"曾100%森林。现仅0.25%在武吉知马、中央集水区保护区。95%+因开发而失去。当前47%绿化包括公园/种植树。","hint":"<1%, very small.","hint_zh":"<1%，非常小。"},

            # AO2 (5)
            {"id":"ex6-buttress-roots","type":"short","difficulty":"medium","prompt":"Explain how buttress roots help rainforest trees.","prompt_zh":"解释板根如何帮助雨林树木。","answer":"Provide stability in shallow nutrient-poor soil","answer_zh":"在浅层营养贫乏土壤中提供稳定性","explanation":"Rainforest soil=thin, nutrients in vegetation not soil. Large buttress roots above ground provide stability, support tall trees against wind.","explanation_zh":"雨林土壤=薄，营养在植被中非在土壤中。地上大板根提供稳定性，支撑高树抵御风。","hint":"Support function.","hint_zh":"支撑功能。"},
            {"id":"ex7-biodiversity","type":"short","difficulty":"medium","prompt":"Why are rainforests called 'biodiversity hotspots'?","prompt_zh":"为什么雨林被称为'生物多样性热点'？","answer":"Contain highest species diversity on Earth","answer_zh":"包含地球上最高的物种多样性","explanation":"Amazon alone: 40,000+ plant species, millions of insects/animals. Constant warm/wet climate, complex structure (layers), long evolutionary time=maximum diversity.","explanation_zh":"仅亚马逊：40,000+植物种，数百万昆虫/动物。持续温暖/潮湿气候，复杂结构（层次），长进化时间=最大多样性。","hint":"Species count.","hint_zh":"物种数量。"},
            {"id":"ex8-deforestation-impact","type":"short","difficulty":"medium","prompt":"Explain ONE environmental impact of deforestation.","prompt_zh":"解释森林砍伐的一种环境影响。","answer":"Increased CO2 and climate change","answer_zh":"CO2增加和气候变化","explanation":"Trees store carbon. Cutting releases CO2. Also less photosynthesis=less CO2 absorbed. Result: more greenhouse gases→climate change. Other impacts: species extinction, soil erosion, floods.","explanation_zh":"树木储存碳。砍伐释放CO2。也更少光合作用=更少CO2吸收。结果：更多温室气体→气候变化。其他影响：物种灭绝、土壤侵蚀、洪水。","hint":"Carbon and climate.","hint_zh":"碳和气候。"},
            {"id":"ex9-selective-logging","type":"short","difficulty":"hard","prompt":"Explain how selective logging is more sustainable than clear-cutting.","prompt_zh":"解释选择性伐木如何比皆伐更可持续。","answer":"Only cuts certain trees allowing forest to regenerate naturally","answer_zh":"只砍伐某些树木允许森林自然再生","explanation":"Selective logging: cut only mature/certain trees, leave young trees/seedlings. Forest structure intact, biodiversity maintained, natural regeneration. Clear-cutting: remove ALL trees→complete ecosystem destruction, slow/no recovery.","explanation_zh":"选择性伐木：只砍伐成熟/某些树木，留下幼树/幼苗。森林结构完整，生物多样性维持，自然再生。皆伐：移除所有树木→完全生态系统破坏，缓慢/无恢复。","hint":"Partial vs total removal.","hint_zh":"部分vs全部移除。"},
            {"id":"ex10-agroforestry","type":"short","difficulty":"hard","prompt":"What is agroforestry and how does it help conservation?","prompt_zh":"什么是农林业，它如何帮助保护？","answer":"Growing crops under tree canopy combining agriculture with conservation","answer_zh":"在树冠下种植作物结合农业与保护","explanation":"Agroforestry=agriculture+forestry. Grow crops (coffee, cocoa) under forest canopy. Benefits: 1)Trees preserved 2)Shade for crops 3)Farmers earn income 4)Biodiversity maintained 5)Soil protected.","explanation_zh":"农林业=农业+林业。在森林树冠下种植作物（咖啡、可可）。好处：1)树木保留 2)作物遮荫 3)农民收入 4)生物多样性维持 5)土壤保护。","hint":"Dual land use.","hint_zh":"双重土地利用。"},

            # AO3 (5)
            {"id":"ex11-distribution-map","type":"mcq","difficulty":"medium","prompt":"Map shows rainforests mainly between Tropics of Cancer/Capricorn. Why?","prompt_zh":"地图显示雨林主要在南北回归线之间。为什么？","choices":["Equatorial climate with year-round warmth and rain","Four distinct seasons","Cold winters","Low rainfall"],"choices_zh":["赤道气候全年温暖和降雨","四个明显季节","寒冷冬季","低降雨"],"answer":0,"explanation":"Equatorial belt (23°N-23°S): direct sun year-round→constant warmth. Rising air→high rain. Perfect conditions for rainforests.","explanation_zh":"赤道带（23°N-23°S）：全年直射阳光→恒定温暖。上升空气→高降雨。雨林的完美条件。","hint":"Equator location.","hint_zh":"赤道位置。"},
            {"id":"ex12-forest-loss","type":"short","difficulty":"medium","prompt":"Graph shows Amazon lost 20% forest in 50 years. Suggest main cause.","prompt_zh":"图表显示亚马逊50年失去20%森林。建议主要原因。","answer":"Cattle ranching and soybean farming","answer_zh":"养牛和大豆种植","explanation":"Amazon deforestation drivers: 1)Cattle ranching (largest) 2)Soybean farms 3)Logging 4)Mining. Brazil=major beef/soy exporter→forest→farmland conversion.","explanation_zh":"亚马逊森林砍伐驱动因素：1)养牛（最大）2)大豆农场 3)伐木 4)采矿。巴西=主要牛肉/大豆出口国→森林→农田转换。","hint":"Agriculture purpose.","hint_zh":"农业目的。"},
            {"id":"ex13-temperature-data","type":"mcq","difficulty":"hard","prompt":"Temperature data: rainforest 26°C all months, temperate forest 5°C winter to 20°C summer. What explains difference?","prompt_zh":"温度数据：雨林全月26°C，温带森林冬5°C夏20°C。什么解释差异？","choices":["Rainforest near equator with constant sun angle","Rainforest higher elevation","Temperate has more trees","Temperate has more rain"],"choices_zh":["雨林靠近赤道太阳角恒定","雨林海拔更高","温带树木更多","温带降雨更多"],"answer":0,"explanation":"Equator: sun overhead year-round→constant temp. Temperate (higher latitudes): sun angle varies→seasons with temp variation.","explanation_zh":"赤道：太阳全年在头顶→恒定温度。温带（更高纬度）：太阳角变化→季节与温度变化。","hint":"Latitude and sun.","hint_zh":"纬度和太阳。"},
            {"id":"ex14-species-count","type":"short","difficulty":"hard","prompt":"Why does rainforest floor have fewer species than canopy despite more space?","prompt_zh":"为什么雨林林地层尽管空间更多但物种比林冠层少？","answer":"Limited sunlight on forest floor reduces photosynthesis and food availability","answer_zh":"林地层有限阳光减少光合作用和食物可用性","explanation":"Forest floor: <2% sunlight penetrates. Less photosynthesis→fewer plants→less food→fewer animals. Canopy: abundant light→rich vegetation→insects→birds→biodiversity.","explanation_zh":"林地层：<2%阳光穿透。光合作用少→植物少→食物少→动物少。林冠层：充足光线→丰富植被→昆虫→鸟类→生物多样性。","hint":"Light availability.","hint_zh":"光的可用性。"},
            {"id":"ex15-conservation-evaluation","type":"short","difficulty":"hard","prompt":"Protected areas conserve rainforests but indigenous people lose access. Is this fair? Explain.","prompt_zh":"保护区保护雨林但原住民失去进入权。这公平吗？解释。","answer":"Both valid: conservation important BUT indigenous rights must be respected","answer_zh":"两者都有效：保护重要但原住民权利必须受尊重","explanation":"Complex issue. Conservation argument: biodiversity preservation for global good. Indigenous argument: ancestral lands, sustainable traditional use for centuries. Best solution: co-management involving indigenous communities in conservation while respecting rights.","explanation_zh":"复杂问题。保护论点：为全球利益保护生物多样性。原住民论点：祖先土地，数百年可持续传统使用。最佳解决方案：共同管理让原住民社区参与保护同时尊重权利。","hint":"Consider both perspectives.","hint_zh":"考虑双方观点。"}
        ],

        # CHAPTER 4: MANGROVES (15 exercises)
        "chapter4": [
            # AO1 (5)
            {"id":"ex1-location","type":"mcq","difficulty":"easy","prompt":"Where are mangroves found?","prompt_zh":"红树林在哪里发现？","choices":["Intertidal zone (between tides)","Deep ocean","Mountain streams","Desert oases"],"choices_zh":["潮间带（潮汐之间）","深海","山溪","沙漠绿洲"],"answer":0,"explanation":"Mangroves=coastal forests in INTERTIDAL zone. Area between high/low tide. Submerged at high tide, exposed at low tide. Saltwater/brackish environment.","explanation_zh":"红树林=潮间带沿海森林。高潮/低潮之间区域。高潮时淹没，低潮时暴露。盐水/半咸水环境。","hint":"Tide-affected area.","hint_zh":"潮汐影响区域。"},
            {"id":"ex2-pneumatophores","type":"mcq","difficulty":"easy","prompt":"What are pneumatophores?","prompt_zh":"什么是呼吸根？","choices":["Breathing roots sticking up from mud","Floating seeds","Salt glands","Fish species"],"choices_zh":["从泥中伸出的呼吸根","漂浮种子","盐腺","鱼类"],"answer":0,"explanation":"Pneumatophores=specialized breathing roots. Stick up vertically from muddy soil. Covered with pores (lenticels) for gas exchange. Absorb oxygen at low tide. Example: Avicennia mangroves.","explanation_zh":"呼吸根=专门的呼吸根。从泥泞土壤垂直伸出。覆盖气孔（皮孔）进行气体交换。低潮时吸收氧气。示例：Avicennia红树林。","hint":"Breathing adaptation.","hint_zh":"呼吸适应。"},
            {"id":"ex3-singapore-mangrove","type":"short","difficulty":"easy","prompt":"Name ONE major mangrove site in Singapore.","prompt_zh":"说出新加坡的一个主要红树林地点。","answer":"Sungei Buloh Wetland Reserve","answer_zh":"双溪布洛湿地保护区","explanation":"Major Singapore mangrove sites: 1)Sungei Buloh (130 ha, ASEAN Heritage Park) 2)Pulau Ubin (Chek Jawa) 3)Pasir Ris Park 4)Berlayer Creek. Total 7.37 ha (down from 13% in 1820s).","explanation_zh":"新加坡主要红树林地点：1)双溪布洛（130公顷，东盟遗产公园）2)乌敏岛（仄爪哇）3)巴西立公园 4)柏雅溪。总计7.37公顷（从1820年代的13%下降）。","hint":"ASEAN Heritage Park.","hint_zh":"东盟遗产公园。"},
            {"id":"ex4-salt-adaptation","type":"mcq","difficulty":"medium","prompt":"How do some mangroves deal with salt?","prompt_zh":"一些红树林如何处理盐？","choices":["Secrete salt through leaf glands","Store salt in roots only","Avoid saltwater completely","Drink freshwater only"],"choices_zh":["通过叶腺分泌盐","只在根中储存盐","完全避免盐水","只喝淡水"],"answer":0,"explanation":"Mangrove salt adaptations: 1)Salt exclusion (roots filter) 2)Salt excretion (leaf glands secrete, visible crystals) 3)Salt accumulation (old leaves, then drop). Example: Avicennia has salt glands.","explanation_zh":"红树林盐适应：1)盐排斥（根过滤）2)盐排泄（叶腺分泌，可见晶体）3)盐积累（老叶，然后脱落）。示例：Avicennia有盐腺。","hint":"Leaf glands.","hint_zh":"叶腺。"},
            {"id":"ex5-vivipary","type":"short","difficulty":"medium","prompt":"What is vivipary in mangroves?","prompt_zh":"红树林中的胎生是什么？","answer":"Seeds germinate while still on parent tree","answer_zh":"种子在仍在母树上时发芽","explanation":"Vivipary=live birth. Mangrove seeds germinate ON tree (not in soil). Develop into propagules (torpedo-shaped seedlings). When mature, drop and stick into mud. If miss, float to new location. Better survival than ungerminated seeds.","explanation_zh":"胎生=活产。红树林种子在树上发芽（非土壤中）。发育为繁殖体（鱼雷形幼苗）。成熟时，掉落并插入泥中。如果错过，漂浮到新位置。比未发芽种子存活率更高。","hint":"Germinate on tree.","hint_zh":"在树上发芽。"},

            # AO2 (5)
            {"id":"ex6-coastal-protection","type":"short","difficulty":"medium","prompt":"Explain how mangroves protect coastlines.","prompt_zh":"解释红树林如何保护海岸线。","answer":"Roots absorb wave energy reducing erosion and storm damage","answer_zh":"根吸收波浪能量减少侵蚀和风暴破坏","explanation":"Mangrove protection: 1)Tangled roots slow waves→less erosion 2)Buffer storms/tsunamis 3)Trap sediment→build land 4)Prevent flooding. Example: Sungei Buloh protects inland Singapore areas.","explanation_zh":"红树林保护：1)缠结根减缓波浪→减少侵蚀 2)缓冲风暴/海啸 3)捕获沉积物→建立土地 4)防止洪水。示例：双溪布洛保护新加坡内陆地区。","hint":"Wave barrier.","hint_zh":"波浪屏障。"},
            {"id":"ex7-nursery-function","type":"short","difficulty":"medium","prompt":"Why are mangroves called 'nurseries of the sea'?","prompt_zh":"为什么红树林被称为'海洋的育儿场'？","answer":"Provide shelter and food for young fish and crustaceans to grow","answer_zh":"为幼鱼和甲壳类动物提供庇护和食物以成长","explanation":"Mangroves=fish nursery because: 1)Roots provide hiding from predators 2)Calm protected waters 3)Rich food (leaf litter, plankton) 4)Breeding ground for eggs. 80% commercial fish depend on mangroves. Singapore: mudskippers, crabs, prawns breed here.","explanation_zh":"红树林=鱼育儿场因为：1)根提供躲避捕食者的藏身处 2)平静保护水域 3)丰富食物（落叶、浮游生物）4)卵的繁殖地。80%商业鱼类依赖红树林。新加坡：弹涂鱼、螃蟹、对虾在这里繁殖。","hint":"Baby fish habitat.","hint_zh":"幼鱼栖息地。"},
            {"id":"ex8-carbon-storage","type":"short","difficulty":"medium","prompt":"Why do mangroves store more carbon than rainforests despite being smaller?","prompt_zh":"为什么红树林尽管更小但比雨林储存更多碳？","answer":"Store carbon in waterlogged soil where decomposition is very slow","answer_zh":"在水涝土壤中储存碳，分解非常缓慢","explanation":"Mangroves store 3-5× more carbon than rainforests because: 1)Waterlogged anaerobic soil=slow decomposition 2)Carbon buried in mud for centuries 3)Both above-ground biomass AND below-ground storage. Climate change mitigation value.","explanation_zh":"红树林储存的碳是雨林的3-5倍，因为：1)水涝缺氧土壤=缓慢分解 2)碳在泥中埋藏数百年 3)地上生物量和地下储存。气候变化缓解价值。","hint":"Soil conditions.","hint_zh":"土壤条件。"},
            {"id":"ex9-development-threat","type":"short","difficulty":"hard","prompt":"Explain why coastal development is a major threat to mangroves.","prompt_zh":"解释为什么沿海开发是红树林的主要威胁。","answer":"Land reclamation for ports, industries, housing replaces mangrove areas","answer_zh":"为港口、工业、住房填海造地取代红树林区域","explanation":"Coastal development threats: 1)Land reclamation (Singapore lost 90% mangroves) 2)Port/industrial zones 3)Aquaculture (shrimp farms) 4)Tourism resorts. Economic benefits outweigh conservation→habitat loss. Example: Tanjong Pagar terminal built on former mangroves.","explanation_zh":"沿海开发威胁：1)填海造地（新加坡失去90%红树林）2)港口/工业区 3)水产养殖（虾场）4)旅游度假村。经济利益超过保护→栖息地丧失。示例：丹戎巴葛码头建在原红树林上。","hint":"Human land use.","hint_zh":"人类土地利用。"},
            {"id":"ex10-restoration","type":"short","difficulty":"hard","prompt":"Suggest TWO strategies to conserve and restore mangroves.","prompt_zh":"建议两种保护和恢复红树林的策略。","answer":"Designate protected areas and replant mangroves in degraded areas","answer_zh":"指定保护区并在退化地区重新种植红树林","explanation":"Conservation strategies: 1)Protected reserves (Sungei Buloh ASEAN Heritage Park) 2)Restoration/replanting (NParks at Pulau Semakau) 3)Sustainable use regulations 4)Community education 5)International cooperation (Ramsar Convention). Singapore example: prawn farm→Sungei Buloh nature park (1993).","explanation_zh":"保护策略：1)保护区（双溪布洛东盟遗产公园）2)恢复/重新种植（NParks在实马高岛）3)可持续利用法规 4)社区教育 5)国际合作（拉姆萨尔公约）。新加坡示例：虾场→双溪布洛自然公园（1993）。","hint":"Protection + restoration.","hint_zh":"保护+恢复。"},

            # AO3 (5)
            {"id":"ex11-distribution-tropics","type":"mcq","difficulty":"medium","prompt":"Map shows mangroves concentrated 25°N-25°S. Why?","prompt_zh":"地图显示红树林集中在25°N-25°S。为什么？","choices":["Tropical climate with warm temps needed for growth","Cold water currents","Deep ocean","High elevation"],"choices_zh":["生长需要的热带气候温暖温度","寒流","深海","高海拔"],"answer":0,"explanation":"Mangroves need >20°C water temperature. Found in tropical/subtropical (25°N-25°S) with warm conditions. Cannot survive freezing temps. Also need sheltered coastlines (protected from strong waves).","explanation_zh":"红树林需要>20°C水温。在热带/亚热带（25°N-25°S）温暖条件下发现。无法在冰冻温度下生存。也需要受保护海岸线（免受强浪）。","hint":"Temperature requirement.","hint_zh":"温度要求。"},
            {"id":"ex12-bird-count","type":"short","difficulty":"medium","prompt":"Data shows 200+ migratory bird species at Sungei Buloh. Why do birds stop here?","prompt_zh":"数据显示双溪布洛有200+候鸟种。为什么鸟类停在这里？","answer":"Rest and refuel during migration along East Asian-Australasian Flyway","answer_zh":"在东亚-澳大拉西亚迁飞路线迁徙期间休息和补充能量","explanation":"Sungei Buloh on East Asian-Australasian Flyway (migration route). Birds fly from Siberia→Southeast Asia→Australia. Need stopover to: 1)Rest 2)Feed (mudflats rich in crabs/worms) 3)Restore energy for next flight leg. Peak season: Sept-March.","explanation_zh":"双溪布洛在东亚-澳大拉西亚迁飞路线（迁徙路线）上。鸟类从西伯利亚飞→东南亚→澳大利亚。需要中途停留：1)休息 2)觅食（泥滩富含螃蟹/蠕虫）3)恢复能量用于下一段飞行。高峰季节：9-3月。","hint":"Migration route.","hint_zh":"迁徙路线。"},
            {"id":"ex13-shrimp-farm-impact","type":"mcq","difficulty":"hard","prompt":"Study shows area converted from mangrove to shrimp farm. Likely environmental impact?","prompt_zh":"研究显示从红树林转变为虾场的区域。可能的环境影响？","choices":["Increased coastal erosion and biodiversity loss","Better water quality","More fish","Cooler climate"],"choices_zh":["增加沿海侵蚀和生物多样性丧失","更好水质","更多鱼","更凉爽气候"],"answer":0,"explanation":"Mangrove→shrimp farm impacts: 1)Loss of coastal protection→erosion 2)Biodiversity loss (no nursery) 3)Pollution from farm waste 4)Less carbon storage 5)Fewer commercial fish. Short-term economic gain, long-term environmental damage.","explanation_zh":"红树林→虾场影响：1)失去海岸保护→侵蚀 2)生物多样性丧失（无育儿场）3)农场废物污染 4)碳储存减少 5)商业鱼类减少。短期经济收益，长期环境破坏。","hint":"Lost ecosystem services.","hint_zh":"失去的生态系统服务。"},
            {"id":"ex14-sea-level-rise","type":"short","difficulty":"hard","prompt":"Rising sea levels threaten mangroves. How can mangroves adapt if inland space is available?","prompt_zh":"海平面上升威胁红树林。如果内陆空间可用，红树林如何适应？","answer":"Migrate landward to higher ground","answer_zh":"向陆地迁移到更高地面","explanation":"With sea level rise, mangroves can: 1)Migrate inland (if space available) 2)Colonize new areas at higher elevation 3)Build sediment faster to keep up. BUT barriers: coastal development blocks migration→'coastal squeeze'→mangroves drown. Need migration corridors.","explanation_zh":"随着海平面上升，红树林可以：1)向内陆迁移（如果空间可用）2)在更高海拔殖民新区域 3)更快建立沉积物以跟上。但障碍：沿海开发阻止迁移→'海岸挤压'→红树林淹没。需要迁移走廊。","hint":"Move to higher ground.","hint_zh":"移至更高地面。"},
            {"id":"ex15-sungei-buloh-history","type":"short","difficulty":"hard","prompt":"Sungei Buloh was a prawn farm (1980s), became nature park (1993), ASEAN Heritage Park (2003). What does this show about Singapore's priorities?","prompt_zh":"双溪布洛是虾场（1980年代），成为自然公园（1993），东盟遗产公园（2003）。这显示了新加坡的什么优先事项？","answer":"Shift from economic exploitation to conservation and environmental protection","answer_zh":"从经济开发转向保护和环境保护","explanation":"Shows: 1)Evolving priorities: economy→environment 2)Recognition of ecosystem value 3)International conservation commitment 4)Urban-nature integration 5)Education/recreation value. Model showing development and nature can coexist. Singapore balances growth with green spaces.","explanation_zh":"显示：1)演变的优先事项：经济→环境 2)认识生态系统价值 3)国际保护承诺 4)城市-自然整合 5)教育/休闲价值。显示开发和自然可以共存的模型。新加坡平衡增长与绿地。","hint":"Priority change over time.","hint_zh":"随时间优先事项变化。"}
        ]
    }

    return exercises

def main():
    print("=" * 60)
    print("FINAL GEOGRAPHY EXERCISES INTEGRATION")
    print("=" * 60)

    # Load data
    print("\n[1/4] Loading geography chapters...")
    with open('chapters/geography-sec1-chapters.json', 'r', encoding='utf-8') as f:
        data = json.load(f)

    print("Current state:")
    for i, ch in enumerate(data['chapters'], 1):
        print(f"  Chapter {i} ({ch['title']}): {len(ch['exercises'])} exercises")

    # Generate exercises
    print("\n[2/4] Generating all exercises...")
    exercises = create_geography_exercises()

    # Add to chapters
    print("\n[3/4] Adding exercises to chapters...")
    data['chapters'][1]['exercises'] = exercises['chapter2']
    print(f"  ✓ Chapter 2: Added {len(exercises['chapter2'])} exercises")

    data['chapters'][2]['exercises'] = exercises['chapter3']
    print(f"  ✓ Chapter 3: Added {len(exercises['chapter3'])} exercises")

    data['chapters'][3]['exercises'] = exercises['chapter4']
    print(f"  ✓ Chapter 4: Added {len(exercises['chapter4'])} exercises")

    # Save
    print("\n[4/4] Saving updated file...")
    with open('chapters/geography-sec1-chapters.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print("\n" + "=" * 60)
    print("✓ SUCCESS! All Geography exercises complete!")
    print("=" * 60)
    print("\nFinal counts:")
    for i, ch in enumerate(data['chapters'], 1):
        print(f"  Chapter {i} ({ch['title']}): {len(ch['exercises'])} exercises")

    total = sum(len(ch['exercises']) for ch in data['chapters'])
    print(f"\n  TOTAL: {total} exercises across {len(data['chapters'])} chapters")
    print(f"  All chapters have complete AO1+AO2+AO3 exercises!")
    print("\nNext step: Integrate into main content.json")

if __name__ == "__main__":
    main()
